"background" = "class=\"autumn highlight background\" style=\"background-color: #ffffea; \""
"comment" = "class=\"comment\" style=\"color: #065905;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #aeeeee; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #a0342f; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #065905; \""
"module" = "class=\"module\" style=\"\""
"operator" = "class=\"operator\" style=\"\""
"string" = "class=\"string\" style=\"color: #a0342f;\""
"text" = "class=\"text\" style=\"color: #000000; \""
