"function" = "class=\"function\" style=\"color: #e6b450;\""
"markup.list" = "class=\"markup list\" style=\"color: #e6b450;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #aad94c;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #e6b450;\""
"keyword" = "class=\"keyword\" style=\"color: #ff8f40;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #e6b450;\""
"string" = "class=\"string\" style=\"color: #aad94c;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #ff8f40;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #59c2ff;\""
"keyword.control" = "class=\"keyword control\" style=\"color: #e6b450;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #e6b450;\""
"operator" = "class=\"operator\" style=\"color: #ff8f40; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #aad94c;\""
"special" = "class=\"special\" style=\"color: #ff8f40;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #ff8f40; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #0f1419; \""
"punctuation" = "class=\"punctuation\" style=\"color: #bfbdb6;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #e6b450;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #5c6773; \""
"tag" = "class=\"tag\" style=\"color: #59c2ff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f07178;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #59c2ff;\""
"constructor" = "class=\"constructor\" style=\"color: #aad94c;\""
"variable" = "class=\"variable\" style=\"color: #bfbdb6;\""
"text" = "class=\"text\" style=\"color: #bfbdb6; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff8f40;\""
"module" = "class=\"module\" style=\"color: #59c2ff; \""
"constant" = "class=\"constant\" style=\"color: #d2a6ff;\""
"string.special" = "class=\"string special\" style=\"color: #e6b450;\""
"type" = "class=\"type\" style=\"color: #59c2ff;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #ff8f40;\""
"namespace" = "class=\"namespace\" style=\"color: #59c2ff;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ff8f40; \""
"label" = "class=\"label\" style=\"color: #ff8f40;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
