"constant.numeric" = "class=\"constant numeric\" style=\"color: #59c0dc;\""
"function" = "class=\"function\" style=\"color: #289cbc;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #232d38;\""
"markup.list" = "class=\"markup list\" style=\"color: #d32c5d;\""
"function.builtin" = "class=\"function builtin\" style=\"font-weight: bold; color: #289cbc; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #289cbc;\""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #a58023; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #dc7759;\""
"string" = "class=\"string\" style=\"color: #23a580;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #232d38;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #dc7759;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #232d38;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #a58023; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #7fdc59; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #a58023;\""
"operator" = "class=\"operator\" style=\"color: #dc7759; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #23a580;\""
"special" = "class=\"special\" style=\"color: #7fdc59;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #dc7759; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: ; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #f6fbd6; \""
"punctuation" = "class=\"punctuation\" style=\"color: #dc7759;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d32c5d;\""
"comment" = "class=\"comment\" style=\"color: #627d9d;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #23a580;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #dc597f;\""
"type.builtin" = "class=\"type builtin\" style=\"font-weight: bold; color: #d32c5d; \""
"constructor" = "class=\"constructor\" style=\"color: #dc597f;\""
"variable" = "class=\"variable\" style=\"color: #232d38;\""
"text" = "class=\"text\" style=\"color: #161c23; \""
"module" = "class=\"module\" style=\"color: #d32c5d; \""
"constant" = "class=\"constant\" style=\"color: #23a580;\""
"type" = "class=\"type\" style=\"color: #dc597f;\""
"attribute" = "class=\"attribute\" style=\"color: #dc7759;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #23a580;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #59c0dc;\""
"namespace" = "class=\"namespace\" style=\"color: #d32c5d;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #a58023; \""
"label" = "class=\"label\" style=\"color: #59c0dc;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
