"function" = "class=\"function\" style=\"color: #8aadf4;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #8bd5ca;\""
"markup.list" = "class=\"markup list\" style=\"color: #c6a0f6;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #eed49f;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #f5bde6;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #a6da95;\""
"keyword" = "class=\"keyword\" style=\"color: #c6a0f6;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #8aadf4;\""
"string" = "class=\"string\" style=\"color: #a6da95;\""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #ee99a0; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ed8796;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #f4dbd6; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f5bde6;\""
"operator" = "class=\"operator\" style=\"color: #91d7e3; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a6da95;\""
"special" = "class=\"special\" style=\"color: #8aadf4;\""
"function.macro" = "class=\"function macro\" style=\"color: #c6a0f6;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #24273a; \""
"punctuation" = "class=\"punctuation\" style=\"color: #939ab7;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #8aadf4;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #8087a2; \""
"tag" = "class=\"tag\" style=\"color: #c6a0f6;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #f0c6c6;\""
"constant.character" = "class=\"constant character\" style=\"color: #8bd5ca;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ed8796;\""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"color: #8bd5ca;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #c6a0f6;\""
"constructor" = "class=\"constructor\" style=\"color: #7dc4e4;\""
"variable" = "class=\"variable\" style=\"color: #cad3f5;\""
"text" = "class=\"text\" style=\"color: #cad3f5; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #f5a97f;\""
"module" = "class=\"module\" style=\"color: #8aadf4; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #91d7e3;\""
"constant" = "class=\"constant\" style=\"color: #f5a97f;\""
"string.special" = "class=\"string special\" style=\"color: #8aadf4;\""
"type" = "class=\"type\" style=\"color: #eed49f;\""
"attribute" = "class=\"attribute\" style=\"color: #8aadf4;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #8bd5ca;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #f5a97f;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #b7bdf8;\""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-style: italic; color: #c6a0f6; \""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #8aadf4; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #f5a97f; \""
"label" = "class=\"label\" style=\"color: #7dc4e4;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
