"function" = "class=\"function\" style=\"color: #8caaee;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #81c8be;\""
"markup.list" = "class=\"markup list\" style=\"color: #ca9ee6;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #e5c890;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #f4b8e4;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #a6d189;\""
"keyword" = "class=\"keyword\" style=\"color: #ca9ee6;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #8caaee;\""
"string" = "class=\"string\" style=\"color: #a6d189;\""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #ea999c; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #e78284;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #f2d5cf; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f4b8e4;\""
"operator" = "class=\"operator\" style=\"color: #99d1db; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a6d189;\""
"special" = "class=\"special\" style=\"color: #8caaee;\""
"function.macro" = "class=\"function macro\" style=\"color: #ca9ee6;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #303446; \""
"punctuation" = "class=\"punctuation\" style=\"color: #949cbb;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #8caaee;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #838ba7; \""
"tag" = "class=\"tag\" style=\"color: #ca9ee6;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #eebebe;\""
"constant.character" = "class=\"constant character\" style=\"color: #81c8be;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e78284;\""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"color: #81c8be;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #ca9ee6;\""
"constructor" = "class=\"constructor\" style=\"color: #85c1dc;\""
"variable" = "class=\"variable\" style=\"color: #c6d0f5;\""
"text" = "class=\"text\" style=\"color: #c6d0f5; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ef9f76;\""
"module" = "class=\"module\" style=\"color: #8caaee; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #99d1db;\""
"constant" = "class=\"constant\" style=\"color: #ef9f76;\""
"string.special" = "class=\"string special\" style=\"color: #8caaee;\""
"type" = "class=\"type\" style=\"color: #e5c890;\""
"attribute" = "class=\"attribute\" style=\"color: #8caaee;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #81c8be;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ef9f76;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #babbf1;\""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-style: italic; color: #ca9ee6; \""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #8caaee; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #ef9f76; \""
"label" = "class=\"label\" style=\"color: #85c1dc;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
