"background" = "class=\"autumn highlight background\" style=\"background-color: #ffffff; \""
"module" = "class=\"module\" style=\"color: black_parent; \""
"namespace" = "class=\"namespace\" style=\"color: black_parent;\""
"operator" = "class=\"operator\" style=\"\""
"text" = "class=\"text\" style=\"color: #000000; \""
"variable" = "class=\"variable\" style=\"color: blue_child;\""
