"constant.numeric" = "class=\"constant numeric\" style=\"color: #d699b6;\""
"function" = "class=\"function\" style=\"color: #a7c080;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #7fbbb3;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #e69875;\""
"markup.list" = "class=\"markup list\" style=\"color: #e67e80;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #e69875;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #859289;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #a7c080; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #d3c6aa;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #7fbbb3; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #dbbc7f; \""
"keyword" = "class=\"keyword\" style=\"color: #e67e80;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #7fbbb3;\""
"string" = "class=\"string\" style=\"color: #83c092;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #83c092;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #d3c6aa;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #859289;\""
"variable.builtin" = "class=\"variable builtin\" style=\"font-style: italic; color: #d699b6; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #7fbbb3; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #a7c080;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #d699b6;\""
"operator" = "class=\"operator\" style=\"color: #e69875; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a7c080;\""
"special" = "class=\"special\" style=\"color: #7fbbb3;\""
"function.macro" = "class=\"function macro\" style=\"color: #a7c080;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #2d353b; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9da9a0;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d699b6;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #859289; \""
"tag" = "class=\"tag\" style=\"color: #e69875;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e67e80;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #e69875; \""
"constructor" = "class=\"constructor\" style=\"color: #a7c080;\""
"variable" = "class=\"variable\" style=\"color: #d3c6aa;\""
"text" = "class=\"text\" style=\"color: #d3c6aa; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #e67e80;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #a7c080;\""
"module" = "class=\"module\" style=\"color: #dbbc7f; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #7fbbb3;\""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #d699b6;\""
"constant" = "class=\"constant\" style=\"color: #d3c6aa;\""
"string.special" = "class=\"string special\" style=\"color: #dbbc7f;\""
"type" = "class=\"type\" style=\"color: #dbbc7f;\""
"attribute" = "class=\"attribute\" style=\"font-style: italic; color: #d699b6; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #d699b6; \""
"constant.builtin" = "class=\"constant builtin\" style=\"font-style: italic; color: #d699b6; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #e67e80; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #a7c080;\""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #dbbc7f; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #859289;\""
"label" = "class=\"label\" style=\"color: #e69875;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
