"constant.numeric" = "class=\"constant numeric\" style=\"color: #6cb6ff;\""
"function" = "class=\"function\" style=\"color: #dcbdfb;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #96d0ff;\""
"keyword" = "class=\"keyword\" style=\"color: #f47067;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #c69026;\""
"string" = "class=\"string\" style=\"color: #96d0ff;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f69d50;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #adbac7;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #f47067;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #6cb6ff;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #f47067;\""
"operator" = "class=\"operator\" style=\"color: #96d0ff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #57ab5a;\""
"special" = "class=\"special\" style=\"color: #96d0ff;\""
"function.macro" = "class=\"function macro\" style=\"color: #dcbdfb;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #22272e; \""
"punctuation" = "class=\"punctuation\" style=\"color: #adbac7;\""
"markup.link.text" = "class=\"markup link text\" style=\"text-decoration: underline; color: #96d0ff; \""
"comment" = "class=\"comment\" style=\"color: #768390;\""
"tag" = "class=\"tag\" style=\"color: #8ddb8c;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #6cb6ff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e5534b;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #6cb6ff;\""
"constructor" = "class=\"constructor\" style=\"color: #dcbdfb;\""
"variable" = "class=\"variable\" style=\"color: #adbac7;\""
"text" = "class=\"text\" style=\"color: #768390; \""
"module" = "class=\"module\" style=\"color: #f69d50; \""
"constant" = "class=\"constant\" style=\"color: #6cb6ff;\""
"type" = "class=\"type\" style=\"color: #f69d50;\""
"attribute" = "class=\"attribute\" style=\"color: #adbac7;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #6cb6ff;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #6cb6ff;\""
"namespace" = "class=\"namespace\" style=\"color: #f69d50;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #f47067;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
