"constant.numeric" = "class=\"constant numeric\" style=\"color: #ae81ff; \""
"function" = "class=\"function\" style=\"color: #A6E22E; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #F8F8F2; \""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #A6E22E; \""
"markup.quote" = "class=\"markup quote\" style=\"color: ;\""
"keyword" = "class=\"keyword\" style=\"color: #F92672; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #fd971f; \""
"string" = "class=\"string\" style=\"color: #e6db74; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #fd971f; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #f8f8f2; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #F92672; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: ; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #F92672; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ae81ff; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #F92672; \""
"operator" = "class=\"operator\" style=\"color: #f8f8f2; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a6e22e; \""
"special" = "class=\"special\" style=\"color: #F92672; \""
"function.macro" = "class=\"function macro\" style=\"color: #F92672; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: ; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #272822; \""
"punctuation" = "class=\"punctuation\" style=\"color: #f8f8f2; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: ;\""
"comment" = "class=\"comment\" style=\"color: #88846F; \""
"markup.raw" = "class=\"markup raw\" style=\"color: ;\""
"constant.character" = "class=\"constant character\" style=\"color: #e6db74; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #f92672; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #66D9EF; \""
"constructor" = "class=\"constructor\" style=\"color: #A6E22E; \""
"variable" = "class=\"variable\" style=\"color: #F8F8F2; \""
"text" = "class=\"text\" style=\"color: #f8f8f2; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #f8f8f2; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #CE9178; \""
"module" = "class=\"module\" style=\"color: #A6E22E; \""
"constant" = "class=\"constant\" style=\"color: #F8F8F2; \""
"type" = "class=\"type\" style=\"color: #A6E22E; \""
"attribute" = "class=\"attribute\" style=\"color: #A6E22E; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ae81ff; \""
"markup.heading" = "class=\"markup heading\" style=\"color: ;\""
"namespace" = "class=\"namespace\" style=\"color: #A6E22E; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: ; \""
"label" = "class=\"label\" style=\"color: #F92672; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
