"constant.numeric" = "class=\"constant numeric\" style=\"color: #baa0f8;\""
"function" = "class=\"function\" style=\"color: #a2e57b;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #f2fffc;\""
"function.builtin" = "class=\"function builtin\" style=\"color: ; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #a2e57b;\""
"keyword" = "class=\"keyword\" style=\"color: #ff6d7e; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ffb270;\""
"string" = "class=\"string\" style=\"color: #ffed72;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f59762;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ff6d7e;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #ffb270; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f2fffc; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #7cd5f1;\""
"operator" = "class=\"operator\" style=\"color: #ff6d7e; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a2e57b;\""
"special" = "class=\"special\" style=\"color: #f59762;\""
"function.macro" = "class=\"function macro\" style=\"color: #7cd5f1; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #ffb270; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #273136; \""
"punctuation" = "class=\"punctuation\" style=\"color: #798384;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ffed72;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #6b7678; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff6d7e;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #ff6d7e; \""
"constructor" = "class=\"constructor\" style=\"color: #7cd5f1;\""
"variable" = "class=\"variable\" style=\"color: #f2fffc;\""
"text" = "class=\"text\" style=\"color: #f2fffc; \""
"module" = "class=\"module\" style=\"color: #f59762; \""
"constant" = "class=\"constant\" style=\"color: #ffb270;\""
"type" = "class=\"type\" style=\"color: #a2e57b;\""
"attribute" = "class=\"attribute\" style=\"color: #7cd5f1;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ff6d7e;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #a2e57b;\""
"namespace" = "class=\"namespace\" style=\"color: #f2fffc;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ffb270; \""
"label" = "class=\"label\" style=\"color: #f2fffc;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
