"constant.numeric" = "class=\"constant numeric\" style=\"color: #fca369; \""
"function" = "class=\"function\" style=\"color: #ffffff; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #f2777a; \""
"markup.list" = "class=\"markup list\" style=\"color: #76d4d6;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #ffffff; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #92d192;\""
"keyword" = "class=\"keyword\" style=\"color: #ffeea6; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #6ab0f3; \""
"string" = "class=\"string\" style=\"color: #92d192; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f2777a; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #d4d4d4; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #6ab0f3; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #ffeea6; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #76d4d6; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ffeea6; \""
"operator" = "class=\"operator\" style=\"color: #ac8d58; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #92d192; \""
"special" = "class=\"special\" style=\"color: #ffffff; \""
"function.macro" = "class=\"function macro\" style=\"color: #6ab0f3; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #2d2d2d; \""
"punctuation" = "class=\"punctuation\" style=\"color: #d4d4d4; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #fca369;\""
"comment" = "class=\"comment\" style=\"color: #777c85; \""
"tag" = "class=\"tag\" style=\"color: #6ab0f3;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #fca369;\""
"constant.character" = "class=\"constant character\" style=\"color: #92d192; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #f2777a; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #6ab0f3; \""
"constructor" = "class=\"constructor\" style=\"color: #6ab0f3; \""
"variable" = "class=\"variable\" style=\"color: #f2777a; \""
"text" = "class=\"text\" style=\"color: #d4d4d4; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #6ab0f3; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #fca369; \""
"module" = "class=\"module\" style=\"color: #6ab0f3; \""
"constant" = "class=\"constant\" style=\"color: #e1a6f2; \""
"type" = "class=\"type\" style=\"color: #6ab0f3; \""
"attribute" = "class=\"attribute\" style=\"color: #ffd479; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #e1a6f2; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #6ab0f3; \""
"namespace" = "class=\"namespace\" style=\"color: #6ab0f3; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #6ab0f3; \""
"label" = "class=\"label\" style=\"color: #6ab0f3; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
