"constant.numeric" = "class=\"constant numeric\" style=\"color: #b39df3;\""
"function" = "class=\"function\" style=\"color: #9ed072;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #e2e2e3;\""
"markup.list" = "class=\"markup list\" style=\"color: #fc5d7c;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #76cce0;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #7f8490;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #9ed072; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #e2e2e3;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #76cce0; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #e7c664; \""
"keyword" = "class=\"keyword\" style=\"color: #fc5d7c;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #f39660;\""
"string" = "class=\"string\" style=\"color: #e7c664;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #e2e2e3;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #7f8490;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #f39660;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #76cce0; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f39660;\""
"operator" = "class=\"operator\" style=\"color: #f39660; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #9ed072;\""
"special" = "class=\"special\" style=\"color: #f39660;\""
"function.macro" = "class=\"function macro\" style=\"color: #b39df3;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #2c2e34; \""
"punctuation" = "class=\"punctuation\" style=\"color: #7f8490;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #b39df3;\""
"comment" = "class=\"comment\" style=\"color: #7f8490;\""
"tag" = "class=\"tag\" style=\"color: #e7c664;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #9ed072;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #fc5d7c;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #f39660; \""
"constructor" = "class=\"constructor\" style=\"color: #76cce0;\""
"variable" = "class=\"variable\" style=\"color: #e2e2e3;\""
"text" = "class=\"text\" style=\"color: #e2e2e3; \""
"module" = "class=\"module\" style=\"color: #76cce0; \""
"constant" = "class=\"constant\" style=\"color: #b39df3;\""
"type" = "class=\"type\" style=\"color: #76cce0;\""
"attribute" = "class=\"attribute\" style=\"color: #b39df3;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #e2e2e3; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #fc5d7c; \""
"namespace" = "class=\"namespace\" style=\"color: #76cce0;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #7f8490;\""
"label" = "class=\"label\" style=\"color: #f39660;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
