"name" = "catppuccin_mocha"
[base]
"normal" = { bg = "#1e1e2e", fg = "#cdd6f4" }
"cursorline" = { bg = "#2a2b3c" }
"cursorlinenr" = { fg = "#b4befe" }
"linenr" = { fg = "#45475a" }
[treesitter]
"variable" = { fg = "#cdd6f4" }
"variable.builtin" = { fg = "#f38ba8" }
"variable.parameter" = { fg = "#eba0ac" }
"variable.parameter.builtin" = { fg = "#f5c2e7" }
"variable.member" = { fg = "#b4befe" }
"constant" = { fg = "#fab387" }
"constant.builtin" = { fg = "#fab387" }
"constant.macro" = { fg = "#cba6f7" }
"module" = { fg = "#b4befe", italic = true }
"module.builtin" = { fg = "#f5c2e7" }
"label" = { fg = "#74c7ec" }
"string" = { fg = "#a6e3a1" }
"string.documentation" = { fg = "#94e2d5" }
"string.regexp" = { fg = "#fab387" }
"string.escape" = { fg = "#f5c2e7" }
"string.special" = { fg = "#f5c2e7" }
"string.special.symbol" = { fg = "#f2cdcd" }
"string.special.url" = { fg = "#f5e0dc", underline = true, italic = true }
"string.special.path" = { fg = "#f5c2e7" }
"character" = { fg = "#94e2d5" }
"character.special" = { fg = "#f5c2e7" }
"boolean" = { fg = "#fab387" }
"number" = { fg = "#fab387" }
"number.float" = { fg = "#fab387" }
"type" = { fg = "#f9e2af" }
"type.builtin" = { fg = "#f9e2af" }
"type.definition" = { fg = "#f9e2af" }
"attribute" = { fg = "#fab387" }
"attribute.builtin" = { fg = "#f5c2e7" }
"property" = { fg = "#b4befe" }
"function" = { fg = "#89b4fa" }
"function.builtin" = { fg = "#fab387" }
"function.call" = { fg = "#89b4fa" }
"function.macro" = { fg = "#94e2d5" }
"function.method" = { fg = "#89b4fa" }
"function.method.call" = { fg = "#89b4fa" }
"constructor" = { fg = "#74c7ec" }
"operator" = { fg = "#89dceb" }
"keyword" = { fg = "#cba6f7" }
"keyword.coroutine" = { fg = "#cba6f7" }
"keyword.function" = { fg = "#cba6f7" }
"keyword.operator" = { fg = "#89dceb" }
"keyword.import" = { fg = "#cba6f7" }
"keyword.type" = { fg = "#cba6f7" }
"keyword.modifier" = { fg = "#cba6f7" }
"keyword.repeat" = { fg = "#cba6f7" }
"keyword.return" = { fg = "#cba6f7" }
"keyword.debug" = { fg = "#cba6f7" }
"keyword.exception" = { fg = "#cba6f7" }
"keyword.conditional" = { fg = "#cba6f7", italic = true }
"keyword.conditional.ternary" = { fg = "#89dceb" }
"keyword.directive" = { fg = "#f5c2e7" }
"keyword.directive.define" = { fg = "#f5c2e7" }
"punctuation.delimiter" = { fg = "#9399b2" }
"punctuation.bracket" = { fg = "#9399b2" }
"punctuation.special" = { fg = "#f5c2e7" }
"comment" = { fg = "#6c7086", italic = true }
"comment.documentation" = { fg = "#6c7086", italic = true }
"comment.error" = { bg = "#f38ba8", fg = "#1e1e2e" }
"comment.warning" = { bg = "#f9e2af", fg = "#1e1e2e" }
"comment.todo" = { bg = "#f2cdcd", fg = "#1e1e2e" }
"comment.note" = { bg = "#89b4fa", fg = "#1e1e2e" }
"markup.strong" = { fg = "#eba0ac", bold = true }
"markup.italic" = { fg = "#eba0ac", italic = true }
"markup.strikethrough" = { fg = "#cdd6f4" }
"markup.underline" = { underline = true }
"markup.heading" = { fg = "#89b4fa", bold = true }
"markup.heading.1" = { fg = "#89b4fa", bold = true }
"markup.heading.2" = { fg = "#89b4fa", bold = true }
"markup.heading.3" = { fg = "#89b4fa", bold = true }
"markup.heading.4" = { fg = "#89b4fa", bold = true }
"markup.heading.5" = { fg = "#89b4fa", bold = true }
"markup.heading.6" = { fg = "#89b4fa", bold = true }
"markup.quote" = { fg = "#eba0ac", bold = true }
"markup.math" = { fg = "#89b4fa" }
"markup.link" = { fg = "#b4befe", bold = true }
"markup.link.label" = { fg = "#74c7ec" }
"markup.link.url" = { fg = "#f5e0dc", underline = true, italic = true }
"markup.raw" = { fg = "#94e2d5" }
"markup.raw.block" = { fg = "#94e2d5" }
"markup.list" = { fg = "#f5c2e7" }
"markup.list.checked" = { fg = "#a6e3a1" }
"markup.list.unchecked" = { fg = "#7f849c" }
"diff.plus" = { fg = "#a6e3a1" }
"diff.minus" = { fg = "#f38ba8" }
"diff.delta" = { fg = "#89b4fa" }
"tag" = { fg = "#cba6f7" }
"tag.builtin" = { fg = "#f5c2e7" }
"tag.attribute" = { fg = "#94e2d5", italic = true }
"tag.delimiter" = { fg = "#89dceb" }