"name" = "dracula"
[base]
"normal" = { bg = "#282a36", fg = "#f8f8f2" }
"cursorline" = { bg = "#44475a" }
"cursorlinenr" = { fg = "#f8f8f2", bold = true }
"linenr" = { fg = "#6272a4" }
[treesitter]
"variable" = { fg = "#f8f8f2" }
"variable.builtin" = { fg = "#bd93f9" }
"variable.parameter" = { fg = "#ffb86c" }
"variable.parameter.builtin" = { fg = "#50fa7b", italic = true }
"variable.member" = { fg = "#ffb86c" }
"constant" = { fg = "#bd93f9" }
"constant.builtin" = { fg = "#bd93f9" }
"constant.macro" = { fg = "#8be9fd" }
"module" = { fg = "#ffb86c" }
"module.builtin" = { fg = "#50fa7b", italic = true }
"label" = { fg = "#8be9fd" }
"string" = { fg = "#f1fa8c" }
"string.documentation" = { fg = "#f1fa8c" }
"string.regexp" = { fg = "#ff5555" }
"string.escape" = { fg = "#8be9fd" }
"string.special" = { fg = "#50fa7b", italic = true }
"string.special.symbol" = { fg = "#bd93f9" }
"string.special.url" = { fg = "#8be9fd", underline = true }
"string.special.path" = { fg = "#50fa7b", italic = true }
"character" = { fg = "#50fa7b" }
"character.special" = { fg = "#50fa7b", italic = true }
"boolean" = { fg = "#bd93f9" }
"number" = { fg = "#bd93f9" }
"number.float" = { fg = "#50fa7b" }
"type" = { fg = "#a4ffff" }
"type.builtin" = { fg = "#8be9fd", italic = true }
"type.definition" = { fg = "#a4ffff" }
"attribute" = { fg = "#8be9fd" }
"attribute.builtin" = { fg = "#50fa7b", italic = true }
"property" = { fg = "#bd93f9" }
"function" = { fg = "#50fa7b" }
"function.builtin" = { fg = "#8be9fd" }
"function.call" = { fg = "#50fa7b" }
"function.macro" = { fg = "#50fa7b" }
"function.method" = { fg = "#50fa7b" }
"function.method.call" = { fg = "#50fa7b" }
"constructor" = { fg = "#8be9fd" }
"operator" = { fg = "#ff79c6" }
"keyword" = { fg = "#ff79c6" }
"keyword.coroutine" = { fg = "#ff79c6" }
"keyword.function" = { fg = "#8be9fd" }
"keyword.operator" = { fg = "#ff79c6" }
"keyword.import" = { fg = "#ff79c6" }
"keyword.type" = { fg = "#ff79c6" }
"keyword.modifier" = { fg = "#ff79c6" }
"keyword.repeat" = { fg = "#ff79c6" }
"keyword.return" = { fg = "#ff79c6" }
"keyword.debug" = { fg = "#ff79c6" }
"keyword.exception" = { fg = "#bd93f9" }
"keyword.conditional" = { fg = "#ff79c6" }
"keyword.conditional.ternary" = { fg = "#ff79c6" }
"keyword.directive" = { fg = "#ff79c6" }
"keyword.directive.define" = { fg = "#ff79c6" }
"punctuation.delimiter" = { fg = "#f8f8f2" }
"punctuation.bracket" = { fg = "#f8f8f2" }
"punctuation.special" = { fg = "#50fa7b", italic = true }
"comment" = { fg = "#6272a4" }
"comment.documentation" = { fg = "#6272a4" }
"comment.error" = { fg = "#ff5555" }
"comment.warning" = { fg = "#f1fa8c" }
"comment.todo" = { fg = "#bd93f9", bold = true, italic = true }
"comment.note" = { fg = "#8be9fd" }
"markup.strong" = { fg = "#ffb86c", bold = true }
"markup.italic" = { italic = true }
"markup.strikethrough" = {  }
"markup.underline" = { fg = "#ffb86c" }
"markup.heading" = { fg = "#ff79c6", bold = true }
"markup.heading.1" = { fg = "#ff79c6", bold = true }
"markup.heading.2" = { fg = "#ff79c6", bold = true }
"markup.heading.3" = { fg = "#ff79c6", bold = true }
"markup.heading.4" = { fg = "#ff79c6", bold = true }
"markup.heading.5" = { fg = "#ff79c6", bold = true }
"markup.heading.6" = { fg = "#ff79c6", bold = true }
"markup.quote" = { fg = "#ffb86c" }
"markup.math" = { fg = "#ffb86c" }
"markup.link" = { fg = "#ffb86c", bold = true }
"markup.link.label" = { fg = "#ffb86c", bold = true }
"markup.link.url" = { fg = "#f1fa8c", italic = true }
"markup.raw" = { fg = "#f1fa8c" }
"markup.raw.block" = { fg = "#f1fa8c" }
"markup.list" = { fg = "#8be9fd" }
"markup.list.checked" = { fg = "#8be9fd" }
"markup.list.unchecked" = { fg = "#8be9fd" }
"diff.plus" = { fg = "#b3f6c0" }
"diff.minus" = { fg = "#ffc0b9" }
"diff.delta" = { fg = "#8cf8f7" }
"tag" = { fg = "#8be9fd" }
"tag.builtin" = { fg = "#50fa7b", italic = true }
"tag.attribute" = { fg = "#50fa7b" }
"tag.delimiter" = { fg = "#8be9fd" }