"name" = "tokyonight"
[base]
"normal" = { bg = "#222436", fg = "#c8d3f5" }
"cursorline" = { bg = "#2f334d" }
"cursorlinenr" = { fg = "#ff966c", bold = true }
"linenr" = { fg = "#3b4261" }
[treesitter]
"variable" = { fg = "#c8d3f5" }
"variable.builtin" = { fg = "#ff757f" }
"variable.parameter" = { fg = "#ffc777" }
"variable.parameter.builtin" = { fg = "#f4c990" }
"variable.member" = { fg = "#4fd6be" }
"constant" = { fg = "#ff966c" }
"constant.builtin" = { fg = "#65bcff" }
"constant.macro" = { fg = "#86e1fc" }
"module" = { fg = "#86e1fc" }
"module.builtin" = { fg = "#ff757f" }
"label" = { fg = "#82aaff" }
"string" = { fg = "#c3e88d" }
"string.documentation" = { fg = "#ffc777" }
"string.regexp" = { fg = "#b4f9f8" }
"string.escape" = { fg = "#c099ff" }
"string.special" = { fg = "#65bcff" }
"string.special.symbol" = { fg = "#65bcff" }
"string.special.url" = { underline = true }
"string.special.path" = { fg = "#65bcff" }
"character" = { fg = "#c3e88d" }
"character.special" = { fg = "#65bcff" }
"boolean" = { fg = "#ff966c" }
"number" = { fg = "#ff966c" }
"number.float" = { fg = "#ff966c" }
"type" = { fg = "#65bcff" }
"type.builtin" = { fg = "#589ed7" }
"type.definition" = { fg = "#65bcff" }
"attribute" = { fg = "#86e1fc" }
"attribute.builtin" = { fg = "#65bcff" }
"property" = { fg = "#4fd6be" }
"function" = { fg = "#82aaff" }
"function.builtin" = { fg = "#65bcff" }
"function.call" = { fg = "#82aaff" }
"function.macro" = { fg = "#86e1fc" }
"function.method" = { fg = "#82aaff" }
"function.method.call" = { fg = "#82aaff" }
"constructor" = { fg = "#c099ff" }
"operator" = { fg = "#89ddff" }
"keyword" = { fg = "#fca7ea", italic = true }
"keyword.coroutine" = { fg = "#fca7ea", italic = true }
"keyword.function" = { fg = "#c099ff" }
"keyword.operator" = { fg = "#89ddff" }
"keyword.import" = { fg = "#86e1fc" }
"keyword.type" = { fg = "#fca7ea", italic = true }
"keyword.modifier" = { fg = "#fca7ea", italic = true }
"keyword.repeat" = { fg = "#c099ff" }
"keyword.return" = { fg = "#fca7ea", italic = true }
"keyword.debug" = { fg = "#ff966c" }
"keyword.exception" = { fg = "#c099ff" }
"keyword.conditional" = { fg = "#c099ff" }
"keyword.conditional.ternary" = { fg = "#c099ff" }
"keyword.directive" = { fg = "#86e1fc" }
"keyword.directive.define" = { fg = "#86e1fc" }
"punctuation.delimiter" = { fg = "#89ddff" }
"punctuation.bracket" = { fg = "#828bb8" }
"punctuation.special" = { fg = "#89ddff" }
"comment" = { fg = "#636da6", italic = true }
"comment.documentation" = { fg = "#636da6", italic = true }
"comment.error" = { fg = "#c53b53" }
"comment.warning" = { fg = "#ffc777" }
"comment.todo" = { fg = "#82aaff" }
"comment.note" = { fg = "#4fd6be" }
"markup.strong" = { bold = true }
"markup.italic" = { italic = true }
"markup.strikethrough" = {  }
"markup.underline" = { underline = true }
"markup.heading" = { fg = "#82aaff", bold = true }
"markup.heading.1" = { fg = "#82aaff", bold = true }
"markup.heading.2" = { fg = "#82aaff", bold = true }
"markup.heading.3" = { fg = "#82aaff", bold = true }
"markup.heading.4" = { fg = "#82aaff", bold = true }
"markup.heading.5" = { fg = "#82aaff", bold = true }
"markup.heading.6" = { fg = "#82aaff", bold = true }
"markup.quote" = {  }
"markup.math" = { fg = "#65bcff" }
"markup.link" = { fg = "#4fd6be" }
"markup.link.label" = { fg = "#65bcff" }
"markup.link.url" = { underline = true }
"markup.raw" = { fg = "#c3e88d" }
"markup.raw.block" = { fg = "#c3e88d" }
"markup.list" = { fg = "#89ddff" }
"markup.list.checked" = { fg = "#4fd6be" }
"markup.list.unchecked" = { fg = "#82aaff" }
"diff.plus" = { bg = "#273849" }
"diff.minus" = { bg = "#3a273a" }
"diff.delta" = { bg = "#252a3f" }
"tag" = { fg = "#c099ff" }
"tag.builtin" = { fg = "#65bcff" }
"tag.attribute" = { fg = "#4fd6be" }
"tag.delimiter" = { fg = "#65bcff" }