"name" = "tokyonight_day"
[base]
"normal" = { bg = "#e1e2e7", fg = "#3760bf" }
"cursorline" = { bg = "#c4c8da" }
"cursorlinenr" = { fg = "#b15c00", bold = true }
"linenr" = { fg = "#a8aecb" }
[treesitter]
"variable" = { fg = "#3760bf" }
"variable.builtin" = { fg = "#f52a65" }
"variable.parameter" = { fg = "#8c6c3e" }
"variable.parameter.builtin" = { fg = "#7b6a58" }
"variable.member" = { fg = "#387068" }
"constant" = { fg = "#b15c00" }
"constant.builtin" = { fg = "#188092" }
"constant.macro" = { fg = "#007197" }
"module" = { fg = "#007197" }
"module.builtin" = { fg = "#f52a65" }
"label" = { fg = "#2e7de9" }
"string" = { fg = "#587539" }
"string.documentation" = { fg = "#8c6c3e" }
"string.regexp" = { fg = "#2e5857" }
"string.escape" = { fg = "#9854f1" }
"string.special" = { fg = "#188092" }
"string.special.symbol" = { fg = "#188092" }
"string.special.url" = { underline = true }
"string.special.path" = { fg = "#188092" }
"character" = { fg = "#587539" }
"character.special" = { fg = "#188092" }
"boolean" = { fg = "#b15c00" }
"number" = { fg = "#b15c00" }
"number.float" = { fg = "#b15c00" }
"type" = { fg = "#188092" }
"type.builtin" = { fg = "#4094a3" }
"type.definition" = { fg = "#188092" }
"attribute" = { fg = "#007197" }
"attribute.builtin" = { fg = "#188092" }
"property" = { fg = "#387068" }
"function" = { fg = "#2e7de9" }
"function.builtin" = { fg = "#188092" }
"function.call" = { fg = "#2e7de9" }
"function.macro" = { fg = "#007197" }
"function.method" = { fg = "#2e7de9" }
"function.method.call" = { fg = "#2e7de9" }
"constructor" = { fg = "#9854f1" }
"operator" = { fg = "#006a83" }
"keyword" = { fg = "#7847bd", italic = true }
"keyword.coroutine" = { fg = "#7847bd", italic = true }
"keyword.function" = { fg = "#9854f1" }
"keyword.operator" = { fg = "#006a83" }
"keyword.import" = { fg = "#007197" }
"keyword.type" = { fg = "#7847bd", italic = true }
"keyword.modifier" = { fg = "#7847bd", italic = true }
"keyword.repeat" = { fg = "#9854f1" }
"keyword.return" = { fg = "#7847bd", italic = true }
"keyword.debug" = { fg = "#b15c00" }
"keyword.exception" = { fg = "#9854f1" }
"keyword.conditional" = { fg = "#9854f1" }
"keyword.conditional.ternary" = { fg = "#9854f1" }
"keyword.directive" = { fg = "#007197" }
"keyword.directive.define" = { fg = "#007197" }
"punctuation.delimiter" = { fg = "#006a83" }
"punctuation.bracket" = { fg = "#6172b0" }
"punctuation.special" = { fg = "#006a83" }
"comment" = { fg = "#848cb5", italic = true }
"comment.documentation" = { fg = "#848cb5", italic = true }
"comment.error" = { fg = "#c64343" }
"comment.warning" = { fg = "#8c6c3e" }
"comment.todo" = { fg = "#2e7de9" }
"comment.note" = { fg = "#118c74" }
"markup.strong" = { bold = true }
"markup.italic" = { italic = true }
"markup.strikethrough" = {  }
"markup.underline" = { underline = true }
"markup.heading" = { fg = "#2e7de9", bold = true }
"markup.heading.1" = { fg = "#2e7de9", bold = true }
"markup.heading.2" = { fg = "#2e7de9", bold = true }
"markup.heading.3" = { fg = "#2e7de9", bold = true }
"markup.heading.4" = { fg = "#2e7de9", bold = true }
"markup.heading.5" = { fg = "#2e7de9", bold = true }
"markup.heading.6" = { fg = "#2e7de9", bold = true }
"markup.quote" = {  }
"markup.math" = { fg = "#188092" }
"markup.link" = { fg = "#118c74" }
"markup.link.label" = { fg = "#188092" }
"markup.link.url" = { underline = true }
"markup.raw" = { fg = "#587539" }
"markup.raw.block" = { fg = "#587539" }
"markup.list" = { fg = "#006a83" }
"markup.list.checked" = { fg = "#387068" }
"markup.list.unchecked" = { fg = "#2e7de9" }
"diff.plus" = { bg = "#c8d6dc" }
"diff.minus" = { bg = "#ddcace" }
"diff.delta" = { bg = "#d5d9e4" }
"tag" = { fg = "#9854f1" }
"tag.builtin" = { fg = "#188092" }
"tag.attribute" = { fg = "#387068" }
"tag.delimiter" = { fg = "#188092" }