"constant.numeric" = "class=\"constant numeric\" style=\"font-weight: bold; color: #33B2A4; \""
"function" = "class=\"function\" style=\"color: #62A0EA;\""
"keyword.function" = "class=\"keyword function\" style=\"color: #FFA348;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #5BC8AF;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #C061CB;\""
"markup.list" = "class=\"markup list\" style=\"font-weight: bold; color: #FFA348; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #62A0EA;\""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #F6F5F4; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #DEDDDA;\""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #FFA348; \""
"function.special" = "class=\"function special\" style=\"font-weight: bold; color: #62A0EA; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #FF7800;\""
"string" = "class=\"string\" style=\"color: #5BC8AF;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #FFA348;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #DEDDDA;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #FFA348;\""
"keyword.control" = "class=\"keyword control\" style=\"font-weight: bold; color: #FFA348; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #7D8AC7;\""
"keyword.directive" = "class=\"keyword directive\" style=\"font-weight: bold; color: #FFA348; \""
"operator" = "class=\"operator\" style=\"color: #C061CB; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #33B2A4;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #62A0EA; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #DEDDDA; \""
"background" = "class=\"background\" style=\"background-color: #1D1D1D; \""
"punctuation" = "class=\"punctuation\" style=\"color: #DEDDDA;\""
"comment" = "class=\"comment\" style=\"color: #5E5C64;\""
"tag" = "class=\"tag\" style=\"color: #5BC8AF;\""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #FFA348;\""
"constant.character" = "class=\"constant character\" style=\"color: #33B2A4;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #F66151;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #5BC8AF;\""
"constructor" = "class=\"constructor\" style=\"color: #62A0EA;\""
"variable" = "class=\"variable\" style=\"color: #DEDDDA;\""
"keyword.storage" = "class=\"keyword storage\" style=\"font-weight: bold; color: #FFA348; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #C061CB;\""
"module" = "class=\"module\" style=\"color: #FFA348; \""
"markup.link" = "class=\"markup link\" style=\"text-decoration: underline; color: #3584E4; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #E01B24;\""
"constant" = "class=\"constant\" style=\"color: #7D8AC7;\""
"string.special" = "class=\"string special\" style=\"color: #62A0EA;\""
"type" = "class=\"type\" style=\"color: #5BC8AF;\""
"variable.other" = "class=\"variable other\" style=\"color: #5BC8AF;\""
"attribute" = "class=\"attribute\" style=\"color: #E66100;\""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #7D8AC7; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #5BC8AF; \""
"markup" = "class=\"markup\" style=\"color: #DEDDDA;\""
"namespace" = "class=\"namespace\" style=\"color: #FFA348;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #DEDDDA; \""
"label" = "class=\"label\" style=\"color: #C061CB;\""
