"attribute" = "style=\"color: #E66100;\""
"comment" = "style=\"color: #5E5C64;\""
"constant" = "style=\"color: #7D8AC7;\""
"constant.builtin" = "style=\"font-weight: bold; color: #7D8AC7; \""
"constant.character" = "style=\"color: #33B2A4;\""
"constant.character.escape" = "style=\"color: #7D8AC7;\""
"constant.numeric" = "style=\"font-weight: bold; color: #33B2A4; \""
"constructor" = "style=\"color: #62A0EA;\""
"diff.delta" = "style=\"color: #FF7800;\""
"diff.delta.moved" = "style=\"color: #FFA348;\""
"diff.minus" = "style=\"color: #F66151;\""
"diff.plus" = "style=\"color: #33B2A4;\""
"function" = "style=\"color: #62A0EA;\""
"function.builtin" = "style=\"color: #62A0EA;\""
"function.macro" = "style=\"font-weight: bold; color: #62A0EA; \""
"function.special" = "style=\"font-weight: bold; color: #62A0EA; \""
"keyword" = "style=\"font-weight: bold; color: #FFA348; \""
"keyword.control" = "style=\"font-weight: bold; color: #FFA348; \""
"keyword.directive" = "style=\"font-weight: bold; color: #FFA348; \""
"keyword.function" = "style=\"color: #FFA348;\""
"keyword.operator" = "style=\"color: #C061CB;\""
"keyword.storage" = "style=\"font-weight: bold; color: #FFA348; \""
"label" = "style=\"color: #C061CB;\""
"markup" = "style=\"color: #DEDDDA;\""
"markup.bold" = "style=\"font-weight: bold; color: #DEDDDA; \""
"markup.heading" = "style=\"font-weight: bold; color: #5BC8AF; \""
"markup.italic" = "style=\"text-decoration: underline; color: #DEDDDA; \""
"markup.link" = "style=\"color: #3584E4; \""
"markup.list" = "style=\"font-weight: bold; color: #FFA348; \""
"markup.quote" = "style=\"text-decoration: underline; color: #F6F5F4; \""
"namespace" = "style=\"color: #FFA348;\""
"operator" = "style=\"color: #C061CB;\""
"punctuation" = "style=\"color: #DEDDDA;\""
"punctuation.bracket" = "style=\"color: #DEDDDA;\""
"punctuation.delimiter" = "style=\"color: #DEDDDA;\""
"punctuation.special" = "style=\"color: #E01B24;\""
"string" = "style=\"color: #5BC8AF;\""
"string.regexp" = "style=\"color: #C061CB;\""
"string.special" = "style=\"color: #62A0EA;\""
"tag" = "style=\"color: #5BC8AF;\""
"type" = "style=\"color: #5BC8AF;\""
"type.builtin" = "style=\"color: #5BC8AF;\""
"variable" = "style=\"color: #DEDDDA;\""
"variable.builtin" = "style=\"color: #FFA348;\""
"variable.other" = "style=\"color: #5BC8AF;\""
"variable.other.member" = "style=\"color: #5BC8AF;\""
"variable.parameter" = "style=\"color: #FFA348;\""
