"constant.numeric" = "class=\"constant numeric\" style=\"color: #e9c46a;\""
"function" = "class=\"function\" style=\"font-style: italic; color: #e5c890; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #c1c0d4;\""
"markup.list" = "class=\"markup list\" style=\"color: #9998a8;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #9898a6;\""
"keyword" = "class=\"keyword\" style=\"color: #8eb6f5;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #b9aeda;\""
"string" = "class=\"string\" style=\"color: #9898a6;\""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #c1c0d4; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #9998a8;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #b9aeda;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #90b99f; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ea83a5;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #e29eca;\""
"operator" = "class=\"operator\" style=\"color: #8eb6f5; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #9dc6ac;\""
"special" = "class=\"special\" style=\"color: #e5c890;\""
"function.macro" = "class=\"function macro\" style=\"color: #f591b2;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #0F1014; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9998a8;\""
"markup.link.text" = "class=\"markup link text\" style=\"font-style: italic; color: #aca1cf; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #808080; \""
"tag" = "class=\"tag\" style=\"color: #9898a6;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #e5c890;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e78284;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #e29eca;\""
"constructor" = "class=\"constructor\" style=\"color: #e5c890;\""
"variable" = "class=\"variable\" style=\"color: #c9c7cd; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #e29eca;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #90b99f;\""
"module" = "class=\"module\" style=\"color: #c58fff; \""
"constant" = "class=\"constant\" style=\"color: #8eb6f5;\""
"string.special" = "class=\"string special\" style=\"color: #e5c890;\""
"type" = "class=\"type\" style=\"color: #b9aeda;\""
"attribute" = "class=\"attribute\" style=\"font-style: italic; color: #aca1cf; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #e5c890;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #b9aeda; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-style: italic; color: #a8a29e; \""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #c58fff; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #9998a8; \""
"label" = "class=\"label\" style=\"color: #e5c890;\""
