"attribute" = "style=\"text-decoration: underline; color: #aca1cf; \""
"comment" = "style=\"text-decoration: underline; color: #808080; \""
"constant" = "style=\"color: #8eb6f5;\""
"constant.builtin" = "style=\"color: #e5c890;\""
"constant.character.escape" = "style=\"color: #ea83a5;\""
"constant.numeric" = "style=\"color: #e9c46a;\""
"constructor" = "style=\"color: #e5c890;\""
"diff.delta" = "style=\"color: #b9aeda;\""
"diff.minus" = "style=\"color: #e78284;\""
"diff.plus" = "style=\"color: #9dc6ac;\""
"function" = "style=\"text-decoration: underline; color: #e5c890; \""
"function.builtin" = "style=\"color: #9898a6;\""
"function.macro" = "style=\"color: #f591b2;\""
"keyword" = "style=\"color: #8eb6f5;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #a8a29e; \""
"keyword.directive" = "style=\"color: #e29eca;\""
"label" = "style=\"color: #e5c890;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #b9aeda; \""
"markup.heading.marker" = "style=\"color: #9998a8; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"text-decoration: underline; color: #aca1cf; \""
"markup.link.url" = "style=\"color: #90b99f; \""
"markup.list" = "style=\"color: #9998a8;\""
"markup.raw" = "style=\"color: #e5c890;\""
"namespace" = "style=\"text-decoration: underline; color: #c58fff; \""
"operator" = "style=\"color: #8eb6f5;\""
"punctuation" = "style=\"color: #9998a8;\""
"punctuation.delimiter" = "style=\"color: #9998a8;\""
"special" = "style=\"color: #e5c890;\""
"string" = "style=\"color: #9898a6;\""
"string.regexp" = "style=\"color: #90b99f;\""
"string.special" = "style=\"color: #e5c890;\""
"tag" = "style=\"color: #9898a6;\""
"type" = "style=\"color: #b9aeda;\""
"type.builtin" = "style=\"color: #e29eca;\""
"type.enum.variant" = "style=\"color: #e29eca;\""
"variable" = "style=\"color: #c9c7cd; \""
"variable.builtin" = "style=\"color: #b9aeda;\""
"variable.other.member" = "style=\"color: #c1c0d4;\""
"variable.parameter" = "style=\"text-decoration: underline; color: #c1c0d4; \""
