"attribute" = "class=\"attribute\" style=\"color: #86c1b9;\""
"background" = "class=\"background\" style=\"background-color: #090909; \""
"comment" = "class=\"comment\" style=\"color: #626C66; \""
"constant" = "class=\"constant\" style=\"color: #F3F2CC;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #86c1b9;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #86c1b9;\""
"constructor" = "class=\"constructor\" style=\"color: #FAD566;\""
"debug" = "class=\"debug\" style=\"color: #ffff9f;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #626C66;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #F05E48;\""
"diff.plus" = "class=\"diff plus\" style=\"color: #99be70;\""
"function" = "class=\"function\" style=\"color: #FAD566;\""
"keyword" = "class=\"keyword\" style=\"color: #F05E48;\""
"label" = "class=\"label\" style=\"color: #F05E48;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #FAD566;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #F3F2CC;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #72a59e;\""
"markup.list" = "class=\"markup list\" style=\"color: #F3F2CC;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #cfba8b;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #99be70;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #F3F2CC; \""
"namespace" = "class=\"namespace\" style=\"color: #F3F2CC;\""
"operator" = "class=\"operator\" style=\"color: #F3F2CC; \""
"special" = "class=\"special\" style=\"color: #FAD566;\""
"string" = "class=\"string\" style=\"color: #99be70;\""
"type" = "class=\"type\" style=\"font-style: italic; color: #F3F2CC; \""
"variable" = "class=\"variable\" style=\"color: #F3F2CC;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #cfba8b;\""
