"background" = "style=\"background-color: #090909; \""
"attribute" = "style=\"color: #86c1b9;\""
"comment" = "style=\"color: #626C66; \""
"constant" = "style=\"color: #F3F2CC;\""
"constant.character.escape" = "style=\"color: #86c1b9;\""
"constant.numeric" = "style=\"color: #86c1b9;\""
"constructor" = "style=\"color: #FAD566;\""
"debug" = "style=\"color: #ffff9f;\""
"diff.delta" = "style=\"color: #626C66;\""
"diff.minus" = "style=\"color: #F05E48;\""
"diff.plus" = "style=\"color: #99be70;\""
"function" = "style=\"color: #FAD566;\""
"keyword" = "style=\"color: #F05E48;\""
"label" = "style=\"color: #F05E48;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #FAD566;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #F3F2CC;\""
"markup.link.url" = "style=\"color: #72a59e;\""
"markup.list" = "style=\"color: #F3F2CC;\""
"markup.quote" = "style=\"color: #cfba8b;\""
"markup.raw" = "style=\"color: #99be70;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #F3F2CC;\""
"operator" = "style=\"color: #F3F2CC;\""
"special" = "style=\"color: #FAD566;\""
"string" = "style=\"color: #99be70;\""
"type" = "style=\"text-decoration: underline; color: #F3F2CC; \""
"variable" = "style=\"color: #F3F2CC;\""
"variable.other.member" = "style=\"color: #cfba8b;\""
