"comment" = "style=\"text-decoration: underline; color: ; \""
"constant" = "style=\"color: ;\""
"constructor" = "style=\"color: ;\""
"diff.delta" = "style=\"color: ;\""
"diff.minus" = "style=\"color: #DD3E25;\""
"diff.plus" = "style=\"color: ;\""
"function" = "style=\"color: ;\""
"keyword" = "style=\"color: ;\""
"keyword.control" = "style=\"color: ;\""
"keyword.directive" = "style=\"color: ;\""
"keyword.storage" = "style=\"color: ;\""
"keyword.storage.modifier" = "style=\"color: ;\""
"label" = "style=\"color: ;\""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.label" = "style=\"color: ;\""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ;\""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"color: ;\""
"markup.raw.block" = "style=\"background-color: #0D0D0D; \""
"markup.raw.inline" = "style=\"background-color: #0D0D0D; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: ;\""
"operator" = "style=\"color: ;\""
"punctuation" = "style=\"color: ;\""
"special" = "style=\"color: ;\""
"string" = "style=\"color: ;\""
"string.regexp" = "style=\"color: ;\""
"string.special" = "style=\"color: ;\""
"tag" = "style=\"color: ;\""
"type" = "style=\"color: ;\""
"type.builtin" = "style=\"text-decoration: underline; color: ; \""
"variable" = "style=\"color: #dedede;\""
