"function" = "class=\"function\" style=\"color: #ffaa33;\""
"markup.list" = "class=\"markup list\" style=\"color: #ffaa33;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #86b300;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #ffaa33;\""
"keyword" = "class=\"keyword\" style=\"color: #fa8d3e;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #ffaa33;\""
"string" = "class=\"string\" style=\"color: #86b300;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #fa8d3e;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #399ee6; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #ffaa33;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ffaa33;\""
"operator" = "class=\"operator\" style=\"color: #fa8d3e; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #86b300;\""
"special" = "class=\"special\" style=\"color: #fa8d3e;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #fa8d3e; \""
"background" = "class=\"background\" style=\"background-color: #fafafa; \""
"punctuation" = "class=\"punctuation\" style=\"color: #5c6166;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ffaa33;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #828c9a; \""
"tag" = "class=\"tag\" style=\"color: #399ee6;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f07171;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #399ee6;\""
"constructor" = "class=\"constructor\" style=\"color: #86b300;\""
"variable" = "class=\"variable\" style=\"color: #5c6166;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #fa8d3e;\""
"module" = "class=\"module\" style=\"color: #399ee6; \""
"constant" = "class=\"constant\" style=\"color: #a37acc;\""
"string.special" = "class=\"string special\" style=\"color: #ffaa33;\""
"type" = "class=\"type\" style=\"color: #399ee6;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #fa8d3e;\""
"namespace" = "class=\"namespace\" style=\"color: #399ee6;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #fa8d3e; \""
"label" = "class=\"label\" style=\"color: #fa8d3e;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
