"background" = "style=\"background-color: #fafafa; \""
"comment" = "style=\"text-decoration: underline; color: #828c9a; \""
"constant" = "style=\"color: #a37acc;\""
"constructor" = "style=\"color: #86b300;\""
"diff.delta" = "style=\"color: #ffaa33;\""
"diff.minus" = "style=\"color: #f07171;\""
"diff.plus" = "style=\"color: #86b300;\""
"function" = "style=\"color: #ffaa33;\""
"keyword" = "style=\"color: #fa8d3e;\""
"keyword.control" = "style=\"color: #ffaa33;\""
"keyword.directive" = "style=\"color: #ffaa33;\""
"label" = "style=\"color: #fa8d3e;\""
"markup.bold" = "style=\"font-weight: bold; color: #fa8d3e; \""
"markup.heading" = "style=\"color: #fa8d3e;\""
"markup.italic" = "style=\"text-decoration: underline; color: #fa8d3e; \""
"markup.link.label" = "style=\"color: #86b300;\""
"markup.link.text" = "style=\"color: #ffaa33;\""
"markup.link.url" = "style=\"color: #399ee6; \""
"markup.list" = "style=\"color: #ffaa33;\""
"markup.quote" = "style=\"color: #ffaa33;\""
"markup.raw.block" = "style=\"color: #fa8d3e;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #399ee6;\""
"operator" = "style=\"color: #fa8d3e;\""
"punctuation" = "style=\"color: #5c6166;\""
"special" = "style=\"color: #fa8d3e;\""
"string" = "style=\"color: #86b300;\""
"string.regexp" = "style=\"color: #fa8d3e;\""
"string.special" = "style=\"color: #ffaa33;\""
"tag" = "style=\"color: #399ee6;\""
"type" = "style=\"color: #399ee6;\""
"type.builtin" = "style=\"color: #399ee6;\""
"variable" = "style=\"color: #5c6166;\""
