"function" = "class=\"function\" style=\"color: #ffcc77;\""
"markup.list" = "class=\"markup list\" style=\"color: #ffcc77;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #d5ff80;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #ffcc77;\""
"keyword" = "class=\"keyword\" style=\"color: #ffad66;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #ffcc77;\""
"string" = "class=\"string\" style=\"color: #d5ff80;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #ffad66;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #73d0ff;\""
"keyword.control" = "class=\"keyword control\" style=\"color: #ffcc77;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ffcc77;\""
"operator" = "class=\"operator\" style=\"color: #ffad66; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #d5ff80;\""
"special" = "class=\"special\" style=\"color: #ffad66;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #ffad66; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #1f2430; \""
"punctuation" = "class=\"punctuation\" style=\"color: #cccac2;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ffcc77;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #565b66; \""
"tag" = "class=\"tag\" style=\"color: #73d0ff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f28779;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #73d0ff;\""
"constructor" = "class=\"constructor\" style=\"color: #d5ff80;\""
"variable" = "class=\"variable\" style=\"color: #cccac2;\""
"text" = "class=\"text\" style=\"color: #cccac2; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ffad66;\""
"module" = "class=\"module\" style=\"color: #73d0ff; \""
"constant" = "class=\"constant\" style=\"color: #dfbfff;\""
"string.special" = "class=\"string special\" style=\"color: #ffcc77;\""
"type" = "class=\"type\" style=\"color: #73d0ff;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #ffad66;\""
"namespace" = "class=\"namespace\" style=\"color: #73d0ff;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ffad66; \""
"label" = "class=\"label\" style=\"color: #ffad66;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
