"background" = "style=\"background-color: #0f1419; \""
"comment" = "style=\"text-decoration: underline; color: #5c6773; \""
"constant" = "style=\"color: #d2a6ff;\""
"constructor" = "style=\"color: #aad94c;\""
"diff.delta" = "style=\"color: #e6b450;\""
"diff.minus" = "style=\"color: #f07178;\""
"diff.plus" = "style=\"color: #aad94c;\""
"function" = "style=\"color: #e6b450;\""
"keyword" = "style=\"color: #ff8f40;\""
"keyword.control" = "style=\"color: #e6b450;\""
"keyword.directive" = "style=\"color: #e6b450;\""
"label" = "style=\"color: #ff8f40;\""
"markup.bold" = "style=\"font-weight: bold; color: #ff8f40; \""
"markup.heading" = "style=\"color: #ff8f40;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ff8f40; \""
"markup.link.label" = "style=\"color: #aad94c;\""
"markup.link.text" = "style=\"color: #e6b450;\""
"markup.link.url" = "style=\"color: #59c2ff;\""
"markup.list" = "style=\"color: #e6b450;\""
"markup.quote" = "style=\"color: #e6b450;\""
"markup.raw.block" = "style=\"color: #ff8f40;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #59c2ff;\""
"operator" = "style=\"color: #ff8f40;\""
"punctuation" = "style=\"color: #bfbdb6;\""
"special" = "style=\"color: #ff8f40;\""
"string" = "style=\"color: #aad94c;\""
"string.regexp" = "style=\"color: #ff8f40;\""
"string.special" = "style=\"color: #e6b450;\""
"tag" = "style=\"color: #59c2ff;\""
"type" = "style=\"color: #59c2ff;\""
"type.builtin" = "style=\"color: #59c2ff;\""
"variable" = "style=\"color: #bfbdb6;\""
