"background" = "style=\"background-color: #1f2430; \""
"comment" = "style=\"text-decoration: underline; color: #565b66; \""
"constant" = "style=\"color: #dfbfff;\""
"constructor" = "style=\"color: #d5ff80;\""
"diff.delta" = "style=\"color: #ffcc77;\""
"diff.minus" = "style=\"color: #f28779;\""
"diff.plus" = "style=\"color: #d5ff80;\""
"function" = "style=\"color: #ffcc77;\""
"keyword" = "style=\"color: #ffad66;\""
"keyword.control" = "style=\"color: #ffcc77;\""
"keyword.directive" = "style=\"color: #ffcc77;\""
"label" = "style=\"color: #ffad66;\""
"markup.bold" = "style=\"font-weight: bold; color: #ffad66; \""
"markup.heading" = "style=\"color: #ffad66;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ffad66; \""
"markup.link.label" = "style=\"color: #d5ff80;\""
"markup.link.text" = "style=\"color: #ffcc77;\""
"markup.link.url" = "style=\"color: #73d0ff;\""
"markup.list" = "style=\"color: #ffcc77;\""
"markup.quote" = "style=\"color: #ffcc77;\""
"markup.raw.block" = "style=\"color: #ffad66;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #73d0ff;\""
"operator" = "style=\"color: #ffad66;\""
"punctuation" = "style=\"color: #cccac2;\""
"special" = "style=\"color: #ffad66;\""
"string" = "style=\"color: #d5ff80;\""
"string.regexp" = "style=\"color: #ffad66;\""
"string.special" = "style=\"color: #ffcc77;\""
"tag" = "style=\"color: #73d0ff;\""
"type" = "style=\"color: #73d0ff;\""
"type.builtin" = "style=\"color: #73d0ff;\""
"variable" = "style=\"color: #cccac2;\""
