"debug" = "class=\"debug\" style=\"color: ;\""
"markup.normal" = "class=\"markup normal\" style=\"color: ; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: ;\""
"function" = "class=\"function\" style=\"color: ;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: ;\""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"markup.quote" = "class=\"markup quote\" style=\"color: ;\""
"markup.select" = "class=\"markup select\" style=\"color: ; \""
"keyword" = "class=\"keyword\" style=\"color: ;\""
"diff.delta" = "class=\"diff delta\" style=\"color: ;\""
"string" = "class=\"string\" style=\"color: ;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: ; color: ; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: ;\""
"operator" = "class=\"operator\" style=\"\""
"diff.plus" = "class=\"diff plus\" style=\"color: ;\""
"special" = "class=\"special\" style=\"color: ;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: ; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #ffffff; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: ;\""
"comment" = "class=\"comment\" style=\"color: ;\""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: ;\""
"markup.raw" = "class=\"markup raw\" style=\"color: ;\""
"markup.insert" = "class=\"markup insert\" style=\"color: ; \""
"diff.minus" = "class=\"diff minus\" style=\"color: ;\""
"constructor" = "class=\"constructor\" style=\"color: ;\""
"variable" = "class=\"variable\" style=\"color: ;\""
"text" = "class=\"text\" style=\"color: ; \""
"module" = "class=\"module\" style=\"color: ; \""
"constant" = "class=\"constant\" style=\"color: ;\""
"type" = "class=\"type\" style=\"color: ;\""
"attribute" = "class=\"attribute\" style=\"color: ;\""
"markup.heading" = "class=\"markup heading\" style=\"color: ;\""
"namespace" = "class=\"namespace\" style=\"color: ;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: ; \""
"label" = "class=\"label\" style=\"color: ;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
