"attribute" = "class=\"attribute\" style=\"color: ;\""
"background" = "class=\"background\" style=\"background-color: ; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: ; \""
"constant" = "class=\"constant\" style=\"color: ;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: ;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: ;\""
"constructor" = "class=\"constructor\" style=\"color: ;\""
"debug" = "class=\"debug\" style=\"color: ;\""
"diff.delta" = "class=\"diff delta\" style=\"color: ;\""
"diff.minus" = "class=\"diff minus\" style=\"color: ;\""
"diff.plus" = "class=\"diff plus\" style=\"color: ;\""
"function" = "class=\"function\" style=\"color: ;\""
"keyword" = "class=\"keyword\" style=\"color: ;\""
"label" = "class=\"label\" style=\"color: ;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: ; \""
"markup.heading" = "class=\"markup heading\" style=\"color: ;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: ;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: ; \""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"markup.quote" = "class=\"markup quote\" style=\"color: ;\""
"markup.raw" = "class=\"markup raw\" style=\"color: ;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: ; \""
"namespace" = "class=\"namespace\" style=\"color: ;\""
"operator" = "class=\"operator\" style=\"\""
"special" = "class=\"special\" style=\"color: ;\""
"string" = "class=\"string\" style=\"color: ;\""
"type" = "class=\"type\" style=\"color: ;\""
"variable" = "class=\"variable\" style=\"color: ;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: ;\""
