"attribute" = "class=\"attribute\" style=\"color: #dc9656;\""
"background" = "class=\"autumn highlight background\" style=\"background-color: #181818; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #585858; \""
"constant" = "class=\"constant\" style=\"color: #dc9656;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #86c1b9;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #dc9656;\""
"constructor" = "class=\"constructor\" style=\"color: #7cafc2;\""
"debug" = "class=\"debug\" style=\"color: #585858;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #dc9656;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ab4642;\""
"diff.plus" = "class=\"diff plus\" style=\"color: #a1b56c;\""
"function" = "class=\"function\" style=\"color: #7cafc2;\""
"keyword" = "class=\"keyword\" style=\"color: #ba8baf;\""
"label" = "class=\"label\" style=\"color: #ba8baf;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #f7ca88; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #7cafc2;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #ba8baf; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ab4642;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #dc9656; \""
"markup.list" = "class=\"markup list\" style=\"color: #ab4642;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #86c1b9;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #a1b56c;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #ba8baf; \""
"namespace" = "class=\"namespace\" style=\"color: #ba8baf;\""
"operator" = "class=\"operator\" style=\"color: #d8d8d8; \""
"special" = "class=\"special\" style=\"color: #7cafc2;\""
"string" = "class=\"string\" style=\"color: #a1b56c;\""
"text" = "class=\"text\" style=\"color: #d8d8d8; \""
"type" = "class=\"type\" style=\"color: #f7ca88;\""
"variable" = "class=\"variable\" style=\"color: #ab4642;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #a1b56c;\""
