"background" = "style=\"background-color: #181818; \""
"attribute" = "style=\"color: #dc9656;\""
"comment" = "style=\"text-decoration: underline; color: #585858; \""
"constant" = "style=\"color: #dc9656;\""
"constant.character.escape" = "style=\"color: #86c1b9;\""
"constant.numeric" = "style=\"color: #dc9656;\""
"constructor" = "style=\"color: #7cafc2;\""
"debug" = "style=\"color: #585858;\""
"diff.delta" = "style=\"color: #dc9656;\""
"diff.minus" = "style=\"color: #ab4642;\""
"diff.plus" = "style=\"color: #a1b56c;\""
"function" = "style=\"color: #7cafc2;\""
"keyword" = "style=\"color: #ba8baf;\""
"label" = "style=\"color: #ba8baf;\""
"markup.bold" = "style=\"font-weight: bold; color: #f7ca88; \""
"markup.heading" = "style=\"color: #7cafc2;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ba8baf; \""
"markup.link.text" = "style=\"color: #ab4642;\""
"markup.link.url" = "style=\"color: #dc9656; \""
"markup.list" = "style=\"color: #ab4642;\""
"markup.quote" = "style=\"color: #86c1b9;\""
"markup.raw" = "style=\"color: #a1b56c;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ba8baf;\""
"operator" = "style=\"color: #d8d8d8;\""
"special" = "style=\"color: #7cafc2;\""
"string" = "style=\"color: #a1b56c;\""
"type" = "style=\"color: #f7ca88;\""
"variable" = "style=\"color: #ab4642;\""
"variable.other.member" = "style=\"color: #a1b56c;\""
