"background" = "style=\"background-color: #f6fbd6; \""
"attribute" = "style=\"color: #dc7759;\""
"comment" = "style=\"color: #627d9d;\""
"constant" = "style=\"color: #23a580;\""
"constant.builtin" = "style=\"color: #23a580;\""
"constant.character.escape" = "style=\"font-weight: bold; color: #7fdc59; \""
"constant.numeric" = "style=\"color: #59c0dc;\""
"constructor" = "style=\"color: #dc597f;\""
"diff.delta" = "style=\"color: #dc7759;\""
"diff.minus" = "style=\"color: #dc597f;\""
"diff.plus" = "style=\"color: #23a580;\""
"function" = "style=\"color: #289cbc;\""
"function.builtin" = "style=\"font-weight: bold; color: #289cbc; \""
"function.macro" = "style=\"font-weight: bold; color: #dc7759; \""
"keyword" = "style=\"font-weight: bold; color: #a58023; \""
"keyword.directive" = "style=\"color: #a58023;\""
"label" = "style=\"color: #59c0dc;\""
"markup.bold" = "style=\"font-weight: bold; color: #a58023; \""
"markup.heading" = "style=\"color: #59c0dc;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: #d32c5d;\""
"markup.link.url" = "style=\"color: #a58023; \""
"markup.list" = "style=\"color: #d32c5d;\""
"markup.quote" = "style=\"color: #289cbc;\""
"markup.raw" = "style=\"color: #23a580;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #d32c5d;\""
"namespace" = "style=\"color: #d32c5d;\""
"operator" = "style=\"font-weight: bold; color: #dc7759; \""
"punctuation" = "style=\"color: #dc7759;\""
"punctuation.delimiter" = "style=\"color: #dc7759;\""
"special" = "style=\"color: #7fdc59;\""
"string" = "style=\"color: #23a580;\""
"type" = "style=\"color: #dc597f;\""
"type.builtin" = "style=\"font-weight: bold; color: #d32c5d; \""
"variable" = "style=\"color: #232d38;\""
"variable.builtin" = "style=\"color: #232d38;\""
"variable.other.member" = "style=\"color: #232d38;\""
"variable.parameter" = "style=\"color: #232d38;\""
