"attribute" = "style=\"color: #dc7759;\""
"comment" = "style=\"color: #abb2bf;\""
"constant" = "style=\"color: #59dcb7;\""
"constant.builtin" = "style=\"color: #59dcb7;\""
"constant.character.escape" = "style=\"font-weight: bold; color: #7fdc59; \""
"constant.numeric" = "style=\"color: #36b2d4;\""
"constructor" = "style=\"color: #dc597f;\""
"diff.delta" = "style=\"color: #dc7759;\""
"diff.minus" = "style=\"color: #dc597f;\""
"diff.plus" = "style=\"color: #59dcb7;\""
"function" = "style=\"color: #59dcd8;\""
"function.builtin" = "style=\"font-weight: bold; color: #59dcd8; \""
"function.macro" = "style=\"font-weight: bold; color: #dc7759; \""
"keyword" = "style=\"font-weight: bold; color: #dcb659; \""
"keyword.directive" = "style=\"color: #dcb659;\""
"label" = "style=\"color: #36b2d4;\""
"markup.bold" = "style=\"font-weight: bold; color: #dcb659; \""
"markup.heading" = "style=\"color: #36b2d4;\""
"markup.italic" = "style=\"text-decoration: underline; color: #b759dc; \""
"markup.link.text" = "style=\"color: #d32c5d;\""
"markup.link.url" = "style=\"color: #dcb659; \""
"markup.list" = "style=\"color: #d32c5d;\""
"markup.quote" = "style=\"color: #59dcb7;\""
"markup.raw" = "style=\"color: #7fdc59;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #d32c5d;\""
"namespace" = "style=\"color: #d32c5d;\""
"operator" = "style=\"font-weight: bold; color: #dc7759; \""
"punctuation" = "style=\"color: #dc7759;\""
"punctuation.delimiter" = "style=\"color: #dc7759;\""
"special" = "style=\"color: #7fdc59;\""
"string" = "style=\"color: #59dcb7;\""
"type" = "style=\"color: #dc597f;\""
"type.builtin" = "style=\"font-weight: bold; color: #d32c5d; \""
"variable" = "style=\"color: #c6b8ad;\""
"variable.builtin" = "style=\"color: #c6b8ad;\""
"variable.other.member" = "style=\"color: #c6b8ad;\""
"variable.parameter" = "style=\"color: #c6b8ad;\""
