"constant.numeric" = "class=\"constant numeric\" style=\"color: #36b2d4;\""
"function" = "class=\"function\" style=\"color: #59dcd8;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #c6b8ad;\""
"markup.list" = "class=\"markup list\" style=\"color: #d32c5d;\""
"function.builtin" = "class=\"function builtin\" style=\"font-weight: bold; color: #59dcd8; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #59dcb7;\""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #dcb659; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #dc7759;\""
"string" = "class=\"string\" style=\"color: #59dcb7;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #c6b8ad;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #dc7759;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #c6b8ad;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #dcb659; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #7fdc59; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #dcb659;\""
"operator" = "class=\"operator\" style=\"color: #dc7759; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #59dcb7;\""
"special" = "class=\"special\" style=\"color: #7fdc59;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #dc7759; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #b759dc; \""
"background" = "class=\"background\" style=\"background-color: #161c23; \""
"punctuation" = "class=\"punctuation\" style=\"color: #dc7759;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d32c5d;\""
"comment" = "class=\"comment\" style=\"color: #abb2bf;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #7fdc59;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #dc597f;\""
"type.builtin" = "class=\"type builtin\" style=\"font-weight: bold; color: #d32c5d; \""
"constructor" = "class=\"constructor\" style=\"color: #dc597f;\""
"variable" = "class=\"variable\" style=\"color: #c6b8ad;\""
"text" = "class=\"text\" style=\"color: #e5ded6; \""
"module" = "class=\"module\" style=\"color: #d32c5d; \""
"constant" = "class=\"constant\" style=\"color: #59dcb7;\""
"type" = "class=\"type\" style=\"color: #dc597f;\""
"attribute" = "class=\"attribute\" style=\"color: #dc7759;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #59dcb7;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #36b2d4;\""
"namespace" = "class=\"namespace\" style=\"color: #d32c5d;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #dcb659; \""
"label" = "class=\"label\" style=\"color: #36b2d4;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
