"background" = "style=\"background-color: #3A2A4D; \""
"attribute" = "style=\"color: #C7B8E0; \""
"comment" = "style=\"color: #886C9C; \""
"constant" = "style=\"color: #E3C0A8; \""
"diff.delta" = "style=\"color: #E3C0A8; \""
"diff.minus" = "style=\"color: #D678B5; \""
"diff.plus" = "style=\"color: #7FC9AB; \""
"function" = "style=\"color: #7FC9AB; \""
"function.macro" = "style=\"color: #D678B5; \""
"keyword" = "style=\"color: #D678B5; \""
"label" = "style=\"color: #E3C0A8; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #E3C0A8; \""
"markup.heading.marker" = "style=\"color: #886C9C; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #C78DFC; \""
"markup.link.url" = "style=\"color: #C78DFC; \""
"markup.list" = "style=\"color: #D678B5; \""
"markup.quote" = "style=\"color: #886C9C; \""
"markup.raw" = "style=\"color: #7FC9AB; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #C7B8E0; \""
"namespace" = "style=\"color: #C7B8E0; \""
"operator" = "style=\"color: #D678B5; \""
"punctuation" = "style=\"color: #C7B8E0; \""
"string" = "style=\"color: #E3C0A8; \""
"tag" = "style=\"color: #E3C0A8; \""
"type" = "style=\"color: #C78DFC; \""
"variable" = "style=\"color: #C7B8E0; \""
"variable.builtin" = "style=\"color: #C78DFC; \""
