"function" = "class=\"function\" style=\"color: #1e66f5;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #179299;\""
"markup.list" = "class=\"markup list\" style=\"color: #8839ef;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #df8e1d;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #ea76cb;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #40a02b;\""
"keyword" = "class=\"keyword\" style=\"color: #8839ef;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #1e66f5;\""
"string" = "class=\"string\" style=\"color: #40a02b;\""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #e64553; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #d20f39;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #dc8a78; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ea76cb;\""
"operator" = "class=\"operator\" style=\"color: #04a5e5; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #40a02b;\""
"special" = "class=\"special\" style=\"color: #1e66f5;\""
"function.macro" = "class=\"function macro\" style=\"color: #8839ef;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #eff1f5; \""
"punctuation" = "class=\"punctuation\" style=\"color: #7c7f93;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #1e66f5;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #8c8fa1; \""
"tag" = "class=\"tag\" style=\"color: #8839ef;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #dd7878;\""
"constant.character" = "class=\"constant character\" style=\"color: #179299;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #d20f39;\""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"color: #179299;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #8839ef;\""
"constructor" = "class=\"constructor\" style=\"color: #209fb5;\""
"variable" = "class=\"variable\" style=\"color: #4c4f69;\""
"text" = "class=\"text\" style=\"color: #4c4f69; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #fe640b;\""
"module" = "class=\"module\" style=\"color: #1e66f5; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #04a5e5;\""
"constant" = "class=\"constant\" style=\"color: #fe640b;\""
"string.special" = "class=\"string special\" style=\"color: #1e66f5;\""
"type" = "class=\"type\" style=\"color: #df8e1d;\""
"attribute" = "class=\"attribute\" style=\"color: #1e66f5;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #179299;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #fe640b;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #7287fd;\""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-style: italic; color: #8839ef; \""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #1e66f5; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #fe640b; \""
"label" = "class=\"label\" style=\"color: #209fb5;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
