"background" = "style=\"background-color: #303446; \""
"attribute" = "style=\"color: #8caaee;\""
"comment" = "style=\"text-decoration: underline; color: #838ba7; \""
"constant" = "style=\"color: #ef9f76;\""
"constant.builtin" = "style=\"color: #ef9f76;\""
"constant.character" = "style=\"color: #81c8be;\""
"constant.character.escape" = "style=\"color: #f4b8e4;\""
"constructor" = "style=\"color: #85c1dc;\""
"diff.delta" = "style=\"color: #8caaee;\""
"diff.minus" = "style=\"color: #e78284;\""
"diff.plus" = "style=\"color: #a6d189;\""
"function" = "style=\"color: #8caaee;\""
"function.macro" = "style=\"color: #ca9ee6;\""
"keyword" = "style=\"color: #ca9ee6;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #ca9ee6; \""
"keyword.storage.modifier.ref" = "style=\"color: #81c8be;\""
"label" = "style=\"color: #85c1dc;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: #babbf1;\""
"markup.heading.2" = "style=\"color: #ca9ee6;\""
"markup.heading.3" = "style=\"color: #a6d189;\""
"markup.heading.4" = "style=\"color: #e5c890;\""
"markup.heading.5" = "style=\"color: #f4b8e4;\""
"markup.heading.6" = "style=\"color: #81c8be;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: #ef9f76; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #8caaee;\""
"markup.link.url" = "style=\"color: #f2d5cf; \""
"markup.list" = "style=\"color: #ca9ee6;\""
"markup.raw" = "style=\"color: #eebebe;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #8caaee; \""
"operator" = "style=\"color: #99d1db;\""
"punctuation" = "style=\"color: #949cbb;\""
"punctuation.special" = "style=\"color: #99d1db;\""
"special" = "style=\"color: #8caaee;\""
"string" = "style=\"color: #a6d189;\""
"string.regexp" = "style=\"color: #ef9f76;\""
"string.special" = "style=\"color: #8caaee;\""
"tag" = "style=\"color: #ca9ee6;\""
"type" = "style=\"color: #e5c890;\""
"variable" = "style=\"color: #c6d0f5;\""
"variable.builtin" = "style=\"color: #e78284;\""
"variable.other.member" = "style=\"color: #81c8be;\""
"variable.parameter" = "style=\"text-decoration: underline; color: #ea999c; \""
