"function" = "class=\"function\" style=\"color: #89b4fa;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #94e2d5;\""
"markup.list" = "class=\"markup list\" style=\"color: #cba6f7;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #f9e2af;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #f5c2e7;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #a6e3a1;\""
"keyword" = "class=\"keyword\" style=\"color: #cba6f7;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #89b4fa;\""
"string" = "class=\"string\" style=\"color: #a6e3a1;\""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #eba0ac; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #f38ba8;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #f5e0dc; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f5c2e7;\""
"operator" = "class=\"operator\" style=\"color: #89dceb; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a6e3a1;\""
"special" = "class=\"special\" style=\"color: #89b4fa;\""
"function.macro" = "class=\"function macro\" style=\"color: #cba6f7;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #1e1e2e; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9399b2;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #89b4fa;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #7f849c; \""
"tag" = "class=\"tag\" style=\"color: #cba6f7;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #f2cdcd;\""
"constant.character" = "class=\"constant character\" style=\"color: #94e2d5;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f38ba8;\""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"color: #94e2d5;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #cba6f7;\""
"constructor" = "class=\"constructor\" style=\"color: #74c7ec;\""
"variable" = "class=\"variable\" style=\"color: #cdd6f4;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #fab387;\""
"module" = "class=\"module\" style=\"color: #89b4fa; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #89dceb;\""
"constant" = "class=\"constant\" style=\"color: #fab387;\""
"string.special" = "class=\"string special\" style=\"color: #89b4fa;\""
"type" = "class=\"type\" style=\"color: #f9e2af;\""
"attribute" = "class=\"attribute\" style=\"color: #89b4fa;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #94e2d5;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #fab387;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #b4befe;\""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-style: italic; color: #cba6f7; \""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #89b4fa; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #fab387; \""
"label" = "class=\"label\" style=\"color: #74c7ec;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
