"attribute" = "style=\"color: #89b4fa;\""
"comment" = "style=\"text-decoration: underline; color: #7f849c; \""
"constant" = "style=\"color: #fab387;\""
"constant.builtin" = "style=\"color: #fab387;\""
"constant.character" = "style=\"color: #94e2d5;\""
"constant.character.escape" = "style=\"color: #f5c2e7;\""
"constructor" = "style=\"color: #74c7ec;\""
"diff.delta" = "style=\"color: #89b4fa;\""
"diff.minus" = "style=\"color: #f38ba8;\""
"diff.plus" = "style=\"color: #a6e3a1;\""
"function" = "style=\"color: #89b4fa;\""
"function.macro" = "style=\"color: #cba6f7;\""
"keyword" = "style=\"color: #cba6f7;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #cba6f7; \""
"keyword.storage.modifier.ref" = "style=\"color: #94e2d5;\""
"label" = "style=\"color: #74c7ec;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: #b4befe;\""
"markup.heading.2" = "style=\"color: #cba6f7;\""
"markup.heading.3" = "style=\"color: #a6e3a1;\""
"markup.heading.4" = "style=\"color: #f9e2af;\""
"markup.heading.5" = "style=\"color: #f5c2e7;\""
"markup.heading.6" = "style=\"color: #94e2d5;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: #fab387; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #89b4fa;\""
"markup.link.url" = "style=\"color: #f5e0dc; \""
"markup.list" = "style=\"color: #cba6f7;\""
"markup.raw" = "style=\"color: #f2cdcd;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #89b4fa; \""
"operator" = "style=\"color: #89dceb;\""
"punctuation" = "style=\"color: #9399b2;\""
"punctuation.special" = "style=\"color: #89dceb;\""
"special" = "style=\"color: #89b4fa;\""
"string" = "style=\"color: #a6e3a1;\""
"string.regexp" = "style=\"color: #fab387;\""
"string.special" = "style=\"color: #89b4fa;\""
"tag" = "style=\"color: #cba6f7;\""
"type" = "style=\"color: #f9e2af;\""
"variable" = "style=\"color: #cdd6f4;\""
"variable.builtin" = "style=\"color: #f38ba8;\""
"variable.other.member" = "style=\"color: #94e2d5;\""
"variable.parameter" = "style=\"text-decoration: underline; color: #eba0ac; \""
