"attribute" = "style=\"color: #8aadf4;\""
"comment" = "style=\"text-decoration: underline; color: #8087a2; \""
"constant" = "style=\"color: #f5a97f;\""
"constant.builtin" = "style=\"color: #f5a97f;\""
"constant.character" = "style=\"color: #8bd5ca;\""
"constant.character.escape" = "style=\"color: #f5bde6;\""
"constructor" = "style=\"color: #7dc4e4;\""
"diff.delta" = "style=\"color: #8aadf4;\""
"diff.minus" = "style=\"color: #ed8796;\""
"diff.plus" = "style=\"color: #a6da95;\""
"function" = "style=\"color: #8aadf4;\""
"function.macro" = "style=\"color: #c6a0f6;\""
"keyword" = "style=\"color: #c6a0f6;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #c6a0f6; \""
"keyword.storage.modifier.ref" = "style=\"color: #8bd5ca;\""
"label" = "style=\"color: #7dc4e4;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: #b7bdf8;\""
"markup.heading.2" = "style=\"color: #c6a0f6;\""
"markup.heading.3" = "style=\"color: #a6da95;\""
"markup.heading.4" = "style=\"color: #eed49f;\""
"markup.heading.5" = "style=\"color: #f5bde6;\""
"markup.heading.6" = "style=\"color: #8bd5ca;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: #f5a97f; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #8aadf4;\""
"markup.link.url" = "style=\"color: #f4dbd6; \""
"markup.list" = "style=\"color: #c6a0f6;\""
"markup.raw" = "style=\"color: #f0c6c6;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #8aadf4; \""
"operator" = "style=\"color: #91d7e3;\""
"punctuation" = "style=\"color: #939ab7;\""
"punctuation.special" = "style=\"color: #91d7e3;\""
"special" = "style=\"color: #8aadf4;\""
"string" = "style=\"color: #a6da95;\""
"string.regexp" = "style=\"color: #f5a97f;\""
"string.special" = "style=\"color: #8aadf4;\""
"tag" = "style=\"color: #c6a0f6;\""
"type" = "style=\"color: #eed49f;\""
"variable" = "style=\"color: #cad3f5;\""
"variable.builtin" = "style=\"color: #ed8796;\""
"variable.other.member" = "style=\"color: #8bd5ca;\""
"variable.parameter" = "style=\"text-decoration: underline; color: #ee99a0; \""
