"attribute" = "style=\"color: #1e66f5;\""
"comment" = "style=\"text-decoration: underline; color: #8c8fa1; \""
"constant" = "style=\"color: #fe640b;\""
"constant.builtin" = "style=\"color: #fe640b;\""
"constant.character" = "style=\"color: #179299;\""
"constant.character.escape" = "style=\"color: #ea76cb;\""
"constructor" = "style=\"color: #209fb5;\""
"diff.delta" = "style=\"color: #1e66f5;\""
"diff.minus" = "style=\"color: #d20f39;\""
"diff.plus" = "style=\"color: #40a02b;\""
"function" = "style=\"color: #1e66f5;\""
"function.macro" = "style=\"color: #8839ef;\""
"keyword" = "style=\"color: #8839ef;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #8839ef; \""
"keyword.storage.modifier.ref" = "style=\"color: #179299;\""
"label" = "style=\"color: #209fb5;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: #7287fd;\""
"markup.heading.2" = "style=\"color: #8839ef;\""
"markup.heading.3" = "style=\"color: #40a02b;\""
"markup.heading.4" = "style=\"color: #df8e1d;\""
"markup.heading.5" = "style=\"color: #ea76cb;\""
"markup.heading.6" = "style=\"color: #179299;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: #fe640b; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #1e66f5;\""
"markup.link.url" = "style=\"color: #dc8a78; \""
"markup.list" = "style=\"color: #8839ef;\""
"markup.raw" = "style=\"color: #dd7878;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #1e66f5; \""
"operator" = "style=\"color: #04a5e5;\""
"punctuation" = "style=\"color: #7c7f93;\""
"punctuation.special" = "style=\"color: #04a5e5;\""
"special" = "style=\"color: #1e66f5;\""
"string" = "style=\"color: #40a02b;\""
"string.regexp" = "style=\"color: #fe640b;\""
"string.special" = "style=\"color: #1e66f5;\""
"tag" = "style=\"color: #8839ef;\""
"type" = "style=\"color: #df8e1d;\""
"variable" = "style=\"color: #4c4f69;\""
"variable.builtin" = "style=\"color: #d20f39;\""
"variable.other.member" = "style=\"color: #179299;\""
"variable.parameter" = "style=\"text-decoration: underline; color: #e64553; \""
