"attribute" = "style=\"color: #0073E6;\""
"comment" = "style=\"color: #808080;\""
"constant" = "style=\"color: #000080;\""
"constant.builtin.boolean" = "style=\"color: #0073E6;\""
"constant.character" = "style=\"color: #0073E6;\""
"constant.character.escape" = "style=\"color: #7F0000;\""
"constant.numeric" = "style=\"color: #0073E6;\""
"constructor" = "style=\"color: #25293c;\""
"diff.delta" = "style=\"color: #C3D6E8;\""
"diff.minus" = "style=\"color: #EBBCBC;\""
"diff.plus" = "style=\"color: #C9DEC1;\""
"function" = "style=\"color: #25293c;\""
"function.builtin" = "style=\"text-decoration: underline; color: #25293c; \""
"function.macro" = "style=\"color: #808000;\""
"function.method" = "style=\"color: #7A7A43;\""
"function.special" = "style=\"color: #7F0000;\""
"keyword" = "style=\"color: #000080;\""
"keyword.control.exception" = "style=\"color: #000080;\""
"label" = "style=\"color: #000080; \""
"markup.bold" = "style=\"font-weight: bold; color: #343a54; \""
"markup.heading" = "style=\"color: #660E7A; \""
"markup.italic" = "style=\"text-decoration: underline; color: #343a54; \""
"markup.link.label" = "style=\"color: #185b93;\""
"markup.link.text" = "style=\"color: #185b93; \""
"markup.link.url" = "style=\"color: #343a54;\""
"markup.list" = "style=\"color: #000080;\""
"markup.list.numbered" = "style=\"color: #000080;\""
"markup.list.unnumbered" = "style=\"color: #000080;\""
"markup.quote" = "style=\"color: #00733B;\""
"markup.raw" = "style=\"color: #00733B;\""
"markup.raw.block" = "style=\"color: #00733B;\""
"markup.raw.inline" = "style=\"color: #00733B;\""
"markup.strikethrough" = "style=\"color: #343a54; \""
"namespace" = "style=\"color: #000080;\""
"operator" = "style=\"color: #343a54;\""
"punctuation" = "style=\"color: #343a54;\""
"special" = "style=\"color: #343a54;\""
"string" = "style=\"color: #00733B;\""
"string.regexp" = "style=\"color: #0073E6;\""
"string.special" = "style=\"color: #7F0000; \""
"tag" = "style=\"color: #000080;\""
"type" = "style=\"color: #25293c;\""
"type.enum.variant" = "style=\"color: #660E7A;\""
"variable" = "style=\"color: #458383;\""
"variable.builtin" = "style=\"color: #000080; \""
"variable.other.member" = "style=\"color: #660E7A;\""
"variable.parameter" = "style=\"color: #660E7A;\""
