"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #000080;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #0073E6;\""
"function" = "class=\"function\" style=\"color: #25293c;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #660E7A;\""
"markup.list" = "class=\"markup list\" style=\"color: #000080;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #185b93;\""
"function.builtin" = "class=\"function builtin\" style=\"font-style: italic; color: #25293c; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #00733B;\""
"keyword" = "class=\"keyword\" style=\"color: #000080;\""
"function.special" = "class=\"function special\" style=\"color: #7F0000;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #C3D6E8;\""
"string" = "class=\"string\" style=\"color: #00733B;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #00733B;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #660E7A;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #000080; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #343a54;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #7F0000;\""
"operator" = "class=\"operator\" style=\"color: #343a54; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #C9DEC1;\""
"special" = "class=\"special\" style=\"color: #343a54;\""
"function.macro" = "class=\"function macro\" style=\"color: #808000;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #343a54; \""
"background" = "class=\"background\" style=\"background-color: #f2f3f7; \""
"punctuation" = "class=\"punctuation\" style=\"color: #343a54;\""
"markup.link.text" = "class=\"markup link text\" style=\"text-decoration: underline; color: #185b93; \""
"comment" = "class=\"comment\" style=\"color: #808080;\""
"tag" = "class=\"tag\" style=\"color: #000080;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #00733B;\""
"constant.character" = "class=\"constant character\" style=\"color: #0073E6;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #EBBCBC;\""
"constructor" = "class=\"constructor\" style=\"color: #25293c;\""
"variable" = "class=\"variable\" style=\"color: #458383;\""
"text" = "class=\"text\" style=\"color: #434b6c; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #660E7A;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #0073E6;\""
"module" = "class=\"module\" style=\"color: #000080; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #0073E6;\""
"constant" = "class=\"constant\" style=\"color: #000080;\""
"string.special" = "class=\"string special\" style=\"text-decoration: underline; color: #7F0000; \""
"function.method" = "class=\"function method\" style=\"color: #7A7A43;\""
"type" = "class=\"type\" style=\"color: #25293c;\""
"attribute" = "class=\"attribute\" style=\"color: #0073E6;\""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #000080;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #660E7A; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #00733B;\""
"namespace" = "class=\"namespace\" style=\"color: #000080;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #343a54; \""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #000080;\""
"label" = "class=\"label\" style=\"text-decoration: underline; color: #000080; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"color: #343a54; \""
