"debug" = "class=\"debug\" style=\"color: #d8d8d8;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #6897bb;\""
"function" = "class=\"function\" style=\"color: #eedd82;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #eedd82;\""
"markup.list" = "class=\"markup list\" style=\"color: #d0d0d0;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #629755;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #808080;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #9876aa;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #a34a27;\""
"keyword" = "class=\"keyword\" style=\"color: #cc7832;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #808080;\""
"string" = "class=\"string\" style=\"color: #629755;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #6897bb; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #d0d0d0;\""
"operator" = "class=\"operator\" style=\"color: #d8d8d8; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #32cd32;\""
"special" = "class=\"special\" style=\"color: #32cd32;\""
"function.macro" = "class=\"function macro\" style=\"color: #32cd32;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #d0d0d0; \""
"background" = "class=\"background\" style=\"background-color: #1f1f1f; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d0d0d0;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #808080; \""
"tag" = "class=\"tag\" style=\"color: #cc7832;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #d0d0d0;\""
"diff.minus" = "class=\"diff minus\" style=\"color: ;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #eedd82;\""
"constructor" = "class=\"constructor\" style=\"color: #eedd82;\""
"variable" = "class=\"variable\" style=\"color: #d0d0d0;\""
"text" = "class=\"text\" style=\"color: #d0d0d0; \""
"module" = "class=\"module\" style=\"color: #9876aa; \""
"constant" = "class=\"constant\" style=\"color: #6897bb;\""
"type" = "class=\"type\" style=\"color: #cc7832;\""
"attribute" = "class=\"attribute\" style=\"color: #eedd82;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #629755;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #cc7832;\""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #9876aa; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #d0d0d0; \""
"label" = "class=\"label\" style=\"color: #9876aa;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"color: #d0d0d0; \""
