"attribute" = "style=\"color: ;\""
"comment" = "style=\"text-decoration: underline; color: ; \""
"constant" = "style=\"color: ;\""
"constant.character.escape" = "style=\"color: ;\""
"constant.numeric" = "style=\"color: ;\""
"constructor" = "style=\"color: ;\""
"debug" = "style=\"color: ;\""
"diff.delta" = "style=\"color: ;\""
"diff.minus" = "style=\"color: ;\""
"diff.plus" = "style=\"color: ;\""
"function" = "style=\"color: ;\""
"function.macro" = "style=\"color: ;\""
"keyword" = "style=\"color: ;\""
"label" = "style=\"color: ;\""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading.1" = "style=\"color: ;\""
"markup.heading.2" = "style=\"color: ;\""
"markup.heading.3" = "style=\"color: ;\""
"markup.heading.4" = "style=\"color: ;\""
"markup.heading.5" = "style=\"color: ;\""
"markup.heading.6" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"color: ;\""
"markup.raw" = "style=\"color: ;\""
"markup.strikethrough" = "style=\"color: ; \""
"namespace" = "style=\"text-decoration: underline; color: ; \""
"operator" = "style=\"color: ;\""
"special" = "style=\"color: ;\""
"string" = "style=\"color: ;\""
"tag" = "style=\"color: ;\""
"type" = "style=\"color: ;\""
"variable" = "style=\"color: ;\""
"variable.other.member" = "style=\"color: ;\""
