"attribute" = "style=\"color: #eedd82;\""
"comment" = "style=\"text-decoration: underline; color: #808080; \""
"constant" = "style=\"color: #6897bb;\""
"constant.character.escape" = "style=\"color: #d0d0d0;\""
"constant.numeric" = "style=\"color: #6897bb;\""
"constructor" = "style=\"color: #eedd82;\""
"debug" = "style=\"color: #d8d8d8;\""
"diff.delta" = "style=\"color: #808080;\""
"diff.minus" = "style=\"color: ;\""
"diff.plus" = "style=\"color: #32cd32;\""
"function" = "style=\"color: #eedd82;\""
"function.macro" = "style=\"color: #32cd32;\""
"keyword" = "style=\"color: #cc7832;\""
"label" = "style=\"color: #9876aa;\""
"markup.bold" = "style=\"font-weight: bold; color: #d0d0d0; \""
"markup.heading.1" = "style=\"color: #cc7832;\""
"markup.heading.2" = "style=\"color: #eedd82;\""
"markup.heading.3" = "style=\"color: #a34a27;\""
"markup.heading.4" = "style=\"color: #808080;\""
"markup.heading.5" = "style=\"color: #9876aa;\""
"markup.heading.6" = "style=\"color: #629755;\""
"markup.italic" = "style=\"text-decoration: underline; color: #d0d0d0; \""
"markup.link.text" = "style=\"color: #d0d0d0;\""
"markup.link.url" = "style=\"color: #6897bb; \""
"markup.list" = "style=\"color: #d0d0d0;\""
"markup.quote" = "style=\"color: #629755;\""
"markup.raw" = "style=\"color: #d0d0d0;\""
"markup.strikethrough" = "style=\"color: #d0d0d0; \""
"namespace" = "style=\"text-decoration: underline; color: #9876aa; \""
"operator" = "style=\"color: #d8d8d8;\""
"special" = "style=\"color: #32cd32;\""
"string" = "style=\"color: #629755;\""
"tag" = "style=\"color: #cc7832;\""
"type" = "style=\"color: #cc7832;\""
"variable" = "style=\"color: #d0d0d0;\""
"variable.other.member" = "style=\"color: #eedd82;\""
