"constant.numeric" = "class=\"constant numeric\" style=\"color: #b5cea8; \""
"function" = "class=\"function\" style=\"color: #DCDCAA; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #9CDCFE; \""
"markup.list" = "class=\"markup list\" style=\"color: #6796E6;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #DCDCAA; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #6A9955;\""
"keyword" = "class=\"keyword\" style=\"color: #569CD6; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #1b81a8; \""
"string" = "class=\"string\" style=\"color: #ce9178; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #9CDCFE; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #d4d4d4; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #569CD6; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #C586C0; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #d7ba7d; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #569CD6; \""
"operator" = "class=\"operator\" style=\"color: #d4d4d4; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #487e02; \""
"special" = "class=\"special\" style=\"color: #d4d4d4; \""
"function.macro" = "class=\"function macro\" style=\"color: #569CD6; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #1e1e1e; \""
"punctuation" = "class=\"punctuation\" style=\"color: #d4d4d4; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ce9178;\""
"comment" = "class=\"comment\" style=\"color: #6A9955; \""
"tag" = "class=\"tag\" style=\"color: #569CD6;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #ce9178;\""
"constant.character" = "class=\"constant character\" style=\"color: #ce9178; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #f14c4c; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #4EC9B0; \""
"constructor" = "class=\"constructor\" style=\"color: #4EC9B0; \""
"variable" = "class=\"variable\" style=\"color: #9CDCFE; \""
"text" = "class=\"text\" style=\"color: #d4d4d4; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #4FC1FF; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #d7ba7d; \""
"module" = "class=\"module\" style=\"color: #4EC9B0; \""
"constant" = "class=\"constant\" style=\"color: #4FC1FF; \""
"type" = "class=\"type\" style=\"color: #4EC9B0; \""
"attribute" = "class=\"attribute\" style=\"color: #DCDCAA; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #569CD6; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #569CD6; \""
"namespace" = "class=\"namespace\" style=\"color: #4EC9B0; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #569CD6; \""
"label" = "class=\"label\" style=\"color: #569CD6; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
