"debug" = "class=\"debug\" style=\"color: #b65f5f;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #4ec9b0;\""
"function" = "class=\"function\" style=\"color: #cedc84;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #ce9178;\""
"markup.list" = "class=\"markup list\" style=\"color: #ff5c8d;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #cedc84;\""
"keyword" = "class=\"keyword\" style=\"color: #66a4ff;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #66a4ff;\""
"string" = "class=\"string\" style=\"color: #ce9178;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #66a4ff; color: #66a4ff; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #c586c0;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #cedc84;\""
"operator" = "class=\"operator\" style=\"color: #ffffff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #427a2d;\""
"special" = "class=\"special\" style=\"color: #f38518;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #66a4ff; \""
"background" = "class=\"background\" style=\"background-color: #000000; \""
"string.special.url" = "class=\"string special url\" style=\"color: #ce9178;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ff5c8d;\""
"comment" = "class=\"comment\" style=\"color: #ffffff;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #ce9178;\""
"attributes" = "class=\"attributes\" style=\"color: #66a4ff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff5c8d;\""
"constructor" = "class=\"constructor\" style=\"color: #6fc3df;\""
"variable" = "class=\"variable\" style=\"color: #6fc3df;\""
"text" = "class=\"text\" style=\"color: #ffffff; \""
"module" = "class=\"module\" style=\"color: #66a4ff; \""
"constant" = "class=\"constant\" style=\"color: #6fc3df;\""
"type" = "class=\"type\" style=\"color: #4ec9b0;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #cedc84; font-weight: bold; color: #cedc84; \""
"namespace" = "class=\"namespace\" style=\"color: #66a4ff;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #4ec9b0; \""
"type.buildin" = "class=\"type buildin\" style=\"color: #4ec9b0;\""
"label" = "class=\"label\" style=\"color: #66a4ff;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
