"attributes" = "style=\"color: #66a4ff;\""
"comment" = "style=\"color: #ffffff;\""
"constant" = "style=\"color: #6fc3df;\""
"constant.character.escape" = "style=\"color: #cedc84;\""
"constant.numeric" = "style=\"color: #4ec9b0;\""
"constructor" = "style=\"color: #6fc3df;\""
"debug" = "style=\"color: #b65f5f;\""
"diff.delta" = "style=\"color: #66a4ff;\""
"diff.minus" = "style=\"color: #ff5c8d;\""
"diff.plus" = "style=\"color: #427a2d;\""
"function" = "style=\"color: #cedc84;\""
"keyword" = "style=\"color: #66a4ff;\""
"keyword.control" = "style=\"color: #c586c0;\""
"label" = "style=\"color: #66a4ff;\""
"markup.bold" = "style=\"font-weight: bold; color: #4ec9b0; \""
"markup.heading" = "style=\"color: #cedc84; font-weight: bold; color: #cedc84; \""
"markup.italic" = "style=\"text-decoration: underline; color: #66a4ff; \""
"markup.link.text" = "style=\"color: #ff5c8d;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #66a4ff; color: #66a4ff; \""
"markup.list" = "style=\"color: #ff5c8d;\""
"markup.quote" = "style=\"color: #cedc84;\""
"markup.raw" = "style=\"color: #ce9178;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #66a4ff;\""
"operator" = "style=\"color: #ffffff;\""
"special" = "style=\"color: #f38518;\""
"string" = "style=\"color: #ce9178;\""
"string.special.url" = "style=\"color: #ce9178;\""
"type" = "style=\"color: #4ec9b0;\""
"type.buildin" = "style=\"color: #4ec9b0;\""
"variable" = "style=\"color: #6fc3df;\""
"variable.other.member" = "style=\"color: #ce9178;\""
