"attribute" = "style=\"color: #DCDCAA; \""
"comment" = "style=\"color: #6A9955; \""
"constant" = "style=\"color: #4FC1FF; \""
"constant.builtin" = "style=\"color: #569CD6; \""
"constant.character" = "style=\"color: #ce9178; \""
"constant.character.escape" = "style=\"color: #d7ba7d; \""
"constant.numeric" = "style=\"color: #b5cea8; \""
"constructor" = "style=\"color: #4EC9B0; \""
"diff.delta" = "style=\"color: #1b81a8; \""
"diff.minus" = "style=\"color: #f14c4c; \""
"diff.plus" = "style=\"color: #487e02; \""
"function" = "style=\"color: #DCDCAA; \""
"function.builtin" = "style=\"color: #DCDCAA; \""
"function.macro" = "style=\"color: #569CD6; \""
"keyword" = "style=\"color: #569CD6; \""
"keyword.control" = "style=\"color: #C586C0; \""
"keyword.directive" = "style=\"color: #569CD6; \""
"label" = "style=\"color: #569CD6; \""
"markup.bold" = "style=\"font-weight: bold; color: #569CD6; \""
"markup.heading" = "style=\"font-weight: bold; color: #569CD6; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #ce9178;\""
"markup.link.url" = "style=\"\""
"markup.list" = "style=\"color: #6796E6;\""
"markup.quote" = "style=\"color: #6A9955;\""
"markup.raw" = "style=\"color: #ce9178;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #4EC9B0; \""
"namespace" = "style=\"color: #4EC9B0; \""
"operator" = "style=\"color: #d4d4d4; \""
"punctuation" = "style=\"color: #d4d4d4; \""
"punctuation.delimiter" = "style=\"color: #d4d4d4; \""
"special" = "style=\"color: #d4d4d4; \""
"string" = "style=\"color: #ce9178; \""
"string.regexp" = "style=\"color: #d7ba7d; \""
"tag" = "style=\"color: #569CD6;\""
"type" = "style=\"color: #4EC9B0; \""
"type.builtin" = "style=\"color: #4EC9B0; \""
"type.enum.variant" = "style=\"color: #4FC1FF; \""
"variable" = "style=\"color: #9CDCFE; \""
"variable.builtin" = "style=\"color: #569CD6; \""
"variable.other.member" = "style=\"color: #9CDCFE; \""
"variable.parameter" = "style=\"color: #9CDCFE; \""
