"background" = "style=\"background-color: #0D0E16; \""
"attribute" = "style=\"color: #3679D8; \""
"comment" = "style=\"text-decoration: underline; color: #767676; \""
"comment.block" = "style=\"text-decoration: underline; color: #79D836; \""
"comment.block.documentation" = "style=\"text-decoration: underline; color: #79D836; \""
"constant" = "style=\"color: #8041D8; \""
"constant.numeric" = "style=\"color: #D85F00; \""
"constructor" = "style=\"color: #D83441; \""
"diff.delta" = "style=\"color: #3679D8; \""
"diff.minus" = "style=\"color: #D83441; \""
"diff.plus" = "style=\"color: #79D836; \""
"function" = "style=\"color: #D8B941; \""
"function.builtin" = "style=\"color: #3679D8; \""
"function.method" = "style=\"color: #ffffff; \""
"keyword" = "style=\"color: #D83441; \""
"label" = "style=\"color: #79D836; \""
"markup.bold" = "style=\"font-weight: bold; color: #D85F00; \""
"markup.heading" = "style=\"color: #D83441; \""
"markup.italic" = "style=\"text-decoration: underline; color: #8041D8; \""
"markup.link" = "style=\"color: #D85F00; \""
"markup.link.label" = "style=\"color: #79D836; \""
"markup.link.text" = "style=\"color: #D85F00; \""
"markup.link.url" = "style=\"color: #8041D8; \""
"markup.list" = "style=\"color: #D83441; \""
"markup.quote" = "style=\"text-decoration: underline; color: #79D836; \""
"markup.raw.block" = "style=\"color: #79D836; background-color: #585C6C; \""
"markup.raw.inline" = "style=\"color: #79D836; background-color: #585C6C; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ffffff; \""
"operator" = "style=\"color: #3679D8; \""
"punctuation.bracket" = "style=\"color: #3679D8; \""
"punctuation.delimiter" = "style=\"font-weight: bold; color: #ffffff; \""
"special" = "style=\"color: #D85F00; \""
"string" = "style=\"color: #79D836; \""
"tag" = "style=\"color: #36D8BD; \""
"type" = "style=\"color: #3679D8; \""
"variable" = "style=\"color: #36D8BD; \""
"variable.parameter" = "style=\"color: #ffffff; \""
