"constant.numeric" = "class=\"constant numeric\" style=\"color: #D85F00; \""
"function" = "class=\"function\" style=\"color: #D8B941; \""
"markup.list" = "class=\"markup list\" style=\"color: #D83441; \""
"markup.link.label" = "class=\"markup link label\" style=\"color: #79D836; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #3679D8; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #79D836; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #3679D8; \""
"keyword" = "class=\"keyword\" style=\"color: #D83441; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #3679D8; \""
"string" = "class=\"string\" style=\"color: #79D836; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #79D836; background-color: #585C6C; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #ffffff; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"font-weight: bold; color: #ffffff; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #8041D8; \""
"operator" = "class=\"operator\" style=\"color: #3679D8; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #79D836; \""
"special" = "class=\"special\" style=\"color: #D85F00; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #8041D8; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #0D0E16; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #D85F00; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #767676; \""
"tag" = "class=\"tag\" style=\"color: #36D8BD; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #D83441; \""
"constructor" = "class=\"constructor\" style=\"color: #D83441; \""
"variable" = "class=\"variable\" style=\"color: #36D8BD; \""
"text" = "class=\"text\" style=\"color: #C3DBE5; \""
"module" = "class=\"module\" style=\"color: #ffffff; \""
"markup.link" = "class=\"markup link\" style=\"color: #D85F00; \""
"comment.block" = "class=\"comment block\" style=\"font-style: italic; color: #79D836; \""
"constant" = "class=\"constant\" style=\"color: #8041D8; \""
"function.method" = "class=\"function method\" style=\"color: #ffffff; \""
"type" = "class=\"type\" style=\"color: #3679D8; \""
"attribute" = "class=\"attribute\" style=\"color: #3679D8; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #D83441; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #79D836; background-color: #585C6C; \""
"namespace" = "class=\"namespace\" style=\"color: #ffffff; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-style: italic; color: #79D836; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #D85F00; \""
"label" = "class=\"label\" style=\"color: #79D836; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
