"annotation" = "style=\"color: #f8f8f2; \""
"attribute" = "style=\"text-decoration: underline; color: #50fa7b; \""
"comment" = "style=\"color: #6272A4; \""
"comment.block" = "style=\"color: #6272A4; \""
"comment.block.documentation" = "style=\"color: #6272A4; \""
"comment.line" = "style=\"color: #6272A4; \""
"constant" = "style=\"color: #BD93F9; \""
"constant.builtin" = "style=\"color: #BD93F9; \""
"constant.builtin.boolean" = "style=\"color: #BD93F9; \""
"constant.character" = "style=\"color: #8be9fd; \""
"constant.character.escape" = "style=\"color: #ff79c6; \""
"constant.macro" = "style=\"color: #BD93F9; \""
"constant.numeric" = "style=\"color: #BD93F9; \""
"constructor" = "style=\"color: #BD93F9; \""
"definition" = "style=\"color: #8be9fd; \""
"diff.delta" = "style=\"color: #ffb86c; \""
"diff.minus" = "style=\"color: #ff5555; \""
"diff.plus" = "style=\"color: #50fa7b; \""
"function" = "style=\"color: #50fa7b; \""
"function.builtin" = "style=\"color: #50fa7b; \""
"function.call" = "style=\"color: #50fa7b; \""
"function.macro" = "style=\"color: #BD93F9; \""
"function.method" = "style=\"color: #50fa7b; \""
"keyword" = "style=\"color: #ff79c6; \""
"keyword.control.conditional" = "style=\"color: #ff79c6; \""
"keyword.control.exception" = "style=\"color: #BD93F9; \""
"keyword.control.import" = "style=\"color: #ff79c6; \""
"keyword.control.repeat" = "style=\"color: #ff79c6; \""
"keyword.directive" = "style=\"color: #50fa7b; \""
"keyword.function" = "style=\"color: #ff79c6; \""
"keyword.operator" = "style=\"color: #ff79c6; \""
"keyword.return" = "style=\"color: #ff79c6; \""
"keyword.storage" = "style=\"color: #ff79c6; \""
"keyword.storage.modifier" = "style=\"color: #ff79c6; \""
"keyword.storage.type" = "style=\"text-decoration: underline; color: #8be9fd; \""
"label" = "style=\"color: #8be9fd; \""
"markup.bold" = "style=\"font-weight: bold; color: #ffb86c; \""
"markup.heading" = "style=\"font-weight: bold; color: #BD93F9; \""
"markup.italic" = "style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.link.text" = "style=\"color: #ff79c6; \""
"markup.link.url" = "style=\"color: #8be9fd; \""
"markup.list" = "style=\"color: #8be9fd; \""
"markup.quote" = "style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.raw" = "style=\"color: #f8f8f2; \""
"markup.strikethrough" = "style=\"\""
"punctuation" = "style=\"color: #f8f8f2; \""
"punctuation.bracket" = "style=\"color: #f8f8f2; \""
"punctuation.delimiter" = "style=\"color: #f8f8f2; \""
"punctuation.special" = "style=\"color: #ff79c6; \""
"special" = "style=\"color: #ff79c6; \""
"string" = "style=\"color: #f1fa8c; \""
"string.regexp" = "style=\"color: #ff5555; \""
"string.special" = "style=\"color: #ffb86c; \""
"string.symbol" = "style=\"color: #f1fa8c; \""
"tag" = "style=\"color: #ff79c6; \""
"tag.attribute" = "style=\"color: #BD93F9; \""
"tag.delimiter" = "style=\"color: #f8f8f2; \""
"type" = "style=\"text-decoration: underline; color: #8be9fd; \""
"type.builtin" = "style=\"color: #8be9fd; \""
"type.enum.variant" = "style=\"text-decoration: underline; color: #f8f8f2; \""
"variable" = "style=\"color: #f8f8f2; \""
"variable.builtin" = "style=\"text-decoration: underline; color: #BD93F9; \""
"variable.other" = "style=\"color: #f8f8f2; \""
"variable.other.member" = "style=\"color: #f8f8f2; \""
"variable.parameter" = "style=\"text-decoration: underline; color: #ffb86c; \""
