"tag.attribute" = "class=\"tag attribute\" style=\"color: #BD93F9; \""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"color: #ff79c6; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #BD93F9; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #BD93F9; \""
"function" = "class=\"function\" style=\"color: #50fa7b; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #ff79c6; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #f8f8f2; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #ff79c6; \""
"markup.list" = "class=\"markup list\" style=\"color: #8be9fd; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #50fa7b; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #f1fa8c; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #f8f8f2; \""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"font-style: italic; color: #8be9fd; \""
"constant.macro" = "class=\"constant macro\" style=\"color: #BD93F9; \""
"keyword" = "class=\"keyword\" style=\"color: #ff79c6; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #ff79c6; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ffb86c; \""
"string" = "class=\"string\" style=\"color: #f1fa8c; \""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #ffb86c; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #f8f8f2; \""
"keyword.return" = "class=\"keyword return\" style=\"color: #ff79c6; \""
"variable.builtin" = "class=\"variable builtin\" style=\"font-style: italic; color: #BD93F9; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #8be9fd; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ff79c6; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #50fa7b; \""
"operator" = "class=\"operator\" style=\"color: #ff79c6; \""
"annotation" = "class=\"annotation\" style=\"color: #f8f8f2; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #50fa7b; \""
"special" = "class=\"special\" style=\"color: #ff79c6; \""
"function.macro" = "class=\"function macro\" style=\"color: #BD93F9; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #f1fa8c; \""
"background" = "class=\"background\" style=\"background-color: #282A36; \""
"punctuation" = "class=\"punctuation\" style=\"color: #f8f8f2; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ff79c6; \""
"comment" = "class=\"comment\" style=\"color: #6272A4; \""
"tag" = "class=\"tag\" style=\"color: #ff79c6; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #f8f8f2; \""
"constant.character" = "class=\"constant character\" style=\"color: #8be9fd; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff5555; \""
"tag.delimiter" = "class=\"tag delimiter\" style=\"color: #f8f8f2; \""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"color: #ff79c6; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #8be9fd; \""
"constructor" = "class=\"constructor\" style=\"color: #BD93F9; \""
"variable" = "class=\"variable\" style=\"color: #f8f8f2; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"font-style: italic; color: #f8f8f2; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #ff79c6; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff5555; \""
"module" = "class=\"module\" style=\"color: #ff79c6; \""
"function.call" = "class=\"function call\" style=\"color: #50fa7b; \""
"comment.block" = "class=\"comment block\" style=\"color: #6272A4; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #ff79c6; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #BD93F9; \""
"constant" = "class=\"constant\" style=\"color: #BD93F9; \""
"string.special" = "class=\"string special\" style=\"color: #ffb86c; \""
"function.method" = "class=\"function method\" style=\"color: #50fa7b; \""
"definition" = "class=\"definition\" style=\"color: #8be9fd; \""
"type" = "class=\"type\" style=\"font-style: italic; color: #8be9fd; \""
"variable.other" = "class=\"variable other\" style=\"color: #f8f8f2; \""
"attribute" = "class=\"attribute\" style=\"font-style: italic; color: #50fa7b; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #BD93F9; \""
"string.symbol" = "class=\"string symbol\" style=\"color: #f1fa8c; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #BD93F9; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"color: #ff79c6; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"color: #6272A4; \""
"comment.line" = "class=\"comment line\" style=\"color: #6272A4; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ffb86c; \""
"label" = "class=\"label\" style=\"color: #8be9fd; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
