"background" = "style=\"background-color: #0e1419; \""
"comment" = "style=\"color: #6272a4; \""
"constant" = "style=\"color: #bd93f9; \""
"constant.character.escape" = "style=\"color: #ff79c6; \""
"diff.delta" = "style=\"color: #ffb86c; \""
"diff.minus" = "style=\"color: #ff5555; \""
"diff.plus" = "style=\"color: #50fa7b; \""
"function" = "style=\"color: #50fa7b; \""
"keyword" = "style=\"color: #ff79c6; \""
"markup.bold" = "style=\"font-weight: bold; color: #ffb86c; \""
"markup.heading" = "style=\"font-weight: bold; color: #bd93f9; \""
"markup.italic" = "style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.link.text" = "style=\"color: #ff79c6;\""
"markup.link.url" = "style=\"color: #8be9fd;\""
"markup.list" = "style=\"color: #8be9fd;\""
"markup.quote" = "style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.raw" = "style=\"color: #f8f8f2; \""
"markup.strikethrough" = "style=\"\""
"operator" = "style=\"color: #ff79c6; \""
"punctuation" = "style=\"color: #f8f8f2; \""
"string" = "style=\"color: #f1fa8c; \""
"string.regexp" = "style=\"color: #ff5555; \""
"tag" = "style=\"color: #ff79c6; \""
"type" = "style=\"text-decoration: underline; color: #8be9fd; \""
"type.enum.variant" = "style=\"text-decoration: underline; color: #f8f8f2; \""
"variable" = "style=\"color: #f8f8f2; \""
"variable.builtin" = "style=\"text-decoration: underline; color: #8be9fd; \""
"variable.parameter" = "style=\"text-decoration: underline; color: #ffb86c; \""
