"background" = "class=\"background\" style=\"background-color: #0e1419; \""
"comment" = "class=\"comment\" style=\"color: #6272a4; \""
"constant" = "class=\"constant\" style=\"color: #bd93f9; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ff79c6; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ffb86c; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff5555; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #50fa7b; \""
"function" = "class=\"function\" style=\"color: #50fa7b; \""
"keyword" = "class=\"keyword\" style=\"color: #ff79c6; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ffb86c; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #bd93f9; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ff79c6;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #8be9fd;\""
"markup.list" = "class=\"markup list\" style=\"color: #8be9fd;\""
"markup.quote" = "class=\"markup quote\" style=\"text-decoration: underline; color: #f1fa8c; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #f8f8f2; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #ff79c6; \""
"operator" = "class=\"operator\" style=\"color: #ff79c6; \""
"punctuation" = "class=\"punctuation\" style=\"color: #f8f8f2; \""
"string" = "class=\"string\" style=\"color: #f1fa8c; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff5555; \""
"tag" = "class=\"tag\" style=\"color: #ff79c6; \""
"type" = "class=\"type\" style=\"text-decoration: underline; color: #8be9fd; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"text-decoration: underline; color: #f8f8f2; \""
"variable" = "class=\"variable\" style=\"color: #f8f8f2; \""
"variable.builtin" = "class=\"variable builtin\" style=\"text-decoration: underline; color: #8be9fd; \""
"variable.parameter" = "class=\"variable parameter\" style=\"text-decoration: underline; color: #ffb86c; \""
