"background" = "style=\"background-color: #ffffff; \""
"attribute" = "style=\"color: #483d8b; \""
"comment" = "style=\"color: #b22222; \""
"constant" = "style=\"color: #008b8b; \""
"constant.builtin" = "style=\"color: #483d8b; \""
"constructor" = "style=\"color: #228b22; \""
"diff.delta" = "style=\"color: #ee9a00; \""
"diff.minus" = "style=\"color: #ee0000; \""
"diff.plus" = "style=\"color: #00cd00; \""
"function" = "style=\"color: #0000ff; \""
"function.builtin" = "style=\"color: #483d8b; \""
"function.call" = "style=\"color: #0000ff; \""
"function.macro" = "style=\"color: #483d8b; \""
"function.special" = "style=\"color: #483d8b; \""
"keyword" = "style=\"color: #a020f0; \""
"label" = "style=\"color: #483d8b; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #ffd700; \""
"markup.heading.1" = "style=\"color: #0000ff; \""
"markup.heading.2" = "style=\"color: #a0522d; \""
"markup.heading.3" = "style=\"color: #a020f0; \""
"markup.heading.4" = "style=\"color: #b22222; \""
"markup.heading.5" = "style=\"color: #228b22; \""
"markup.heading.6" = "style=\"color: #008b8b; \""
"markup.heading.marker" = "style=\"color: #999999; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #3a5fcd; \""
"markup.link.url" = "style=\"color: #3a5fcd; \""
"markup.list" = "style=\"color: #000000; \""
"markup.quote" = "style=\"color: #999999; \""
"markup.raw.block" = "style=\"color: #008b8b; \""
"markup.raw.inline" = "style=\"color: #008b8b; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #008b8b; \""
"namespace" = "style=\"color: #008b8b; \""
"operator" = "style=\"color: #a020f0; \""
"punctuation" = "style=\"color: #000000; \""
"special" = "style=\"color: #0000ff; \""
"string" = "style=\"color: #8b2252; \""
"string.special" = "style=\"font-weight: bold; color: #8b2252; \""
"tag" = "style=\"color: #0000ff; \""
"type" = "style=\"color: #228b22; \""
"type.builtin" = "style=\"color: #483d8b; \""
"variable" = "style=\"color: #a0522d; \""
"variable.builtin" = "style=\"color: #483d8b; \""
"variable.parameter" = "style=\"color: #a0522d; \""
