"function" = "class=\"function\" style=\"color: #0000ff; \""
"markup.list" = "class=\"markup list\" style=\"color: #000000; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #483d8b; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #999999; \""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #b22222; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #228b22; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #a020f0; \""
"keyword" = "class=\"keyword\" style=\"color: #a020f0; \""
"function.special" = "class=\"function special\" style=\"color: #483d8b; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ee9a00; \""
"string" = "class=\"string\" style=\"color: #8b2252; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #008b8b; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #a0522d; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #483d8b; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #3a5fcd; \""
"operator" = "class=\"operator\" style=\"color: #a020f0; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #00cd00; \""
"special" = "class=\"special\" style=\"color: #0000ff; \""
"function.macro" = "class=\"function macro\" style=\"color: #483d8b; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #ffffff; \""
"punctuation" = "class=\"punctuation\" style=\"color: #000000; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #3a5fcd; \""
"comment" = "class=\"comment\" style=\"color: #b22222; \""
"tag" = "class=\"tag\" style=\"color: #0000ff; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ee0000; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #a0522d; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #483d8b; \""
"constructor" = "class=\"constructor\" style=\"color: #228b22; \""
"variable" = "class=\"variable\" style=\"color: #a0522d; \""
"module" = "class=\"module\" style=\"color: #008b8b; \""
"function.call" = "class=\"function call\" style=\"color: #0000ff; \""
"constant" = "class=\"constant\" style=\"color: #008b8b; \""
"string.special" = "class=\"string special\" style=\"font-weight: bold; color: #8b2252; \""
"type" = "class=\"type\" style=\"color: #228b22; \""
"attribute" = "class=\"attribute\" style=\"color: #483d8b; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #008b8b; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #483d8b; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #0000ff; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #ffd700; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #008b8b; \""
"namespace" = "class=\"namespace\" style=\"color: #008b8b; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #999999; \""
"label" = "class=\"label\" style=\"color: #483d8b; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
