"constant.numeric" = "class=\"constant numeric\" style=\"color: #df69ba;\""
"function" = "class=\"function\" style=\"color: #8da101;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #3a94c5;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #f57d26;\""
"markup.list" = "class=\"markup list\" style=\"color: #f85552;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #f57d26;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #939f91;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #8da101; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #5c6a72;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #3a94c5; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #dfa000; \""
"keyword" = "class=\"keyword\" style=\"color: #f85552;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #3a94c5;\""
"string" = "class=\"string\" style=\"color: #35a77c;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #35a77c;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #5c6a72;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #939f91;\""
"variable.builtin" = "class=\"variable builtin\" style=\"font-style: italic; color: #df69ba; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #3a94c5; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #8da101;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #df69ba;\""
"operator" = "class=\"operator\" style=\"color: #f57d26; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #8da101;\""
"special" = "class=\"special\" style=\"color: #3a94c5;\""
"function.macro" = "class=\"function macro\" style=\"color: #8da101;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #fdf6e3; \""
"punctuation" = "class=\"punctuation\" style=\"color: #829181;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #df69ba;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #939f91; \""
"tag" = "class=\"tag\" style=\"color: #f57d26;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f85552;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #f57d26; \""
"constructor" = "class=\"constructor\" style=\"color: #8da101;\""
"variable" = "class=\"variable\" style=\"color: #5c6a72;\""
"text" = "class=\"text\" style=\"color: #5c6a72; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #f85552;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #8da101;\""
"module" = "class=\"module\" style=\"color: #dfa000; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #3a94c5;\""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #df69ba;\""
"constant" = "class=\"constant\" style=\"color: #5c6a72;\""
"string.special" = "class=\"string special\" style=\"color: #dfa000;\""
"type" = "class=\"type\" style=\"color: #dfa000;\""
"attribute" = "class=\"attribute\" style=\"font-style: italic; color: #df69ba; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #df69ba; \""
"constant.builtin" = "class=\"constant builtin\" style=\"font-style: italic; color: #df69ba; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #f85552; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #8da101;\""
"namespace" = "class=\"namespace\" style=\"font-style: italic; color: #dfa000; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #939f91;\""
"label" = "class=\"label\" style=\"color: #f57d26;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
