"attribute" = "style=\"text-decoration: underline; color: #df69ba; \""
"comment" = "style=\"text-decoration: underline; color: #939f91; \""
"constant" = "style=\"color: #5c6a72;\""
"constant.builtin" = "style=\"text-decoration: underline; color: #df69ba; \""
"constant.builtin.boolean" = "style=\"color: #df69ba;\""
"constant.character.escape" = "style=\"color: #8da101;\""
"constant.numeric" = "style=\"color: #df69ba;\""
"constructor" = "style=\"color: #8da101;\""
"diff.delta" = "style=\"color: #3a94c5;\""
"diff.minus" = "style=\"color: #f85552;\""
"diff.plus" = "style=\"color: #8da101;\""
"function" = "style=\"color: #8da101;\""
"function.macro" = "style=\"color: #8da101;\""
"keyword" = "style=\"color: #f85552;\""
"keyword.directive" = "style=\"color: #df69ba;\""
"keyword.operator" = "style=\"color: #f57d26;\""
"keyword.storage" = "style=\"color: #f85552;\""
"label" = "style=\"color: #f57d26;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #f85552; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #f57d26; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #dfa000; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #8da101; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #3a94c5; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #df69ba; \""
"markup.heading.marker" = "style=\"color: #939f91;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #f57d26;\""
"markup.link.text" = "style=\"color: #df69ba;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #3a94c5; \""
"markup.list" = "style=\"color: #f85552;\""
"markup.quote" = "style=\"color: #939f91;\""
"markup.raw.block" = "style=\"color: #35a77c;\""
"markup.raw.inline" = "style=\"color: #8da101;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #dfa000;\""
"namespace" = "style=\"text-decoration: underline; color: #dfa000; \""
"operator" = "style=\"color: #f57d26;\""
"punctuation" = "style=\"color: #829181;\""
"punctuation.bracket" = "style=\"color: #5c6a72;\""
"punctuation.delimiter" = "style=\"color: #939f91;\""
"punctuation.special" = "style=\"color: #3a94c5;\""
"special" = "style=\"color: #3a94c5;\""
"string" = "style=\"color: #35a77c;\""
"string.regexp" = "style=\"color: #8da101;\""
"string.special" = "style=\"color: #dfa000;\""
"tag" = "style=\"color: #f57d26;\""
"type" = "style=\"color: #dfa000;\""
"variable" = "style=\"color: #5c6a72;\""
"variable.builtin" = "style=\"text-decoration: underline; color: #df69ba; \""
"variable.other.member" = "style=\"color: #3a94c5;\""
"variable.parameter" = "style=\"color: #5c6a72;\""
