"constant.numeric.float" = "class=\"constant numeric float\" style=\"color: #2d3437; \""
"string.escape" = "class=\"string escape\" style=\"color: #67b0e8; \""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"color: #f4d67a; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #2d3437; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #e5c76b; \""
"function" = "class=\"function\" style=\"color: #e57474; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #67b0e8; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #e57474; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #71baf2; \""
"markup.list" = "class=\"markup list\" style=\"color: #6cbfbf; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #67cbe7; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #e5c76b; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #b3b9b8; \""
"keyword" = "class=\"keyword\" style=\"color: #67b0e8; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #ef7e7e; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #c47fd5; \""
"string" = "class=\"string\" style=\"color: #8ccf7e; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #e57474; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #b3b9b8; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #67b0e8; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #8ccf7e; \""
"operator" = "class=\"operator\" style=\"color: #b3b9b8; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #67b0e8; \""
"special" = "class=\"special\" style=\"color: #ef7e7e; \""
"function.macro" = "class=\"function macro\" style=\"color: #8ccf7e; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #e5c76b; \""
"background" = "class=\"background\" style=\"background-color: #141b1e; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #2d3437; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #404749; \""
"tag" = "class=\"tag\" style=\"color: #67b0e8; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #6cbfbf; \""
"constant.character" = "class=\"constant character\" style=\"color: #67b0e8; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #e57474; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #e5c76b; \""
"constructor" = "class=\"constructor\" style=\"color: #67b0e8; \""
"variable" = "class=\"variable\" style=\"color: #b3b9b8; \""
"module" = "class=\"module\" style=\"color: #ef7e7e; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #b3b9b8; \""
"string.regex" = "class=\"string regex\" style=\"color: #8ccf7e; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #6cbfbf; \""
"constant" = "class=\"constant\" style=\"color: #6cbfbf; \""
"string.special" = "class=\"string special\" style=\"color: #67b0e8; \""
"function.method" = "class=\"function method\" style=\"color: #71baf2; \""
"type" = "class=\"type\" style=\"color: #e5c76b; \""
"attribute" = "class=\"attribute\" style=\"color: #67b0e8; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #67b0e8; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #67b0e8; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"color: #e57474; \""
"string.special.symbol" = "class=\"string special symbol\" style=\"color: #e57474; \""
"namespace" = "class=\"namespace\" style=\"color: #ef7e7e; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #c47fd5; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #67b0e8; \""
"label" = "class=\"label\" style=\"color: #67b0e8; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
