"background" = "style=\"background-color: #141b1e; \""
"attribute" = "style=\"color: #67b0e8; \""
"comment" = "style=\"text-decoration: underline; color: #404749; \""
"constant" = "style=\"color: #6cbfbf; \""
"constant.builtin" = "style=\"color: #67b0e8; \""
"constant.builtin.boolean" = "style=\"color: #6cbfbf; \""
"constant.character" = "style=\"color: #67b0e8; \""
"constant.numeric" = "style=\"color: #e5c76b; \""
"constant.numeric.float" = "style=\"color: #2d3437; \""
"constructor" = "style=\"color: #67b0e8; \""
"diff.delta" = "style=\"color: #c47fd5; \""
"diff.minus" = "style=\"color: #e57474; \""
"diff.plus" = "style=\"color: #67b0e8; \""
"function" = "style=\"color: #e57474; \""
"function.builtin" = "style=\"color: #67cbe7; \""
"function.macro" = "style=\"color: #8ccf7e; \""
"function.method" = "style=\"color: #71baf2; \""
"keyword" = "style=\"color: #67b0e8; \""
"keyword.control.conditional" = "style=\"color: #e57474; \""
"keyword.control.exception" = "style=\"color: #2d3437; \""
"keyword.control.import" = "style=\"color: #ef7e7e; \""
"keyword.control.repeat" = "style=\"color: #f4d67a; \""
"keyword.control.return" = "style=\"color: #67b0e8; \""
"keyword.function" = "style=\"color: #67b0e8; \""
"keyword.operator" = "style=\"color: #71baf2; \""
"label" = "style=\"color: #67b0e8; \""
"markup.bold" = "style=\"font-weight: bold; color: #c47fd5; \""
"markup.heading" = "style=\"font-weight: bold; color: #67b0e8; \""
"markup.italic" = "style=\"text-decoration: underline; color: #e5c76b; \""
"markup.link.text" = "style=\"color: #2d3437; \""
"markup.link.url" = "style=\"color: #8ccf7e; \""
"markup.list" = "style=\"color: #6cbfbf; \""
"markup.quote" = "style=\"text-decoration: underline; color: #e5c76b; \""
"markup.raw" = "style=\"color: #6cbfbf; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ef7e7e; \""
"operator" = "style=\"color: #b3b9b8; \""
"punctuation.bracket" = "style=\"color: #b3b9b8; \""
"punctuation.delimiter" = "style=\"color: #b3b9b8; \""
"punctuation.special" = "style=\"color: #b3b9b8; \""
"special" = "style=\"color: #ef7e7e; \""
"string" = "style=\"color: #8ccf7e; \""
"string.escape" = "style=\"color: #67b0e8; \""
"string.regex" = "style=\"color: #8ccf7e; \""
"string.special" = "style=\"color: #67b0e8; \""
"string.special.symbol" = "style=\"color: #e57474; \""
"tag" = "style=\"color: #67b0e8; \""
"type" = "style=\"color: #e5c76b; \""
"type.builtin" = "style=\"color: #e5c76b; \""
"variable" = "style=\"color: #b3b9b8; \""
"variable.builtin" = "style=\"color: #67b0e8; \""
"variable.other.member" = "style=\"color: #e57474; \""
"variable.parameter" = "style=\"color: #e57474; \""
