"attribute" = "style=\"text-decoration: underline; color: #d699b6; \""
"comment" = "style=\"text-decoration: underline; color: #859289; \""
"constant" = "style=\"color: #d3c6aa;\""
"constant.builtin" = "style=\"text-decoration: underline; color: #d699b6; \""
"constant.builtin.boolean" = "style=\"color: #d699b6;\""
"constant.character.escape" = "style=\"color: #a7c080;\""
"constant.numeric" = "style=\"color: #d699b6;\""
"constructor" = "style=\"color: #a7c080;\""
"diff.delta" = "style=\"color: #7fbbb3;\""
"diff.minus" = "style=\"color: #e67e80;\""
"diff.plus" = "style=\"color: #a7c080;\""
"function" = "style=\"color: #a7c080;\""
"function.macro" = "style=\"color: #a7c080;\""
"keyword" = "style=\"color: #e67e80;\""
"keyword.directive" = "style=\"color: #d699b6;\""
"keyword.operator" = "style=\"color: #e69875;\""
"keyword.storage" = "style=\"color: #e67e80;\""
"label" = "style=\"color: #e69875;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #e67e80; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #e69875; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #dbbc7f; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #a7c080; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #7fbbb3; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #d699b6; \""
"markup.heading.marker" = "style=\"color: #859289;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #e69875;\""
"markup.link.text" = "style=\"color: #d699b6;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #7fbbb3; \""
"markup.list" = "style=\"color: #e67e80;\""
"markup.quote" = "style=\"color: #859289;\""
"markup.raw.block" = "style=\"color: #83c092;\""
"markup.raw.inline" = "style=\"color: #a7c080;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #dbbc7f;\""
"namespace" = "style=\"text-decoration: underline; color: #dbbc7f; \""
"operator" = "style=\"color: #e69875;\""
"punctuation" = "style=\"color: #9da9a0;\""
"punctuation.bracket" = "style=\"color: #d3c6aa;\""
"punctuation.delimiter" = "style=\"color: #859289;\""
"punctuation.special" = "style=\"color: #7fbbb3;\""
"special" = "style=\"color: #7fbbb3;\""
"string" = "style=\"color: #83c092;\""
"string.regexp" = "style=\"color: #a7c080;\""
"string.special" = "style=\"color: #dbbc7f;\""
"tag" = "style=\"color: #e69875;\""
"type" = "style=\"color: #dbbc7f;\""
"variable" = "style=\"color: #d3c6aa;\""
"variable.builtin" = "style=\"text-decoration: underline; color: #d699b6; \""
"variable.other.member" = "style=\"color: #7fbbb3;\""
"variable.parameter" = "style=\"color: #d3c6aa;\""
