"attribute" = "style=\"color: #fecdb2; \""
"comment" = "style=\"text-decoration: underline; color: #6F5D63; \""
"constant" = "style=\"color: #B1B695; \""
"diff.delta" = "style=\"color: #fecdb2; \""
"diff.minus" = "style=\"color: #e06b75; \""
"diff.plus" = "style=\"color: #B1B695; \""
"function" = "style=\"color: #ffa07a; \""
"function.macro" = "style=\"color: #D1D1E0; \""
"keyword" = "style=\"color: #D1D1E0; \""
"label" = "style=\"color: #B1B695; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #B1B695; \""
"markup.heading.marker" = "style=\"color: #6F5D63; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #F6B6C9; \""
"markup.link.url" = "style=\"color: #F6B6C9; \""
"markup.list" = "style=\"color: #D1D1E0; \""
"markup.quote" = "style=\"color: #6F5D63; \""
"markup.raw" = "style=\"color: #ffa07a; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #fecdb2; \""
"namespace" = "style=\"color: #fecdb2; \""
"operator" = "style=\"color: #D1D1E0; \""
"punctuation" = "style=\"color: #fecdb2; \""
"string" = "style=\"color: #B1B695; \""
"tag" = "style=\"color: #B1B695; \""
"type" = "style=\"color: #F6B6C9; \""
"variable" = "style=\"color: #fecdb2; \""
"variable.builtin" = "style=\"color: #F6B6C9; \""
