"attribute" = "class=\"attribute\" style=\"color: #fecdb2; \""
"background" = "class=\"background\" style=\"background-color: #2b292d; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #6F5D63; \""
"constant" = "class=\"constant\" style=\"color: #B1B695; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #fecdb2; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #e06b75; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #B1B695; \""
"function" = "class=\"function\" style=\"color: #ffa07a; \""
"function.macro" = "class=\"function macro\" style=\"color: #D1D1E0; \""
"keyword" = "class=\"keyword\" style=\"color: #D1D1E0; \""
"label" = "class=\"label\" style=\"color: #B1B695; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #B1B695; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #6F5D63; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #F6B6C9; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #F6B6C9; \""
"markup.list" = "class=\"markup list\" style=\"color: #D1D1E0; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #6F5D63; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #ffa07a; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #fecdb2; \""
"namespace" = "class=\"namespace\" style=\"color: #fecdb2; \""
"operator" = "class=\"operator\" style=\"color: #D1D1E0; \""
"punctuation" = "class=\"punctuation\" style=\"color: #fecdb2; \""
"string" = "class=\"string\" style=\"color: #B1B695; \""
"tag" = "class=\"tag\" style=\"color: #B1B695; \""
"type" = "class=\"type\" style=\"color: #F6B6C9; \""
"variable" = "class=\"variable\" style=\"color: #fecdb2; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #F6B6C9; \""
