"background" = "style=\"background-color: #f7f3ee; \""
"attribute" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"comment" = "style=\"text-decoration: underline; color: #b9a992; \""
"comment.block.documentation" = "style=\"color: #93836c; \""
"constant" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"constructor" = "style=\"color: #605a52; \""
"diff.delta" = "style=\"color: #f2a60d; \""
"diff.minus" = "style=\"color: #ff1414; \""
"diff.plus" = "style=\"color: #2db448; \""
"function" = "style=\"font-weight: bold; color: #605a52; \""
"keyword" = "style=\"color: #614c61; background-color: #f1ddf1; \""
"label" = "style=\"font-weight: bold; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #614c61; background-color: #f1ddf1; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.link.text" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.link.url" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.list" = "style=\"color: #614c61; background-color: #f1ddf1; \""
"markup.quote" = "style=\"color: #465953; background-color: #d2ebe3; \""
"markup.raw" = "style=\"color: #5b5143; background-color: #f7e0c3; \""
"markup.raw.block" = "style=\"color: #5b5143; background-color: #f7e0c3; \""
"markup.raw.inline" = "style=\"color: #5b5143; background-color: #f7e0c3; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #465953; background-color: #d2ebe3; \""
"operator" = "style=\"color: #605a52; \""
"punctuation.bracket" = "style=\"font-weight: bold; \""
"special" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"string" = "style=\"color: #525643; background-color: #e2e9c1; \""
"type" = "style=\"color: #605a52; \""
"variable" = "style=\"color: #605a52; \""
"variable.parameter" = "style=\"color: #4c5361; background-color: #dde4f2; \""
