"attribute" = "style=\"color: #4c5361; background-color: #dde4f2; \""
"comment" = "style=\"text-decoration: underline; color: #b9a992; \""
"comment.block" = "style=\"\""
"comment.line" = "style=\"\""
