"function" = "class=\"function\" style=\"font-weight: bold; color: #605a52; \""
"markup.list" = "class=\"markup list\" style=\"color: #614c61; background-color: #f1ddf1; \""
"markup.link.label" = "class=\"markup link label\" style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #465953; background-color: #d2ebe3; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"font-weight: bold; \""
"keyword" = "class=\"keyword\" style=\"color: #614c61; background-color: #f1ddf1; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #f2a60d; \""
"string" = "class=\"string\" style=\"color: #525643; background-color: #e2e9c1; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #5b5143; background-color: #f7e0c3; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #4c5361; background-color: #dde4f2; \""
"operator" = "class=\"operator\" style=\"color: #605a52; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #2db448; \""
"special" = "class=\"special\" style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #f7f3ee; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #4c5361; background-color: #dde4f2; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #b9a992; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #5b5143; background-color: #f7e0c3; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff1414; \""
"constructor" = "class=\"constructor\" style=\"color: #605a52; \""
"variable" = "class=\"variable\" style=\"color: #605a52; \""
"module" = "class=\"module\" style=\"color: #465953; \""
"constant" = "class=\"constant\" style=\"color: #4c5361; background-color: #dde4f2; \""
"type" = "class=\"type\" style=\"color: #605a52; \""
"attribute" = "class=\"attribute\" style=\"color: #4c5361; background-color: #dde4f2; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #614c61; background-color: #f1ddf1; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #5b5143; background-color: #f7e0c3; \""
"namespace" = "class=\"namespace\" style=\"color: #465953; background-color: #d2ebe3; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"color: #93836c; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"font-weight: bold; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
