"attribute" = "style=\"color: #A8CC7C;\""
"comment" = "style=\"color: #898989;\""
"constant" = "style=\"color: #AF9CFF;\""
"constant.builtin.boolean" = "style=\"color: #82D2CE;\""
"constant.character" = "style=\"color: #EBC88D;\""
"constant.character.escape" = "style=\"color: #82D2CE;\""
"constant.numeric" = "style=\"color: #EBC88D;\""
"constructor" = "style=\"color: #EBC88D;\""
"diff.delta" = "style=\"color: #1a85f6;\""
"diff.minus" = "style=\"color: #ce364d;\""
"diff.plus" = "style=\"color: #4ca988;\""
"function" = "style=\"color: #EBC88D;\""
"function.builtin" = "style=\"color: #A8CC7C;\""
"function.declaration" = "style=\"color: #EFEFEF;\""
"function.macro" = "style=\"color: #A8CC7C;\""
"function.special" = "style=\"color: #A8CC7C;\""
"keyword" = "style=\"color: #82D2CE;\""
"label" = "style=\"color: #EBC88D;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #82D2CE; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #c07bf3;\""
"markup.link.text" = "style=\"color: #82D2CE;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #E394DC; \""
"markup.list" = "style=\"color: #E394DC;\""
"markup.list.numbered" = "style=\"color: #82D2CE;\""
"markup.list.unnumbered" = "style=\"color: #82D2CE;\""
"markup.quote" = "style=\"color: #E394DC;\""
"markup.raw" = "style=\"color: #E394DC;\""
"markup.raw.block" = "style=\"color: #EB83E2;\""
"markup.raw.inline" = "style=\"color: #82D2CE;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #87C3FF;\""
"special" = "style=\"color: #A8CC7C;\""
"string" = "style=\"color: #E394DC;\""
"string.regexp" = "style=\"color: #82D2CE;\""
"string.special" = "style=\"color: #EBC88D; \""
"tag" = "style=\"color: #87C3FF;\""
"type" = "style=\"color: #87C3FF;\""
"type.parameter" = "style=\"color: #ADD1DE;\""
"type.return" = "style=\"color: #ADD1DE;\""
"variable" = "style=\"color: #d1d1d1;\""
"variable.builtin" = "style=\"color: #CC7C8A; \""
"variable.other.member" = "style=\"color: #AF9CFF;\""
