"type.return" = "class=\"type return\" style=\"color: #ADD1DE;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #EBC88D;\""
"function" = "class=\"function\" style=\"color: #EBC88D;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #AF9CFF;\""
"markup.list" = "class=\"markup list\" style=\"color: #E394DC;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #c07bf3;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #A8CC7C;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #E394DC;\""
"keyword" = "class=\"keyword\" style=\"color: #82D2CE;\""
"function.special" = "class=\"function special\" style=\"color: #A8CC7C;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #1a85f6;\""
"string" = "class=\"string\" style=\"color: #E394DC;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #EB83E2;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #CC7C8A; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #E394DC; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #82D2CE;\""
"operator" = "class=\"operator\" style=\"\""
"function.declaration" = "class=\"function declaration\" style=\"color: #EFEFEF;\""
"diff.plus" = "class=\"diff plus\" style=\"color: #4ca988;\""
"special" = "class=\"special\" style=\"color: #A8CC7C;\""
"function.macro" = "class=\"function macro\" style=\"color: #A8CC7C;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #181818; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #82D2CE;\""
"comment" = "class=\"comment\" style=\"color: #898989;\""
"tag" = "class=\"tag\" style=\"color: #87C3FF;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #E394DC;\""
"constant.character" = "class=\"constant character\" style=\"color: #EBC88D;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ce364d;\""
"constructor" = "class=\"constructor\" style=\"color: #EBC88D;\""
"variable" = "class=\"variable\" style=\"color: #d1d1d1;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #82D2CE;\""
"module" = "class=\"module\" style=\"color: #87C3FF; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #82D2CE;\""
"constant" = "class=\"constant\" style=\"color: #AF9CFF;\""
"string.special" = "class=\"string special\" style=\"color: #EBC88D; \""
"type" = "class=\"type\" style=\"color: #87C3FF;\""
"attribute" = "class=\"attribute\" style=\"color: #A8CC7C;\""
"type.parameter" = "class=\"type parameter\" style=\"color: #ADD1DE;\""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #82D2CE;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #82D2CE; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #82D2CE;\""
"namespace" = "class=\"namespace\" style=\"color: #87C3FF;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #82D2CE;\""
"label" = "class=\"label\" style=\"color: #EBC88D;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
