"attribute" = "style=\"color: #c9d1d9;\""
"comment" = "style=\"color: #8b949e;\""
"constant" = "style=\"color: #79c0ff;\""
"constant.builtin" = "style=\"color: #79c0ff;\""
"constant.character.escape" = "style=\"color: #79c0ff;\""
"constant.numeric" = "style=\"color: #79c0ff;\""
"constructor" = "style=\"color: #d2a8ff;\""
"diff.delta" = "style=\"color: #d29922;\""
"diff.minus" = "style=\"color: #8b949e;\""
"diff.plus" = "style=\"color: #ec8e2c;\""
"function" = "style=\"color: #d2a8ff;\""
"function.macro" = "style=\"color: #d2a8ff;\""
"keyword" = "style=\"color: #ec8e2c;\""
"keyword.directive" = "style=\"color: #ec8e2c;\""
"label" = "style=\"color: #ec8e2c;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #79c0ff;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #a5d6ff; \""
"markup.link.url" = "style=\"\""
"markup.raw" = "style=\"color: #79c0ff;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #fdac54;\""
"operator" = "style=\"color: #a5d6ff;\""
"punctuation" = "style=\"color: #c9d1d9;\""
"punctuation.delimiter" = "style=\"color: #c9d1d9;\""
"special" = "style=\"color: #a5d6ff;\""
"string" = "style=\"color: #a5d6ff;\""
"tag" = "style=\"color: #a5d6ff;\""
"type" = "style=\"color: #fdac54;\""
"type.builtin" = "style=\"color: #79c0ff;\""
"variable" = "style=\"color: #c9d1d9;\""
"variable.builtin" = "style=\"color: #ec8e2c;\""
"variable.other.member" = "style=\"color: #a5d6ff;\""
"variable.parameter" = "style=\"color: #fdac54;\""
