"constant.numeric" = "class=\"constant numeric\" style=\"color: #91cbff;\""
"function" = "class=\"function\" style=\"color: #dbb7ff;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #addcff;\""
"keyword" = "class=\"keyword\" style=\"color: #ff9492;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #f0b72f;\""
"string" = "class=\"string\" style=\"color: #addcff;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #ffb757;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #f0f3f6;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ff9492;\""
"markup.link.url" = "class=\"markup link url\" style=\"\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #91cbff;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ff9492;\""
"operator" = "class=\"operator\" style=\"color: #addcff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #26cd4d;\""
"special" = "class=\"special\" style=\"color: #addcff;\""
"function.macro" = "class=\"function macro\" style=\"color: #dbb7ff;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #0a0c10; \""
"punctuation" = "class=\"punctuation\" style=\"color: #f0f3f6;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #addcff; \""
"comment" = "class=\"comment\" style=\"color: #f0f3f6;\""
"tag" = "class=\"tag\" style=\"color: #72f088;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #91cbff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff6a69;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #91cbff;\""
"constructor" = "class=\"constructor\" style=\"color: #dbb7ff;\""
"variable" = "class=\"variable\" style=\"color: #f0f3f6;\""
"module" = "class=\"module\" style=\"color: #ffb757; \""
"constant" = "class=\"constant\" style=\"color: #91cbff;\""
"type" = "class=\"type\" style=\"color: #ffb757;\""
"attribute" = "class=\"attribute\" style=\"color: #f0f3f6;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #91cbff;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #91cbff;\""
"namespace" = "class=\"namespace\" style=\"color: #ffb757;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #ff9492;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
