"constant.numeric" = "class=\"constant numeric\" style=\"color: #79c0ff;\""
"function" = "class=\"function\" style=\"color: #d2a8ff;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #a5d6ff;\""
"keyword" = "class=\"keyword\" style=\"color: #ec8e2c;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #d29922;\""
"string" = "class=\"string\" style=\"color: #a5d6ff;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #fdac54;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #c9d1d9;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ec8e2c;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #79c0ff;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ec8e2c;\""
"operator" = "class=\"operator\" style=\"color: #a5d6ff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #ec8e2c;\""
"special" = "class=\"special\" style=\"color: #a5d6ff;\""
"function.macro" = "class=\"function macro\" style=\"color: #d2a8ff;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #0d1117; \""
"punctuation" = "class=\"punctuation\" style=\"color: #c9d1d9;\""
"markup.link.text" = "class=\"markup link text\" style=\"text-decoration: underline; color: #a5d6ff; \""
"comment" = "class=\"comment\" style=\"color: #8b949e;\""
"tag" = "class=\"tag\" style=\"color: #a5d6ff;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #79c0ff;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #8b949e;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #79c0ff;\""
"constructor" = "class=\"constructor\" style=\"color: #d2a8ff;\""
"variable" = "class=\"variable\" style=\"color: #c9d1d9;\""
"text" = "class=\"text\" style=\"color: #8b949e; \""
"module" = "class=\"module\" style=\"color: #fdac54; \""
"constant" = "class=\"constant\" style=\"color: #79c0ff;\""
"type" = "class=\"type\" style=\"color: #fdac54;\""
"attribute" = "class=\"attribute\" style=\"color: #c9d1d9;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #79c0ff;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #79c0ff;\""
"namespace" = "class=\"namespace\" style=\"color: #fdac54;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #ec8e2c;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
