"constant.numeric" = "class=\"constant numeric\" style=\"color: #023b95;\""
"function" = "class=\"function\" style=\"color: #622cbc;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #032563;\""
"keyword" = "class=\"keyword\" style=\"color: #a0111f;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #744500;\""
"string" = "class=\"string\" style=\"color: #032563;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #702c00;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #0e1116;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #a0111f;\""
"markup.link.url" = "class=\"markup link url\" style=\"\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #023b95;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #a0111f;\""
"operator" = "class=\"operator\" style=\"color: #032563; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #055d20;\""
"special" = "class=\"special\" style=\"color: #032563;\""
"function.macro" = "class=\"function macro\" style=\"color: #622cbc;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #ffffff; \""
"punctuation" = "class=\"punctuation\" style=\"color: #0e1116;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #032563; \""
"comment" = "class=\"comment\" style=\"color: #0e1116;\""
"tag" = "class=\"tag\" style=\"color: #024c1a;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #023b95;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #a0111f;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #023b95;\""
"constructor" = "class=\"constructor\" style=\"color: #622cbc;\""
"variable" = "class=\"variable\" style=\"color: #0e1116;\""
"module" = "class=\"module\" style=\"color: #702c00; \""
"constant" = "class=\"constant\" style=\"color: #023b95;\""
"type" = "class=\"type\" style=\"color: #702c00;\""
"attribute" = "class=\"attribute\" style=\"color: #0e1116;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #023b95;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #023b95;\""
"namespace" = "class=\"namespace\" style=\"color: #702c00;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #a0111f;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
