"constant.numeric" = "class=\"constant numeric\" style=\"color: #0550ae;\""
"function" = "class=\"function\" style=\"color: #8250df;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #0a3069;\""
"keyword" = "class=\"keyword\" style=\"color: #cf222e;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #9a6700;\""
"string" = "class=\"string\" style=\"color: #0a3069;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #a40e26;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #24292f;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #cf222e;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #0550ae;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #cf222e;\""
"operator" = "class=\"operator\" style=\"color: #0a3069; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #cf222e;\""
"special" = "class=\"special\" style=\"color: #0a3069;\""
"function.macro" = "class=\"function macro\" style=\"color: #8250df;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #ffffff; \""
"punctuation" = "class=\"punctuation\" style=\"color: #24292f;\""
"markup.link.text" = "class=\"markup link text\" style=\"text-decoration: underline; color: #0a3069; \""
"comment" = "class=\"comment\" style=\"color: #57606a;\""
"tag" = "class=\"tag\" style=\"color: #0550ae;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #0550ae;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #6e7781;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #0550ae;\""
"constructor" = "class=\"constructor\" style=\"color: #8250df;\""
"variable" = "class=\"variable\" style=\"color: #24292f;\""
"text" = "class=\"text\" style=\"color: #57606a; \""
"module" = "class=\"module\" style=\"color: #a40e26; \""
"constant" = "class=\"constant\" style=\"color: #0550ae;\""
"type" = "class=\"type\" style=\"color: #a40e26;\""
"attribute" = "class=\"attribute\" style=\"color: #24292f;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #0550ae;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #0550ae;\""
"namespace" = "class=\"namespace\" style=\"color: #a40e26;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #cf222e;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
