"attribute" = "style=\"color: #24292f;\""
"comment" = "style=\"color: #57606a;\""
"constant" = "style=\"color: #0550ae;\""
"constant.builtin" = "style=\"color: #0550ae;\""
"constant.character.escape" = "style=\"color: #0550ae;\""
"constant.numeric" = "style=\"color: #0550ae;\""
"constructor" = "style=\"color: #8250df;\""
"diff.delta" = "style=\"color: #9a6700;\""
"diff.minus" = "style=\"color: #cf222e;\""
"diff.plus" = "style=\"color: #1a7f37;\""
"function" = "style=\"color: #8250df;\""
"function.macro" = "style=\"color: #8250df;\""
"keyword" = "style=\"color: #cf222e;\""
"keyword.directive" = "style=\"color: #cf222e;\""
"label" = "style=\"color: #cf222e;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #0550ae;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #0a3069; \""
"markup.link.url" = "style=\"\""
"markup.raw" = "style=\"color: #0550ae;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #953800;\""
"operator" = "style=\"color: #0a3069;\""
"punctuation" = "style=\"color: #24292f;\""
"punctuation.delimiter" = "style=\"color: #24292f;\""
"special" = "style=\"color: #0a3069;\""
"string" = "style=\"color: #0a3069;\""
"tag" = "style=\"color: #116329;\""
"type" = "style=\"color: #953800;\""
"type.builtin" = "style=\"color: #0550ae;\""
"variable" = "style=\"color: #24292f;\""
"variable.builtin" = "style=\"color: #cf222e;\""
"variable.other.member" = "style=\"color: #0a3069;\""
"variable.parameter" = "style=\"color: #953800;\""
