"background" = "style=\"background-color: #22272e; \""
"attribute" = "style=\"color: #adbac7;\""
"comment" = "style=\"color: #768390;\""
"constant" = "style=\"color: #6cb6ff;\""
"constant.builtin" = "style=\"color: #6cb6ff;\""
"constant.character.escape" = "style=\"color: #6cb6ff;\""
"constant.numeric" = "style=\"color: #6cb6ff;\""
"constructor" = "style=\"color: #dcbdfb;\""
"diff.delta" = "style=\"color: #c69026;\""
"diff.minus" = "style=\"color: #e5534b;\""
"diff.plus" = "style=\"color: #57ab5a;\""
"function" = "style=\"color: #dcbdfb;\""
"function.macro" = "style=\"color: #dcbdfb;\""
"keyword" = "style=\"color: #f47067;\""
"keyword.directive" = "style=\"color: #f47067;\""
"label" = "style=\"color: #f47067;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #6cb6ff;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #96d0ff; \""
"markup.link.url" = "style=\"\""
"markup.raw" = "style=\"color: #6cb6ff;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #f69d50;\""
"operator" = "style=\"color: #96d0ff;\""
"punctuation" = "style=\"color: #adbac7;\""
"punctuation.delimiter" = "style=\"color: #adbac7;\""
"special" = "style=\"color: #96d0ff;\""
"string" = "style=\"color: #96d0ff;\""
"tag" = "style=\"color: #8ddb8c;\""
"type" = "style=\"color: #f69d50;\""
"type.builtin" = "style=\"color: #6cb6ff;\""
"variable" = "style=\"color: #adbac7;\""
"variable.builtin" = "style=\"color: #f47067;\""
"variable.other.member" = "style=\"color: #96d0ff;\""
"variable.parameter" = "style=\"color: #f69d50;\""
