"background" = "style=\"background-color: #0a0c10; \""
"attribute" = "style=\"color: #f0f3f6;\""
"comment" = "style=\"color: #f0f3f6;\""
"constant" = "style=\"color: #91cbff;\""
"constant.builtin" = "style=\"color: #91cbff;\""
"constant.character.escape" = "style=\"color: #91cbff;\""
"constant.numeric" = "style=\"color: #91cbff;\""
"constructor" = "style=\"color: #dbb7ff;\""
"diff.delta" = "style=\"color: #f0b72f;\""
"diff.minus" = "style=\"color: #ff6a69;\""
"diff.plus" = "style=\"color: #26cd4d;\""
"function" = "style=\"color: #dbb7ff;\""
"function.macro" = "style=\"color: #dbb7ff;\""
"keyword" = "style=\"color: #ff9492;\""
"keyword.directive" = "style=\"color: #ff9492;\""
"label" = "style=\"color: #ff9492;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #91cbff;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #addcff; \""
"markup.link.url" = "style=\"\""
"markup.raw" = "style=\"color: #91cbff;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ffb757;\""
"operator" = "style=\"color: #addcff;\""
"punctuation" = "style=\"color: #f0f3f6;\""
"punctuation.delimiter" = "style=\"color: #f0f3f6;\""
"special" = "style=\"color: #addcff;\""
"string" = "style=\"color: #addcff;\""
"tag" = "style=\"color: #72f088;\""
"type" = "style=\"color: #ffb757;\""
"type.builtin" = "style=\"color: #91cbff;\""
"variable" = "style=\"color: #f0f3f6;\""
"variable.builtin" = "style=\"color: #ff9492;\""
"variable.other.member" = "style=\"color: #addcff;\""
"variable.parameter" = "style=\"color: #ffb757;\""
