"background" = "style=\"background-color: #ffffff; \""
"attribute" = "style=\"color: #0e1116;\""
"comment" = "style=\"color: #0e1116;\""
"constant" = "style=\"color: #023b95;\""
"constant.builtin" = "style=\"color: #023b95;\""
"constant.character.escape" = "style=\"color: #023b95;\""
"constant.numeric" = "style=\"color: #023b95;\""
"constructor" = "style=\"color: #622cbc;\""
"diff.delta" = "style=\"color: #744500;\""
"diff.minus" = "style=\"color: #a0111f;\""
"diff.plus" = "style=\"color: #055d20;\""
"function" = "style=\"color: #622cbc;\""
"function.macro" = "style=\"color: #622cbc;\""
"keyword" = "style=\"color: #a0111f;\""
"keyword.directive" = "style=\"color: #a0111f;\""
"label" = "style=\"color: #a0111f;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #023b95;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #032563; \""
"markup.link.url" = "style=\"\""
"markup.raw" = "style=\"color: #023b95;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #702c00;\""
"operator" = "style=\"color: #032563;\""
"punctuation" = "style=\"color: #0e1116;\""
"punctuation.delimiter" = "style=\"color: #0e1116;\""
"special" = "style=\"color: #032563;\""
"string" = "style=\"color: #032563;\""
"tag" = "style=\"color: #024c1a;\""
"type" = "style=\"color: #702c00;\""
"type.builtin" = "style=\"color: #023b95;\""
"variable" = "style=\"color: #0e1116;\""
"variable.builtin" = "style=\"color: #a0111f;\""
"variable.other.member" = "style=\"color: #032563;\""
"variable.parameter" = "style=\"color: #702c00;\""
