"background" = "style=\"background-color: #1d2021; \""
"attribute" = "style=\"color: ;\""
"comment" = "style=\"text-decoration: underline; color: ; \""
"constant" = "style=\"color: ; \""
"constant.builtin" = "style=\"font-weight: bold; color: ; \""
"constant.character.escape" = "style=\"font-weight: bold; color: ; \""
"constant.numeric" = "style=\"color: ;\""
"constructor" = "style=\"font-weight: bold; color: ; \""
"diff.delta" = "style=\"color: ;\""
"diff.minus" = "style=\"color: ;\""
"diff.plus" = "style=\"color: ;\""
"function" = "style=\"font-weight: bold; color: ; \""
"function.builtin" = "style=\"color: ;\""
"function.macro" = "style=\"color: ;\""
"keyword" = "style=\"color: ; \""
"keyword.directive" = "style=\"color: ;\""
"label" = "style=\"color: ;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.raw" = "style=\"color: ;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: ;\""
"namespace" = "style=\"color: ;\""
"operator" = "style=\"color: ;\""
"punctuation" = "style=\"color: ;\""
"punctuation.delimiter" = "style=\"color: ;\""
"special" = "style=\"color: ;\""
"string" = "style=\"color: ;\""
"tag" = "style=\"color: ;\""
"type" = "style=\"color: ;\""
"type.builtin" = "style=\"color: ;\""
"variable" = "style=\"color: ;\""
"variable.builtin" = "style=\"color: ;\""
"variable.other.member" = "style=\"color: ;\""
"variable.parameter" = "style=\"color: ;\""
