"background" = "style=\"background-color: #fbf1c7; \""
"attribute" = "style=\"color: #427b58;\""
"comment" = "style=\"text-decoration: underline; color: ; \""
"constant" = "style=\"color: #8f3f71; \""
"constant.builtin" = "style=\"font-weight: bold; color: #8f3f71; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #504945; \""
"constant.numeric" = "style=\"color: #8f3f71;\""
"constructor" = "style=\"font-weight: bold; color: #8f3f71; \""
"diff.delta" = "style=\"color: #af3a03;\""
"diff.minus" = "style=\"color: #9d0006;\""
"diff.plus" = "style=\"color: #79740e;\""
"function" = "style=\"font-weight: bold; color: #79740e; \""
"function.builtin" = "style=\"color: #b57614;\""
"function.macro" = "style=\"color: #427b58;\""
"keyword" = "style=\"color: #9d0006; \""
"keyword.directive" = "style=\"color: ;\""
"label" = "style=\"color: #427b58;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #427b58;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #9d0006;\""
"markup.link.url" = "style=\"color: #79740e; \""
"markup.raw" = "style=\"color: #9d0006;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #427b58;\""
"namespace" = "style=\"color: #427b58;\""
"operator" = "style=\"color: #8f3f71;\""
"punctuation" = "style=\"color: #af3a03;\""
"punctuation.delimiter" = "style=\"color: #af3a03;\""
"special" = "style=\"color: ;\""
"string" = "style=\"color: #79740e;\""
"tag" = "style=\"color: #9d0006;\""
"type" = "style=\"color: #b57614;\""
"type.builtin" = "style=\"color: #b57614;\""
"variable" = "style=\"color: #3c3836;\""
"variable.builtin" = "style=\"color: #af3a03;\""
"variable.other.member" = "style=\"color: #076678;\""
"variable.parameter" = "style=\"color: #504945;\""
