"constant.numeric" = "class=\"constant numeric\" style=\"color: #8f3f71;\""
"function" = "class=\"function\" style=\"font-weight: bold; color: #79740e; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #076678;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #b57614;\""
"keyword" = "class=\"keyword\" style=\"color: #9d0006; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #af3a03;\""
"string" = "class=\"string\" style=\"color: #79740e;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #504945;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #af3a03;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #af3a03;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #79740e; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #504945; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #cc241d;\""
"operator" = "class=\"operator\" style=\"color: #8f3f71; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #79740e;\""
"special" = "class=\"special\" style=\"color: #b16286;\""
"function.macro" = "class=\"function macro\" style=\"color: #427b58;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #fbf1c7; \""
"punctuation" = "class=\"punctuation\" style=\"color: #af3a03;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #9d0006;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #928374; \""
"tag" = "class=\"tag\" style=\"color: #9d0006;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #9d0006;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #9d0006;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #b57614;\""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #8f3f71; \""
"variable" = "class=\"variable\" style=\"color: #3c3836;\""
"module" = "class=\"module\" style=\"color: #427b58; \""
"constant" = "class=\"constant\" style=\"color: #8f3f71; \""
"type" = "class=\"type\" style=\"color: #b57614;\""
"attribute" = "class=\"attribute\" style=\"color: #427b58;\""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #8f3f71; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #427b58;\""
"namespace" = "class=\"namespace\" style=\"color: #427b58;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #427b58;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
