"constant.numeric" = "class=\"constant numeric\" style=\"color: #d3869b;\""
"function" = "class=\"function\" style=\"font-weight: bold; color: #b8bb26; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #83a598;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #fabd2f;\""
"keyword" = "class=\"keyword\" style=\"color: #fb4934; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #fe8019;\""
"string" = "class=\"string\" style=\"color: #b8bb26;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #d5c4a1;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #fe8019;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #fe8019;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #b8bb26; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #d5c4a1; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #cc241d;\""
"operator" = "class=\"operator\" style=\"color: #d3869b; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #b8bb26;\""
"special" = "class=\"special\" style=\"color: #b16286;\""
"function.macro" = "class=\"function macro\" style=\"color: #8ec07c;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #1d2021; \""
"punctuation" = "class=\"punctuation\" style=\"color: #fe8019;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #fb4934;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #928374; \""
"tag" = "class=\"tag\" style=\"color: #fb4934;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #fb4934;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #fb4934;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #fabd2f;\""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #d3869b; \""
"variable" = "class=\"variable\" style=\"color: #ebdbb2;\""
"module" = "class=\"module\" style=\"color: #8ec07c; \""
"constant" = "class=\"constant\" style=\"color: #d3869b; \""
"type" = "class=\"type\" style=\"color: #fabd2f;\""
"attribute" = "class=\"attribute\" style=\"color: #8ec07c;\""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #d3869b; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #8ec07c;\""
"namespace" = "class=\"namespace\" style=\"color: #8ec07c;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #8ec07c;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
