"attribute" = "style=\"color: #8ec07c;\""
"comment" = "style=\"text-decoration: underline; color: #928374; \""
"constant" = "style=\"color: #d3869b; \""
"constant.builtin" = "style=\"font-weight: bold; color: #d3869b; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #d5c4a1; \""
"constant.numeric" = "style=\"color: #d3869b;\""
"constructor" = "style=\"font-weight: bold; color: #d3869b; \""
"diff.delta" = "style=\"color: #fe8019;\""
"diff.minus" = "style=\"color: #fb4934;\""
"diff.plus" = "style=\"color: #b8bb26;\""
"function" = "style=\"font-weight: bold; color: #b8bb26; \""
"function.builtin" = "style=\"color: #fabd2f;\""
"function.macro" = "style=\"color: #8ec07c;\""
"keyword" = "style=\"color: #fb4934; \""
"keyword.directive" = "style=\"color: #cc241d;\""
"label" = "style=\"color: #8ec07c;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #8ec07c;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #fb4934;\""
"markup.link.url" = "style=\"color: #b8bb26; \""
"markup.raw" = "style=\"color: #fb4934;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #8ec07c;\""
"namespace" = "style=\"color: #8ec07c;\""
"operator" = "style=\"color: #d3869b;\""
"punctuation" = "style=\"color: #fe8019;\""
"punctuation.delimiter" = "style=\"color: #fe8019;\""
"special" = "style=\"color: #b16286;\""
"string" = "style=\"color: #b8bb26;\""
"tag" = "style=\"color: #fb4934;\""
"type" = "style=\"color: #fabd2f;\""
"type.builtin" = "style=\"color: #fabd2f;\""
"variable" = "style=\"color: #ebdbb2;\""
"variable.builtin" = "style=\"color: #fe8019;\""
"variable.other.member" = "style=\"color: #83a598;\""
"variable.parameter" = "style=\"color: #d5c4a1;\""
