"background" = "class=\"background\" style=\"background-color: #000000; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #bd5173; \""
"constant" = "class=\"constant\" style=\"color: #f7b90c; \""
"constructor" = "class=\"constructor\" style=\"color: #009669; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ff8f40; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #c32101; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #00ff80; \""
"function" = "class=\"function\" style=\"font-weight: bold; color: #00ff80; \""
"keyword" = "class=\"keyword\" style=\"color: #009669; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #009669; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #bd5173; \""
"label" = "class=\"label\" style=\"color: #cecd19; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #f7b90c; \""
"markup.link.label" = "class=\"markup link label\" style=\"color: #009669; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #cecd19; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #32c9fa; \""
"markup.list" = "class=\"markup list\" style=\"color: #cecd19; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #cecd19; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #ff8f40; background-color: #000000; \""
"module" = "class=\"module\" style=\"color: #f7b90c; \""
"namespace" = "class=\"namespace\" style=\"color: #f7b90c; \""
"operator" = "class=\"operator\" style=\"color: #f7b90c; \""
"punctuation" = "class=\"punctuation\" style=\"color: #009669; \""
"special" = "class=\"special\" style=\"color: #00ff80; \""
"string" = "class=\"string\" style=\"color: #32c9fa; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff8f40; \""
"string.special" = "class=\"string special\" style=\"color: #cecd19; \""
"tag" = "class=\"tag\" style=\"color: #32c9fa; \""
"type" = "class=\"type\" style=\"color: #32c9fa; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #32c9fa; \""
"variable" = "class=\"variable\" style=\"color: #186800; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f7b90c; \""
