"background" = "style=\"background-color: #000000; \""
"comment" = "style=\"text-decoration: underline; color: #bd5173; \""
"constant" = "style=\"color: #f7b90c; \""
"constructor" = "style=\"color: #009669; \""
"diff.delta" = "style=\"color: #ff8f40; \""
"diff.minus" = "style=\"color: #c32101; \""
"diff.plus" = "style=\"color: #00ff80; \""
"function" = "style=\"font-weight: bold; color: #00ff80; \""
"keyword" = "style=\"color: #009669; \""
"keyword.control" = "style=\"color: #009669; \""
"keyword.directive" = "style=\"color: #bd5173; \""
"label" = "style=\"color: #cecd19; \""
"markup.heading" = "style=\"color: #f7b90c; \""
"markup.link.label" = "style=\"color: #009669; \""
"markup.link.text" = "style=\"color: #cecd19; \""
"markup.link.url" = "style=\"color: #32c9fa; \""
"markup.list" = "style=\"color: #cecd19; \""
"markup.quote" = "style=\"color: #cecd19; \""
"markup.raw.block" = "style=\"color: #ff8f40; background-color: #000000; \""
"namespace" = "style=\"color: #f7b90c; \""
"operator" = "style=\"color: #f7b90c; \""
"punctuation" = "style=\"color: #009669; \""
"special" = "style=\"color: #00ff80; \""
"string" = "style=\"color: #32c9fa; \""
"string.regexp" = "style=\"color: #ff8f40; \""
"string.special" = "style=\"color: #cecd19; \""
"tag" = "style=\"color: #32c9fa; \""
"type" = "style=\"color: #32c9fa; \""
"type.builtin" = "style=\"color: #32c9fa; \""
"variable" = "style=\"color: #186800; \""
"variable.parameter" = "style=\"color: #f7b90c; \""
