"function" = "class=\"function\" style=\"color: #9db2b8; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #897dca; \""
"markup.list" = "class=\"markup list\" style=\"color: #61586f; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #61586f; \""
"keyword" = "class=\"keyword\" style=\"color: #878480; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #7b89a3; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #0078bd; \""
"string" = "class=\"string\" style=\"font-style: italic; color: #878480; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #61586f; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #7b89a3; \""
"operator" = "class=\"operator\" style=\"color: #7b89a3; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #87a800; \""
"special" = "class=\"special\" style=\"font-weight: bold; color: #897dca; \""
"function.macro" = "class=\"function macro\" style=\"color: #897dca; \""
"markup.italic" = "class=\"markup italic\" style=\"color: #61586f; \""
"background" = "class=\"background\" style=\"background-color: #121311; \""
"punctuation" = "class=\"punctuation\" style=\"color: #bcb6ba; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #61586f; \""
"comment" = "class=\"comment\" style=\"color: #9aacfe; \""
"tag" = "class=\"tag\" style=\"color: #61586f; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #0048bd; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #61586f; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff0900; \""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"color: #897dca; \""
"variable" = "class=\"variable\" style=\"color: #61586f; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #878480; \""
"module" = "class=\"module\" style=\"color: #878480; \""
"constant" = "class=\"constant\" style=\"color: #a0c7cf; \""
"function.method" = "class=\"function method\" style=\"color: #9db2b8; \""
"type" = "class=\"type\" style=\"font-weight: bold; color: #7b89a3; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #61586f; \""
"namespace" = "class=\"namespace\" style=\"font-weight: bold; color: #878480; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-style: italic; background-color: #0affa9; \""
"markup.bold" = "class=\"markup bold\" style=\"color: #61586f; \""
"label" = "class=\"label\" style=\"color: #61586f; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"color: #61586f; \""
