"background" = "style=\"background-color: #1b2a32; \""
"comment" = "style=\"color: #61bdd1; \""
"comment.block.documentation" = "style=\"text-decoration: underline; background-color: #234048; \""
"constant" = "style=\"color: #ffbf52; \""
"diff.delta" = "style=\"color: ; \""
"diff.delta.moved" = "style=\"color: ; \""
"diff.minus" = "style=\"color: ; \""
"diff.plus" = "style=\"color: ; \""
"function" = "style=\"color: #b0d4d8; \""
"function.macro" = "style=\"color: #eeac90; \""
"function.method" = "style=\"color: #b0d4d8; \""
"keyword" = "style=\"color: #8bb2b9; \""
"keyword.control" = "style=\"color: #b0bd9f; \""
"keyword.control.import" = "style=\"color: #b0bd9f; \""
"keyword.function" = "style=\"color: #eeac90; \""
"keyword.storage.modifier" = "style=\"color: #eeac90; \""
"label" = "style=\"color: #8792ab; \""
"markup.bold" = "style=\"color: #8792ab; \""
"markup.heading" = "style=\"color: #8792ab; \""
"markup.italic" = "style=\"color: #8792ab; \""
"markup.link.text" = "style=\"color: #8792ab; \""
"markup.link.url" = "style=\"color: #8792ab; \""
"markup.list" = "style=\"color: #8792ab; \""
"markup.quote" = "style=\"color: #8792ab; \""
"markup.raw" = "style=\"color: #8792ab; \""
"markup.strikethrough" = "style=\"color: #8792ab; \""
"namespace" = "style=\"font-weight: bold; color: #8bb2b9; \""
"operator" = "style=\"color: #b0bd9f; \""
"punctuation" = "style=\"color: #b3ccd0; \""
"special" = "style=\"font-weight: bold; color: #eeac90; \""
"string" = "style=\"text-decoration: underline; color: #8bb2b9; \""
"string.regexp" = "style=\"color: #8bb2b9; \""
"tag" = "style=\"color: #8792ab; \""
"type" = "style=\"font-weight: bold; color: #b0bd9f; \""
"variable" = "style=\"color: #8792ab; \""
