"background" = "style=\"background-color: #1d1e1b; \""
"comment" = "style=\"color: #d4d987; \""
"comment.block.documentation" = "style=\"text-decoration: underline; background-color: #234048; \""
"constant" = "style=\"color: #f78c5e; \""
"diff.delta" = "style=\"color: #0078bd; \""
"diff.delta.moved" = "style=\"color: #0048bd; \""
"diff.minus" = "style=\"color: #ff0900; \""
"diff.plus" = "style=\"color: #87a800; \""
"function" = "style=\"color: #c0d0ce; \""
"function.macro" = "style=\"color: #d85c60; \""
"function.method" = "style=\"color: #c0d0ce; \""
"keyword" = "style=\"color: #6e8789; \""
"keyword.control" = "style=\"color: #9bc1bb; \""
"keyword.control.import" = "style=\"color: #9bc1bb; \""
"keyword.function" = "style=\"color: #d85c60; \""
"keyword.storage.modifier" = "style=\"color: #d85c60; \""
"label" = "style=\"color: #656869; \""
"markup.bold" = "style=\"color: #656869; \""
"markup.heading" = "style=\"color: #656869; \""
"markup.italic" = "style=\"color: #656869; \""
"markup.link.text" = "style=\"color: #656869; \""
"markup.link.url" = "style=\"color: #656869; \""
"markup.list" = "style=\"color: #656869; \""
"markup.quote" = "style=\"color: #656869; \""
"markup.raw" = "style=\"color: #656869; \""
"markup.strikethrough" = "style=\"color: #656869; \""
"namespace" = "style=\"font-weight: bold; color: #6e8789; \""
"operator" = "style=\"color: #9bc1bb; \""
"punctuation" = "style=\"color: #b5c5c5; \""
"special" = "style=\"font-weight: bold; color: #d85c60; \""
"string" = "style=\"text-decoration: underline; color: #6e8789; \""
"string.regexp" = "style=\"color: #6e8789; \""
"tag" = "style=\"color: #656869; \""
"type" = "style=\"font-weight: bold; color: #9bc1bb; \""
"variable" = "style=\"color: #656869; \""
