"background" = "style=\"background-color: #121311; \""
"comment" = "style=\"color: #9aacfe; \""
"comment.block.documentation" = "style=\"text-decoration: underline; background-color: #0affa9; \""
"constant" = "style=\"color: #a0c7cf; \""
"diff.delta" = "style=\"color: ; \""
"diff.delta.moved" = "style=\"color: ; \""
"diff.minus" = "style=\"color: ; \""
"diff.plus" = "style=\"color: ; \""
"function" = "style=\"color: #9db2b8; \""
"function.macro" = "style=\"color: #897dca; \""
"function.method" = "style=\"color: #9db2b8; \""
"keyword" = "style=\"color: #878480; \""
"keyword.control" = "style=\"color: #7b89a3; \""
"keyword.control.import" = "style=\"color: #7b89a3; \""
"keyword.function" = "style=\"color: #897dca; \""
"keyword.storage.modifier" = "style=\"color: #897dca; \""
"label" = "style=\"color: #61586f; \""
"markup.bold" = "style=\"color: #61586f; \""
"markup.heading" = "style=\"color: #61586f; \""
"markup.italic" = "style=\"color: #61586f; \""
"markup.link.text" = "style=\"color: #61586f; \""
"markup.link.url" = "style=\"color: #61586f; \""
"markup.list" = "style=\"color: #61586f; \""
"markup.quote" = "style=\"color: #61586f; \""
"markup.raw" = "style=\"color: #61586f; \""
"markup.strikethrough" = "style=\"color: #61586f; \""
"namespace" = "style=\"font-weight: bold; color: #878480; \""
"operator" = "style=\"color: #7b89a3; \""
"punctuation" = "style=\"color: #bcb6ba; \""
"special" = "style=\"font-weight: bold; color: #897dca; \""
"string" = "style=\"text-decoration: underline; color: #878480; \""
"string.regexp" = "style=\"color: #878480; \""
"tag" = "style=\"color: #61586f; \""
"type" = "style=\"font-weight: bold; color: #7b89a3; \""
"variable" = "style=\"color: #61586f; \""
