"constant.numeric" = "class=\"constant numeric\" style=\"color: #D74E50;\""
"function" = "class=\"function\" style=\"font-weight: bold; color: #89BEB7; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #89BEB7;\""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #89BEB7;\""
"markup.quote" = "class=\"markup quote\" style=\"color: ;\""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #D74E50; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #D4A520;\""
"string" = "class=\"string\" style=\"color: #D74E50;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #89BEB7;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #C97270;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #D4A520;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: ; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #D74E50; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #6F873E;\""
"operator" = "class=\"operator\" style=\"color: #D74E50; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #839A53;\""
"special" = "class=\"special\" style=\"color: #D68482;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #D4A520; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: ; \""
"background" = "class=\"background\" style=\"background-color: #FFFCFD; \""
"punctuation" = "class=\"punctuation\" style=\"color: #C97270;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: ;\""
"comment" = "class=\"comment\" style=\"color: #A6B6CE;\""
"markup.raw" = "class=\"markup raw\" style=\"color: ;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #D74E50;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #839A53;\""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #839A53; \""
"variable" = "class=\"variable\" style=\"color: #A6B6CE;\""
"module" = "class=\"module\" style=\"color: #839A53; \""
"constant" = "class=\"constant\" style=\"color: #D4A520;\""
"type" = "class=\"type\" style=\"font-weight: bold; color: #A6B6CE; \""
"attribute" = "class=\"attribute\" style=\"color: #839A53;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #D4A520;\""
"markup.heading" = "class=\"markup heading\" style=\"color: ;\""
"namespace" = "class=\"namespace\" style=\"color: #839A53;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: ; \""
"label" = "class=\"label\" style=\"color: #D68482;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
