"attribute" = "style=\"color: #839A53;\""
"comment" = "style=\"color: #A6B6CE;\""
"constant" = "style=\"color: #D4A520;\""
"constant.builtin" = "style=\"color: #D4A520;\""
"constant.character.escape" = "style=\"font-weight: bold; color: #D74E50; \""
"constant.numeric" = "style=\"color: #D74E50;\""
"constructor" = "style=\"font-weight: bold; color: #839A53; \""
"diff.delta" = "style=\"color: #D4A520;\""
"diff.minus" = "style=\"color: #D74E50;\""
"diff.plus" = "style=\"color: #839A53;\""
"function" = "style=\"font-weight: bold; color: #89BEB7; \""
"function.builtin" = "style=\"color: #89BEB7;\""
"function.macro" = "style=\"font-weight: bold; color: #D4A520; \""
"keyword" = "style=\"font-weight: bold; color: #D74E50; \""
"keyword.directive" = "style=\"color: #6F873E;\""
"label" = "style=\"color: #D68482;\""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"color: ;\""
"markup.raw" = "style=\"color: ;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #839A53;\""
"namespace" = "style=\"color: #839A53;\""
"operator" = "style=\"font-weight: bold; color: #D74E50; \""
"punctuation" = "style=\"color: #C97270;\""
"punctuation.delimiter" = "style=\"color: #C97270;\""
"special" = "style=\"color: #D68482;\""
"string" = "style=\"color: #D74E50;\""
"type" = "style=\"font-weight: bold; color: #A6B6CE; \""
"type.builtin" = "style=\"color: #839A53;\""
"variable" = "style=\"color: #A6B6CE;\""
"variable.builtin" = "style=\"color: #D4A520;\""
"variable.other.member" = "style=\"color: #89BEB7;\""
"variable.parameter" = "style=\"color: #89BEB7;\""
