"attribute" = "style=\"color: #99ad6a;\""
"comment" = "style=\"color: #6d6d6d;\""
"constant" = "style=\"color: #cf6a4c;\""
"constant.builtin.boolean" = "style=\"color: #fad07a;\""
"constant.character" = "style=\"color: #fad07a;\""
"constant.character.escape" = "style=\"color: #902020;\""
"constant.numeric" = "style=\"color: #cf6a4c;\""
"constructor" = "style=\"color: #fad07a;\""
"diff.delta" = "style=\"color: #2197F3;\""
"diff.minus" = "style=\"color: #F44747;\""
"diff.plus" = "style=\"color: #5A9F81;\""
"function" = "style=\"color: #fad07a;\""
"function.builtin" = "style=\"color: #99ad6a;\""
"function.macro" = "style=\"color: #99ad6a;\""
"function.method" = "style=\"color: #fad07a;\""
"function.special" = "style=\"color: #99ad6a;\""
"keyword" = "style=\"color: #8197bf;\""
"keyword.control.exception" = "style=\"color: #a390f0;\""
"label" = "style=\"color: #fad07a;\""
"markup.bold" = "style=\"font-weight: bold; color: #ffffff; \""
"markup.heading" = "style=\"font-weight: bold; color: #8197bf; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #a390f0;\""
"markup.link.text" = "style=\"color: #8197bf;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #84A775; \""
"markup.list" = "style=\"color: #84A775;\""
"markup.list.numbered" = "style=\"color: #8197bf;\""
"markup.list.unnumbered" = "style=\"color: #8197bf;\""
"markup.quote" = "style=\"color: #84A775;\""
"markup.raw" = "style=\"color: #84A775;\""
"markup.raw.block" = "style=\"color: #84A775;\""
"markup.raw.inline" = "style=\"color: #8197bf;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #CDBEF0;\""
"operator" = "style=\"color: #CDBEF0;\""
"punctuation" = "style=\"color: #8197bf;\""
"special" = "style=\"color: #99ad6a;\""
"string" = "style=\"color: #84A775;\""
"string.regexp" = "style=\"color: #CDBEF0;\""
"string.special" = "style=\"color: #fad07a; \""
"tag" = "style=\"color: #8fbfdc;\""
"type" = "style=\"color: #8fbfdc;\""
"type.enum.variant" = "style=\"color: #a390f0;\""
"variable" = "style=\"color: #EBEBD8;\""
"variable.builtin" = "style=\"color: #84A775; \""
"variable.other.member" = "style=\"color: #CDBEF0;\""
"variable.parameter" = "style=\"color: #fad07a;\""
