"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #a390f0;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #cf6a4c;\""
"function" = "class=\"function\" style=\"color: #fad07a;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #CDBEF0;\""
"markup.list" = "class=\"markup list\" style=\"color: #84A775;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #a390f0;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #99ad6a;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #84A775;\""
"keyword" = "class=\"keyword\" style=\"color: #8197bf;\""
"function.special" = "class=\"function special\" style=\"color: #99ad6a;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #2197F3;\""
"string" = "class=\"string\" style=\"color: #84A775;\""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #84A775;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #fad07a;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #84A775; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #84A775; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #902020;\""
"operator" = "class=\"operator\" style=\"color: #CDBEF0; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #5A9F81;\""
"special" = "class=\"special\" style=\"color: #99ad6a;\""
"function.macro" = "class=\"function macro\" style=\"color: #99ad6a;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #151515; \""
"punctuation" = "class=\"punctuation\" style=\"color: #8197bf;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #8197bf;\""
"comment" = "class=\"comment\" style=\"color: #6d6d6d;\""
"tag" = "class=\"tag\" style=\"color: #8fbfdc;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #84A775;\""
"constant.character" = "class=\"constant character\" style=\"color: #fad07a;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #F44747;\""
"constructor" = "class=\"constructor\" style=\"color: #fad07a;\""
"variable" = "class=\"variable\" style=\"color: #EBEBD8;\""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #a390f0;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #CDBEF0;\""
"module" = "class=\"module\" style=\"color: #CDBEF0; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #fad07a;\""
"constant" = "class=\"constant\" style=\"color: #cf6a4c;\""
"string.special" = "class=\"string special\" style=\"color: #fad07a; \""
"function.method" = "class=\"function method\" style=\"color: #fad07a;\""
"type" = "class=\"type\" style=\"color: #8fbfdc;\""
"attribute" = "class=\"attribute\" style=\"color: #99ad6a;\""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #8197bf;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #8197bf; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #8197bf;\""
"namespace" = "class=\"namespace\" style=\"color: #CDBEF0;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ffffff; \""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #8197bf;\""
"label" = "class=\"label\" style=\"color: #fad07a;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
