"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #FF5D62;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #D27E99;\""
"function" = "class=\"function\" style=\"color: #7E9CD8;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #E6C384;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #FFA066;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #7FB4CA;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #938AA9;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #A3D4D5; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #957FB8; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #7AA89F; \""
"keyword" = "class=\"keyword\" style=\"color: #957FB8;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #DCA561;\""
"string" = "class=\"string\" style=\"color: #98BB6C;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #E6C384;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #E46876;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #7FB4CA; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #7FB4CA;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #FF5D62;\""
"operator" = "class=\"operator\" style=\"color: #C0A36E; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #76946A;\""
"special" = "class=\"special\" style=\"color: #FF5D62;\""
"function.macro" = "class=\"function macro\" style=\"color: #E46876;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #1F1F28; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9CABCA;\""
"string.special.url" = "class=\"string special url\" style=\"color: #7FB4CA;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #7E9CD8;\""
"comment" = "class=\"comment\" style=\"color: #727169;\""
"tag" = "class=\"tag\" style=\"color: #7AA89F;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #98BB6C;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #C34043;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #E6C384; \""
"constructor" = "class=\"constructor\" style=\"color: #7FB4CA;\""
"variable" = "class=\"variable\" style=\"color: #DCD7BA;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #C0A36E;\""
"module" = "class=\"module\" style=\"color: #FFA066; \""
"constant" = "class=\"constant\" style=\"color: #FFA066;\""
"type" = "class=\"type\" style=\"color: #7AA89F;\""
"attribute" = "class=\"attribute\" style=\"color: #E46876;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #938AA9; \""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #E46876;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #FFA066; \""
"string.special.symbol" = "class=\"string special symbol\" style=\"color: #957FB8;\""
"namespace" = "class=\"namespace\" style=\"color: #FFA066;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #FF5D62;\""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #D27E99;\""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #9CABCA;\""
"label" = "class=\"label\" style=\"color: #7FB4CA;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
