"background" = "style=\"background-color: #1F1F28; \""
"attribute" = "style=\"color: #E46876;\""
"comment" = "style=\"color: #727169;\""
"constant" = "style=\"color: #FFA066;\""
"constant.character.escape" = "style=\"color: #7FB4CA;\""
"constant.numeric" = "style=\"color: #D27E99;\""
"constructor" = "style=\"color: #7FB4CA;\""
"diff.delta" = "style=\"color: #DCA561;\""
"diff.minus" = "style=\"color: #C34043;\""
"diff.plus" = "style=\"color: #76946A;\""
"function" = "style=\"color: #7E9CD8;\""
"function.builtin" = "style=\"color: #7FB4CA;\""
"function.macro" = "style=\"color: #E46876;\""
"keyword" = "style=\"color: #957FB8;\""
"keyword.control.exception" = "style=\"color: #FF5D62;\""
"keyword.control.return" = "style=\"color: #FF5D62;\""
"keyword.directive" = "style=\"color: #FF5D62;\""
"label" = "style=\"color: #7FB4CA;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #FFA066; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #E6C384; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #7AA89F; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #A3D4D5; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #957FB8; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #938AA9; \""
"markup.heading.marker" = "style=\"color: #9CABCA;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"color: #FFA066;\""
"markup.link.text" = "style=\"color: #7E9CD8;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #7FB4CA; \""
"markup.list.numbered" = "style=\"color: #D27E99;\""
"markup.list.unnumbered" = "style=\"color: #E46876;\""
"markup.quote" = "style=\"color: #938AA9;\""
"markup.raw" = "style=\"color: #98BB6C;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #FFA066;\""
"operator" = "style=\"color: #C0A36E;\""
"punctuation" = "style=\"color: #9CABCA;\""
"special" = "style=\"color: #FF5D62;\""
"string" = "style=\"color: #98BB6C;\""
"string.regexp" = "style=\"color: #C0A36E;\""
"string.special.symbol" = "style=\"color: #957FB8;\""
"string.special.url" = "style=\"color: #7FB4CA;\""
"tag" = "style=\"color: #7AA89F;\""
"type" = "style=\"color: #7AA89F;\""
"variable" = "style=\"color: #DCD7BA;\""
"variable.builtin" = "style=\"color: #E46876;\""
"variable.other.member" = "style=\"color: #E6C384;\""
"variable.parameter" = "style=\"color: #E6C384;\""
