"attribute" = "style=\"color: #ab98b5;\""
"comment" = "style=\"text-decoration: underline; color: #545c5e; \""
"constant" = "style=\"color: #ab98b5; \""
"constant.builtin" = "style=\"color: #80bcb6; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #4d9391; \""
"constant.numeric" = "style=\"color: #80bcb6;\""
"constructor" = "style=\"color: #cd9575; \""
"diff.delta" = "style=\"color: #dbac66;\""
"diff.minus" = "style=\"color: #cd5c60;\""
"diff.plus" = "style=\"color: #6fb593;\""
"function" = "style=\"color: #80bcb6; \""
"function.builtin" = "style=\"color: #68f3ca;\""
"function.macro" = "style=\"color: #ab98b5;\""
"keyword" = "style=\"color: #4d9391; \""
"keyword.directive" = "style=\"color: #80bcb6;\""
"label" = "style=\"color: #ab98b5;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #80bcb6;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #68f3ca;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #dbac66; \""
"markup.raw" = "style=\"color: #68f3ca;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #80bcb6;\""
"namespace" = "style=\"color: #ab98b5;\""
"operator" = "style=\"color: #e6e6e8;\""
"punctuation" = "style=\"color: #e6e6e8;\""
"punctuation.delimiter" = "style=\"color: #e6e6e8;\""
"special" = "style=\"color: #ab98b5;\""
"string" = "style=\"color: #4d9391;\""
"tag" = "style=\"color: #7aaaa5;\""
"type" = "style=\"color: #cd9575;\""
"type.builtin" = "style=\"color: #80bcb6;\""
"variable" = "style=\"color: #968cc7;\""
"variable.builtin" = "style=\"color: #4d9391;\""
"variable.other.member" = "style=\"text-decoration: underline; color: #766884; \""
"variable.parameter" = "style=\"color: #968cc7;\""
