"constant.numeric" = "class=\"constant numeric\" style=\"color: #80bcb6;\""
"function" = "class=\"function\" style=\"color: #80bcb6; \""
"variable.other.member" = "class=\"variable other member\" style=\"font-style: italic; color: #766884; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #68f3ca;\""
"keyword" = "class=\"keyword\" style=\"color: #4d9391; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #dbac66;\""
"string" = "class=\"string\" style=\"color: #4d9391;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #968cc7;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #e6e6e8;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #4d9391;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #dbac66; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #4d9391; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #80bcb6;\""
"operator" = "class=\"operator\" style=\"color: #e6e6e8; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #6fb593;\""
"special" = "class=\"special\" style=\"color: #ab98b5;\""
"function.macro" = "class=\"function macro\" style=\"color: #ab98b5;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #18181b; \""
"punctuation" = "class=\"punctuation\" style=\"color: #e6e6e8;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #68f3ca;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #545c5e; \""
"tag" = "class=\"tag\" style=\"color: #7aaaa5;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #68f3ca;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #cd5c60;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #80bcb6;\""
"constructor" = "class=\"constructor\" style=\"color: #cd9575; \""
"variable" = "class=\"variable\" style=\"color: #968cc7;\""
"module" = "class=\"module\" style=\"color: #80bcb6; \""
"constant" = "class=\"constant\" style=\"color: #ab98b5; \""
"type" = "class=\"type\" style=\"color: #cd9575;\""
"attribute" = "class=\"attribute\" style=\"color: #ab98b5;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #80bcb6; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #80bcb6;\""
"namespace" = "class=\"namespace\" style=\"color: #ab98b5;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #ab98b5;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
