"attribute" = "style=\"color: #cea2ca;\""
"comment" = "style=\"text-decoration: underline; color: #635c4a; \""
"constant" = "style=\"color: #ef6787; \""
"constant.builtin" = "style=\"color: #53e6b5; \""
"constant.character.escape" = "style=\"color: #cea2ca;\""
"constant.numeric" = "style=\"color: #53e6b5;\""
"constructor" = "style=\"color: #eed891; \""
"diff.delta" = "style=\"color: #eed891;\""
"diff.minus" = "style=\"color: #e84c58;\""
"diff.plus" = "style=\"color: #91f368;\""
"function" = "style=\"color: #7ed7e6; \""
"function.builtin" = "style=\"color: #53e6b5;\""
"function.macro" = "style=\"color: #7ed7e6;\""
"keyword" = "style=\"color: #49bdb0; \""
"keyword.directive" = "style=\"color: #91f368;\""
"label" = "style=\"color: #9587dd;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #eed891;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #7ed7e6;\""
"markup.link.url" = "style=\"color: #ef6787; \""
"markup.raw" = "style=\"color: #ee7042;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #91f368;\""
"namespace" = "style=\"color: #ef6787;\""
"operator" = "style=\"color: #49bdb0;\""
"punctuation" = "style=\"color: #eee6d3;\""
"punctuation.delimiter" = "style=\"color: #eee6d3;\""
"special" = "style=\"color: #9587dd;\""
"string" = "style=\"color: #cea2ca;\""
"tag" = "style=\"color: #91f368;\""
"type" = "style=\"color: #eed891;\""
"type.builtin" = "style=\"color: #53e6b5;\""
"variable" = "style=\"color: #ef6787;\""
"variable.builtin" = "style=\"color: #49bdb0;\""
"variable.other.member" = "style=\"text-decoration: underline; color: #ee7042; \""
"variable.parameter" = "style=\"color: #ef6787;\""
