"constant.numeric" = "class=\"constant numeric\" style=\"color: #53e6b5;\""
"function" = "class=\"function\" style=\"color: #7ed7e6; \""
"variable.other.member" = "class=\"variable other member\" style=\"font-style: italic; color: #ee7042; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #53e6b5;\""
"keyword" = "class=\"keyword\" style=\"color: #49bdb0; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #eed891;\""
"string" = "class=\"string\" style=\"color: #cea2ca;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #ef6787;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #eee6d3;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #49bdb0;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #ef6787; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #cea2ca;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #91f368;\""
"operator" = "class=\"operator\" style=\"color: #49bdb0; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #91f368;\""
"special" = "class=\"special\" style=\"color: #9587dd;\""
"function.macro" = "class=\"function macro\" style=\"color: #7ed7e6;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #262221; \""
"punctuation" = "class=\"punctuation\" style=\"color: #eee6d3;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #7ed7e6;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #635c4a; \""
"tag" = "class=\"tag\" style=\"color: #91f368;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #ee7042;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e84c58;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #53e6b5;\""
"constructor" = "class=\"constructor\" style=\"color: #eed891; \""
"variable" = "class=\"variable\" style=\"color: #ef6787;\""
"module" = "class=\"module\" style=\"color: #91f368; \""
"constant" = "class=\"constant\" style=\"color: #ef6787; \""
"type" = "class=\"type\" style=\"color: #eed891;\""
"attribute" = "class=\"attribute\" style=\"color: #cea2ca;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #53e6b5; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #eed891;\""
"namespace" = "class=\"namespace\" style=\"color: #ef6787;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #9587dd;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
