"attribute" = "style=\"color: #845A84;\""
"comment" = "style=\"text-decoration: underline; color: #7c878a; \""
"constant" = "style=\"color: #845A84; \""
"constant.builtin" = "style=\"color: #4c7a90; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #13665f; \""
"constant.numeric" = "style=\"color: #4c7a90;\""
"constructor" = "style=\"color: #e36b3f; \""
"diff.delta" = "style=\"color: #dbac66;\""
"diff.minus" = "style=\"color: #e84c58;\""
"diff.plus" = "style=\"color: #39854c;\""
"function" = "style=\"color: #4c7a90; \""
"function.builtin" = "style=\"color: #6d46e3;\""
"function.macro" = "style=\"color: #845A84;\""
"keyword" = "style=\"color: #13665f; \""
"keyword.directive" = "style=\"color: #4c7a90;\""
"label" = "style=\"color: #845A84;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #6d46e3; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #3b84cc;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #3b84cc; \""
"markup.raw" = "style=\"color: #845A84;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #4c7a90;\""
"namespace" = "style=\"color: #845A84;\""
"operator" = "style=\"color: #383e3f;\""
"punctuation" = "style=\"color: #383e3f;\""
"punctuation.delimiter" = "style=\"color: #383e3f;\""
"special" = "style=\"color: #6d46e3;\""
"string" = "style=\"color: #39854c;\""
"tag" = "style=\"text-decoration: underline; color: #13665f; \""
"type" = "style=\"color: #e36b3f;\""
"type.builtin" = "style=\"color: #4c7a90;\""
"variable" = "style=\"color: #6d46e3;\""
"variable.builtin" = "style=\"color: #13665f;\""
"variable.other.member" = "style=\"text-decoration: underline; color: #845A84; \""
"variable.parameter" = "style=\"color: #845A84;\""
