"constant.numeric" = "class=\"constant numeric\" style=\"color: #4c7a90;\""
"function" = "class=\"function\" style=\"color: #4c7a90; \""
"variable.other.member" = "class=\"variable other member\" style=\"font-style: italic; color: #845A84; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #6d46e3;\""
"keyword" = "class=\"keyword\" style=\"color: #13665f; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #dbac66;\""
"string" = "class=\"string\" style=\"color: #39854c;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #845A84;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #383e3f;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #13665f;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #3b84cc; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #13665f; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #4c7a90;\""
"operator" = "class=\"operator\" style=\"color: #383e3f; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #39854c;\""
"special" = "class=\"special\" style=\"color: #6d46e3;\""
"function.macro" = "class=\"function macro\" style=\"color: #845A84;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #edeeeb; \""
"punctuation" = "class=\"punctuation\" style=\"color: #383e3f;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #3b84cc;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #7c878a; \""
"tag" = "class=\"tag\" style=\"font-style: italic; color: #13665f; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #845A84;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e84c58;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #4c7a90;\""
"constructor" = "class=\"constructor\" style=\"color: #e36b3f; \""
"variable" = "class=\"variable\" style=\"color: #6d46e3;\""
"module" = "class=\"module\" style=\"color: #4c7a90; \""
"constant" = "class=\"constant\" style=\"color: #845A84; \""
"type" = "class=\"type\" style=\"color: #e36b3f;\""
"attribute" = "class=\"attribute\" style=\"color: #845A84;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #4c7a90; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #6d46e3; \""
"namespace" = "class=\"namespace\" style=\"color: #845A84;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #845A84;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
