"function" = "class=\"function\" style=\"color: #82aaff;\""
"markup.list" = "class=\"markup list\" style=\"color: #c792ea;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #ffcb6b;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #82aaff;\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #c3e88d;\""
"keyword" = "class=\"keyword\" style=\"color: #c792ea;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #82aaff;\""
"string" = "class=\"string\" style=\"color: #c3e88d;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f78c6c; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ffcb6b;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #c3e88d; \""
"operator" = "class=\"operator\" style=\"color: #89ddff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #c3e88d;\""
"special" = "class=\"special\" style=\"color: #89ddff;\""
"function.macro" = "class=\"function macro\" style=\"color: #89ddff;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #292d3e; \""
"punctuation" = "class=\"punctuation\" style=\"color: #89ddff;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #82aaff;\""
"comment" = "class=\"comment\" style=\"color: #676e95; \""
"tag" = "class=\"tag\" style=\"color: #f07178;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #a6accd;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #f07178;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #f07178;\""
"constructor" = "class=\"constructor\" style=\"color: #82aaff;\""
"variable" = "class=\"variable\" style=\"color: #a6accd;\""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #89ddff;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #ffcb6b;\""
"module" = "class=\"module\" style=\"color: #ffcb6b; \""
"constant" = "class=\"constant\" style=\"color: #ffcb6b;\""
"string.special" = "class=\"string special\" style=\"color: #82aaff;\""
"type" = "class=\"type\" style=\"color: #c792ea;\""
"attribute" = "class=\"attribute\" style=\"color: #c792ea;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #f78c6c;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #89ddff;\""
"namespace" = "class=\"namespace\" style=\"color: #ffcb6b; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #89ddff; \""
"label" = "class=\"label\" style=\"color: #f78c6c;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
