"background" = "style=\"background-color: #212121; \""
"attribute" = "style=\"color: ;\""
"comment" = "style=\"color: #616161; \""
"constant" = "style=\"color: ;\""
"constructor" = "style=\"color: ;\""
"diff.delta" = "style=\"color: ;\""
"diff.minus" = "style=\"color: ;\""
"diff.plus" = "style=\"color: ;\""
"function" = "style=\"color: ;\""
"function.macro" = "style=\"color: ;\""
"keyword" = "style=\"color: ;\""
"keyword.storage" = "style=\"color: ;\""
"label" = "style=\"color: ;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: ;\""
"markup.heading.2" = "style=\"color: ;\""
"markup.heading.3" = "style=\"color: ;\""
"markup.heading.4" = "style=\"color: ;\""
"markup.heading.5" = "style=\"color: ;\""
"markup.heading.6" = "style=\"color: ;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: ; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ;\""
"markup.raw" = "style=\"color: #b0bec5;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: ; \""
"operator" = "style=\"color: ;\""
"punctuation" = "style=\"color: ;\""
"special" = "style=\"color: ;\""
"string" = "style=\"color: ;\""
"string.regexp" = "style=\"color: ;\""
"string.special" = "style=\"color: ;\""
"tag" = "style=\"color: ;\""
"type" = "style=\"color: ;\""
"variable" = "style=\"color: #b0bec5;\""
"variable.builtin" = "style=\"color: ;\""
"variable.parameter" = "style=\"color: ; \""
