"background" = "style=\"background-color: #0f111a; \""
"attribute" = "style=\"color: #c792ea;\""
"comment" = "style=\"color: #464b5d; \""
"constant" = "style=\"color: #ffcb6b;\""
"constructor" = "style=\"color: #82aaff;\""
"diff.delta" = "style=\"color: #82aaff;\""
"diff.minus" = "style=\"color: #f07178;\""
"diff.plus" = "style=\"color: #c3e88d;\""
"function" = "style=\"color: #82aaff;\""
"function.macro" = "style=\"color: #89ddff;\""
"keyword" = "style=\"color: #c792ea;\""
"keyword.storage" = "style=\"color: #89ddff;\""
"label" = "style=\"color: #f78c6c;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"color: #89ddff;\""
"markup.heading.2" = "style=\"color: #f07178;\""
"markup.heading.3" = "style=\"color: #c3e88d;\""
"markup.heading.4" = "style=\"color: #ffcb6b;\""
"markup.heading.5" = "style=\"color: #82aaff;\""
"markup.heading.6" = "style=\"color: #f78c6c;\""
"markup.heading.marker" = "style=\"font-weight: bold; color: #89ddff; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #82aaff;\""
"markup.link.url" = "style=\"color: #c3e88d; \""
"markup.list" = "style=\"color: #c792ea;\""
"markup.raw" = "style=\"color: #a6accd;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ffcb6b; \""
"operator" = "style=\"color: #89ddff;\""
"punctuation" = "style=\"color: #89ddff;\""
"special" = "style=\"color: #89ddff;\""
"string" = "style=\"color: #c3e88d;\""
"string.regexp" = "style=\"color: #ffcb6b;\""
"string.special" = "style=\"color: #82aaff;\""
"tag" = "style=\"color: #f07178;\""
"type" = "style=\"color: #c792ea;\""
"variable" = "style=\"color: #a6accd;\""
"variable.builtin" = "style=\"color: #ffcb6b;\""
"variable.parameter" = "style=\"color: #f78c6c; \""
