"background" = "class=\"background\" style=\"background-color: #1c1917; \""
"comment" = "class=\"comment\" style=\"color: #707035; \""
"constant" = "class=\"constant\" style=\"color: #b494af; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #b494af; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #d29595; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a49db9; \""
"function" = "class=\"function\" style=\"color: #a49db9; \""
"keyword" = "class=\"keyword\" style=\"color: #cbab8a; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #d29595; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #cbab8a; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #d29595; \""
"label" = "class=\"label\" style=\"color: #cbab8a; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #b494af; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #cbab8a; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #a49db9; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #707035; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #707035; \""
"markup.list" = "class=\"markup list\" style=\"color: #a49db9; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #c9b58e; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #a49db9; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #a49db9; \""
"namespace" = "class=\"namespace\" style=\"color: #a49db9; \""
"operator" = "class=\"operator\" style=\"color: #c2b4a8; \""
"punctuation" = "class=\"punctuation\" style=\"color: #c2b4a8; \""
"special" = "class=\"special\" style=\"color: #c9b58e; \""
"string" = "class=\"string\" style=\"color: #c9b58e; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #cbab8a; \""
"tag" = "class=\"tag\" style=\"color: #d29595; \""
"type" = "class=\"type\" style=\"color: #c2b4a8; \""
"variable" = "class=\"variable\" style=\"color: #dad7d5; \""
