"comment" = "style=\"color: #707035; \""
"constant" = "style=\"color: #b494af; \""
"diff.delta" = "style=\"color: #b494af; \""
"diff.minus" = "style=\"color: #d29595; \""
"diff.plus" = "style=\"color: #a49db9; \""
"function" = "style=\"color: #a49db9; \""
"keyword" = "style=\"color: #cbab8a; \""
"keyword.control" = "style=\"color: #d29595; \""
"keyword.control.import" = "style=\"color: #cbab8a; \""
"keyword.function" = "style=\"color: #d29595; \""
"label" = "style=\"color: #cbab8a; \""
"markup.bold" = "style=\"font-weight: bold; color: #b494af; \""
"markup.heading" = "style=\"color: #cbab8a; \""
"markup.italic" = "style=\"text-decoration: underline; color: #a49db9; \""
"markup.link.text" = "style=\"color: #707035; \""
"markup.link.url" = "style=\"color: #707035; \""
"markup.list" = "style=\"color: #a49db9; \""
"markup.quote" = "style=\"color: #c9b58e; \""
"markup.raw" = "style=\"color: #a49db9; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #a49db9; \""
"operator" = "style=\"color: #c2b4a8; \""
"punctuation" = "style=\"color: #c2b4a8; \""
"special" = "style=\"color: #c9b58e; \""
"string" = "style=\"color: #c9b58e; \""
"string.regexp" = "style=\"color: #cbab8a; \""
"tag" = "style=\"color: #d29595; \""
"type" = "style=\"color: #c2b4a8; \""
"variable" = "style=\"color: #dad7d5; \""
