"background" = "style=\"background-color: #161617; \""
"attribute" = "style=\"text-decoration: underline; color: #aca1cf; \""
"comment" = "style=\"text-decoration: underline; color: #757581; \""
"constant" = "style=\"color: #ea83a5;\""
"constant.builtin" = "style=\"color: #e6b99d;\""
"constant.character.escape" = "style=\"color: #ea83a5;\""
"constant.numeric" = "style=\"color: #e29eca;\""
"constructor" = "style=\"color: #e6b99d;\""
"diff.delta" = "style=\"color: #b9aeda;\""
"diff.minus" = "style=\"color: #ffae9f;\""
"diff.plus" = "style=\"color: #9dc6ac;\""
"function" = "style=\"color: #c1c0d4;\""
"function.builtin" = "style=\"color: #b9aeda;\""
"function.macro" = "style=\"color: #f591b2;\""
"keyword" = "style=\"color: #aca1cf;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #aca1cf; \""
"keyword.directive" = "style=\"color: #e29eca;\""
"label" = "style=\"color: #e6b99d;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #b9aeda; \""
"markup.heading.marker" = "style=\"color: #9998a8; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"text-decoration: underline; color: #aca1cf; \""
"markup.link.url" = "style=\"color: #90b99f; \""
"markup.list" = "style=\"color: #9998a8;\""
"markup.raw" = "style=\"color: #e6b99d;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #ea83a5; \""
"operator" = "style=\"color: #e6b99d;\""
"punctuation" = "style=\"color: #9998a8;\""
"punctuation.delimiter" = "style=\"color: #9998a8;\""
"special" = "style=\"color: #e6b99d;\""
"string" = "style=\"color: #90b99f;\""
"string.regexp" = "style=\"color: #90b99f;\""
"string.special" = "style=\"color: #e6b99d;\""
"tag" = "style=\"color: #ea83a5;\""
"type" = "style=\"color: #b9aeda;\""
"type.builtin" = "style=\"color: #e29eca;\""
"type.enum.variant" = "style=\"color: #e29eca;\""
"variable" = "style=\"color: #c9c7cd;\""
"variable.builtin" = "style=\"color: #b9aeda;\""
"variable.other.member" = "style=\"color: #c1c0d4;\""
"variable.parameter" = "style=\"color: #ea83a5;\""
