"background" = "style=\"background-color: #190f0f; \""
"attribute" = "style=\"color: #65aba3;\""
"comment" = "style=\"text-decoration: underline; color: #d2505f; \""
"constant" = "style=\"color: #ff7550; \""
"constant.builtin" = "style=\"font-weight: bold; color: #ff7550; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #ff7550; \""
"constant.numeric" = "style=\"color: #ff7550;\""
"constructor" = "style=\"font-weight: bold; color: #65aba3; \""
"diff.delta" = "style=\"color: #ce8b9f;\""
"diff.minus" = "style=\"color: #d95362;\""
"diff.plus" = "style=\"color: #6db269;\""
"function" = "style=\"font-weight: bold; color: #8ea84d; \""
"function.builtin" = "style=\"color: #8ea84d;\""
"function.macro" = "style=\"color: #8ea84d;\""
"keyword" = "style=\"color: #eb842b; \""
"label" = "style=\"color: #65aba3;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #eb842b; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #6db269;\""
"markup.link.url" = "style=\"color: #65aba3; \""
"markup.raw" = "style=\"color: #d95362;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #65aba3;\""
"namespace" = "style=\"color: #d95362;\""
"operator" = "style=\"color: #eb842b;\""
"punctuation" = "style=\"color: #eb842b;\""
"special" = "style=\"color: #d95362;\""
"string" = "style=\"color: #ce8b9f;\""
"tag" = "style=\"color: #8ea84d;\""
"type" = "style=\"color: #65aba3;\""
"type.builtin" = "style=\"color: #ff7550;\""
"variable" = "style=\"color: #cebabf;\""
"variable.builtin" = "style=\"color: #65aba3;\""
"variable.other.member" = "style=\"color: #65aba3;\""
"variable.parameter" = "style=\"color: #6db269;\""
