"constant.numeric" = "class=\"constant numeric\" style=\"color: #ff7550;\""
"function" = "class=\"function\" style=\"font-weight: bold; color: #8ea84d; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #65aba3;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #8ea84d;\""
"keyword" = "class=\"keyword\" style=\"color: #eb842b; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ce8b9f;\""
"string" = "class=\"string\" style=\"color: #ce8b9f;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #6db269;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #65aba3;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #65aba3; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #ff7550; \""
"operator" = "class=\"operator\" style=\"color: #eb842b; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #6db269;\""
"special" = "class=\"special\" style=\"color: #d95362;\""
"function.macro" = "class=\"function macro\" style=\"color: #8ea84d;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #190f0f; \""
"punctuation" = "class=\"punctuation\" style=\"color: #eb842b;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #6db269;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #d2505f; \""
"tag" = "class=\"tag\" style=\"color: #8ea84d;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #d95362;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #d95362;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #ff7550;\""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #65aba3; \""
"variable" = "class=\"variable\" style=\"color: #cebabf;\""
"text" = "class=\"text\" style=\"color: #cebabf; \""
"module" = "class=\"module\" style=\"color: #65aba3; \""
"constant" = "class=\"constant\" style=\"color: #ff7550; \""
"type" = "class=\"type\" style=\"color: #65aba3;\""
"attribute" = "class=\"attribute\" style=\"color: #65aba3;\""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #ff7550; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #eb842b; \""
"namespace" = "class=\"namespace\" style=\"color: #d95362;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #65aba3;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
