"background" = "class=\"background\" style=\"background-color: #ffffff; \""
"module" = "class=\"module\" style=\"color: black; \""
"operator" = "class=\"operator\" style=\"\""
"text" = "class=\"text\" style=\"color: #000000; \""
