"attribute" = "style=\"color: ; \""
"comment" = "style=\"color: #7e8e91;\""
"comment.block.documentation" = "style=\"font-weight: bold; color: #7e8e91; \""
"constant" = "style=\"color: ; \""
"constant.builtin" = "style=\"color: #ae81ff; \""
"constant.character" = "style=\"color: #e6db74; \""
"constant.character.escape" = "style=\"text-decoration: underline; color: #66d9ef; \""
"constant.numeric" = "style=\"color: #ae81ff; \""
"constructor" = "style=\"color: ; \""
"diff.delta" = "style=\"color: #89807d;\""
"diff.minus" = "style=\"color: #960050;\""
"diff.plus" = "style=\"color: ;\""
"function" = "style=\"color: ; \""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"text-decoration: underline; color: #c4be89; \""
"keyword" = "style=\"font-weight: bold; color: ; \""
"keyword.control" = "style=\"font-weight: bold; color: ; \""
"keyword.control.exception" = "style=\"font-weight: bold; color: ; \""
"keyword.directive" = "style=\"font-weight: bold; color: ; \""
"keyword.storage.modifier" = "style=\"text-decoration: underline; color: #fd971f; \""
"label" = "style=\"color: #e6db74;\""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"color: ;\""
"markup.raw" = "style=\"color: ;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: ; \""
"namespace" = "style=\"color: ; \""
"operator" = "style=\"color: ;\""
"punctuation" = "style=\"color: ; \""
"punctuation.delimiter" = "style=\"color: #8f8f8f;\""
"special" = "style=\"color: ; \""
"string" = "style=\"color: #e6db74; \""
"string.regexp" = "style=\"color: ; \""
"tag.builtin" = "style=\"font-weight: bold; color: #ae81ff; \""
"type" = "style=\"color: #66d9ef;\""
"type.builtin" = "style=\"color: #66D9EF; \""
"type.enum.variant" = "style=\"color: ; \""
"variable" = "style=\"color: ; \""
"variable.builtin" = "style=\"font-weight: bold; color: #ae81ff; \""
"variable.other.member" = "style=\"color: ; \""
"variable.parameter" = "style=\"color: ;\""
