"attribute" = "style=\"color: #7cd5f1;\""
"comment" = "style=\"text-decoration: underline; color: #6b7678; \""
"constant" = "style=\"color: #ffb270;\""
"constant.builtin" = "style=\"color: #ff6d7e;\""
"constant.character.escape" = "style=\"color: #f2fffc; \""
"constant.numeric" = "style=\"color: #baa0f8;\""
"constructor" = "style=\"color: #7cd5f1;\""
"diff.delta" = "style=\"color: #ffb270;\""
"diff.minus" = "style=\"color: #ff6d7e;\""
"diff.plus" = "style=\"color: #a2e57b;\""
"function" = "style=\"color: #a2e57b;\""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"color: #7cd5f1; \""
"keyword" = "style=\"color: #ff6d7e; \""
"keyword.directive" = "style=\"color: #7cd5f1;\""
"label" = "style=\"color: #f2fffc;\""
"markup.bold" = "style=\"font-weight: bold; color: #ffb270; \""
"markup.heading" = "style=\"color: #a2e57b;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ffb270; \""
"markup.link.text" = "style=\"color: #ffed72;\""
"markup.link.url" = "style=\"color: #ffb270; \""
"markup.quote" = "style=\"color: #a2e57b;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #f59762;\""
"namespace" = "style=\"color: #f2fffc;\""
"operator" = "style=\"color: #ff6d7e;\""
"punctuation" = "style=\"color: #798384;\""
"special" = "style=\"color: #f59762;\""
"string" = "style=\"color: #ffed72;\""
"type" = "style=\"color: #a2e57b;\""
"type.builtin" = "style=\"color: #ff6d7e; \""
"variable" = "style=\"color: #f2fffc;\""
"variable.builtin" = "style=\"color: #ff6d7e;\""
"variable.other.member" = "style=\"color: #f2fffc;\""
"variable.parameter" = "style=\"color: #f59762;\""
