"constant.numeric" = "class=\"constant numeric\" style=\"color: #c39ac9;\""
"function" = "class=\"function\" style=\"color: #bad761;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #eaf2f1;\""
"function.builtin" = "class=\"function builtin\" style=\"color: ; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #bad761;\""
"keyword" = "class=\"keyword\" style=\"color: #ff657a; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ff9b5e;\""
"string" = "class=\"string\" style=\"color: #ffd76d;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f59762;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ff657a;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #ff9b5e; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #eaf2f1; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #9cd1bb;\""
"operator" = "class=\"operator\" style=\"color: #ff657a; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #bad761;\""
"special" = "class=\"special\" style=\"color: #f59762;\""
"function.macro" = "class=\"function macro\" style=\"color: #9cd1bb; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #ff9b5e; \""
"background" = "class=\"background\" style=\"background-color: #282a3a; \""
"punctuation" = "class=\"punctuation\" style=\"color: #767b81;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ffd76d;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #696d77; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff657a;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #ff657a; \""
"constructor" = "class=\"constructor\" style=\"color: #9cd1bb;\""
"variable" = "class=\"variable\" style=\"color: #eaf2f1;\""
"text" = "class=\"text\" style=\"color: #eaf2f1; \""
"module" = "class=\"module\" style=\"color: #f59762; \""
"constant" = "class=\"constant\" style=\"color: #ff9b5e;\""
"type" = "class=\"type\" style=\"color: #bad761;\""
"attribute" = "class=\"attribute\" style=\"color: #9cd1bb;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ff657a;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #bad761;\""
"namespace" = "class=\"namespace\" style=\"color: #eaf2f1;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ff9b5e; \""
"label" = "class=\"label\" style=\"color: #eaf2f1;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
