"constant.numeric" = "class=\"constant numeric\" style=\"color: #a8a9eb;\""
"function" = "class=\"function\" style=\"color: #adda78;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #fff1f3;\""
"function.builtin" = "class=\"function builtin\" style=\"color: ; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #adda78;\""
"keyword" = "class=\"keyword\" style=\"color: #fd6883; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #f38d70;\""
"string" = "class=\"string\" style=\"color: #f9cc6c;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f59762;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #fd6883;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #f38d70; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #fff1f3; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #85dacc;\""
"operator" = "class=\"operator\" style=\"color: #fd6883; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #adda78;\""
"special" = "class=\"special\" style=\"color: #f59762;\""
"function.macro" = "class=\"function macro\" style=\"color: #85dacc; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #f38d70; \""
"background" = "class=\"background\" style=\"background-color: #2c2525; \""
"punctuation" = "class=\"punctuation\" style=\"color: #8c8384;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #f9cc6c;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #72696a; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #fd6883;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #fd6883; \""
"constructor" = "class=\"constructor\" style=\"color: #85dacc;\""
"variable" = "class=\"variable\" style=\"color: #fff1f3;\""
"text" = "class=\"text\" style=\"color: #fff1f3; \""
"module" = "class=\"module\" style=\"color: #f59762; \""
"constant" = "class=\"constant\" style=\"color: #f38d70;\""
"type" = "class=\"type\" style=\"color: #adda78;\""
"attribute" = "class=\"attribute\" style=\"color: #85dacc;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #fd6883;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #adda78;\""
"namespace" = "class=\"namespace\" style=\"color: #fff1f3;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #f38d70; \""
"label" = "class=\"label\" style=\"color: #fff1f3;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
