"attribute" = "style=\"color: ; \""
"comment" = "style=\"color: #88846F; \""
"constant" = "style=\"color: ; \""
"constant.builtin" = "style=\"color: #ae81ff; \""
"constant.character" = "style=\"color: #e6db74; \""
"constant.character.escape" = "style=\"color: #ae81ff; \""
"constant.numeric" = "style=\"color: #ae81ff; \""
"constructor" = "style=\"color: ; \""
"diff.delta" = "style=\"color: #fd971f; \""
"diff.minus" = "style=\"color: #f92672; \""
"diff.plus" = "style=\"color: #a6e22e; \""
"function" = "style=\"color: ; \""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"color: ; \""
"keyword" = "style=\"color: ; \""
"keyword.control" = "style=\"color: ; \""
"keyword.control.import" = "style=\"text-decoration: underline; color: #66D9EF; \""
"keyword.directive" = "style=\"color: ; \""
"keyword.function" = "style=\"text-decoration: underline; color: #66D9EF; \""
"keyword.storage.type" = "style=\"text-decoration: underline; color: #66D9EF; \""
"label" = "style=\"color: ; \""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading" = "style=\"color: ;\""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: ;\""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"color: #66D9EF;\""
"markup.raw" = "style=\"color: ;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #66D9EF; \""
"namespace" = "style=\"color: ; \""
"operator" = "style=\"color: ; \""
"punctuation" = "style=\"color: ; \""
"punctuation.delimiter" = "style=\"color: ; \""
"special" = "style=\"color: ; \""
"string" = "style=\"color: #e6db74; \""
"string.regexp" = "style=\"color: ; \""
"type" = "style=\"font-weight: bold; color: #66D9EF; \""
"type.builtin" = "style=\"color: #66D9EF; \""
"type.enum.variant" = "style=\"color: ; \""
"variable" = "style=\"color: ; \""
"variable.builtin" = "style=\"color: ; \""
"variable.other.member" = "style=\"color: ; \""
"variable.parameter" = "style=\"color: #fd971f; \""
