"background" = "style=\"background-color: #2c2525; \""
"attribute" = "style=\"color: #85dacc;\""
"comment" = "style=\"text-decoration: underline; color: #72696a; \""
"constant" = "style=\"color: #f38d70;\""
"constant.builtin" = "style=\"color: #fd6883;\""
"constant.character.escape" = "style=\"color: #fff1f3; \""
"constant.numeric" = "style=\"color: #a8a9eb;\""
"constructor" = "style=\"color: #85dacc;\""
"diff.delta" = "style=\"color: #f38d70;\""
"diff.minus" = "style=\"color: #fd6883;\""
"diff.plus" = "style=\"color: #adda78;\""
"function" = "style=\"color: #adda78;\""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"color: #85dacc; \""
"keyword" = "style=\"color: #fd6883; \""
"keyword.directive" = "style=\"color: #85dacc;\""
"label" = "style=\"color: #fff1f3;\""
"markup.bold" = "style=\"font-weight: bold; color: #f38d70; \""
"markup.heading" = "style=\"color: #adda78;\""
"markup.italic" = "style=\"text-decoration: underline; color: #f38d70; \""
"markup.link.text" = "style=\"color: #f9cc6c;\""
"markup.link.url" = "style=\"color: #f38d70; \""
"markup.quote" = "style=\"color: #adda78;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #f59762;\""
"namespace" = "style=\"color: #fff1f3;\""
"operator" = "style=\"color: #fd6883;\""
"punctuation" = "style=\"color: #8c8384;\""
"special" = "style=\"color: #f59762;\""
"string" = "style=\"color: #f9cc6c;\""
"type" = "style=\"color: #adda78;\""
"type.builtin" = "style=\"color: #fd6883; \""
"variable" = "style=\"color: #fff1f3;\""
"variable.builtin" = "style=\"color: #fd6883;\""
"variable.other.member" = "style=\"color: #fff1f3;\""
"variable.parameter" = "style=\"color: #f59762;\""
