"constant.numeric" = "class=\"constant numeric\" style=\"color: #948ae3;\""
"function" = "class=\"function\" style=\"color: #7bd88f;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #f7f1ff;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #5ad4e6; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #7bd88f;\""
"keyword" = "class=\"keyword\" style=\"color: #fc618d; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #fd9353;\""
"string" = "class=\"string\" style=\"color: #fce566;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f59762;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #fc618d;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #fd9353; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f7f1ff; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #5ad4e6;\""
"operator" = "class=\"operator\" style=\"color: #fc618d; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #7bd88f;\""
"special" = "class=\"special\" style=\"color: #f59762;\""
"function.macro" = "class=\"function macro\" style=\"color: #5ad4e6; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #fd9353; \""
"background" = "class=\"background\" style=\"background-color: #222222; \""
"punctuation" = "class=\"punctuation\" style=\"color: #8b888f;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #fce566;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #69676c; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #fc618d;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #fc618d; \""
"constructor" = "class=\"constructor\" style=\"color: #5ad4e6;\""
"variable" = "class=\"variable\" style=\"color: #f7f1ff;\""
"module" = "class=\"module\" style=\"color: #f59762; \""
"constant" = "class=\"constant\" style=\"color: #fd9353;\""
"type" = "class=\"type\" style=\"color: #7bd88f;\""
"attribute" = "class=\"attribute\" style=\"color: #5ad4e6;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #fc618d;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #7bd88f;\""
"namespace" = "class=\"namespace\" style=\"color: #f7f1ff;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #fd9353; \""
"label" = "class=\"label\" style=\"color: #f7f1ff;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
