"constant.numeric" = "class=\"constant numeric\" style=\"color: #ab9df2;\""
"function" = "class=\"function\" style=\"color: #a9dc76;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #fcfcfa;\""
"function.builtin" = "class=\"function builtin\" style=\"color: ; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #a9dc76;\""
"keyword" = "class=\"keyword\" style=\"color: #ff6188; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #fc9867;\""
"string" = "class=\"string\" style=\"color: #ffd866;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #f59762;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ff6188;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #fc9867; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #fcfcfa; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #78dce8;\""
"operator" = "class=\"operator\" style=\"color: #ff6188; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a9dc76;\""
"special" = "class=\"special\" style=\"color: #f59762;\""
"function.macro" = "class=\"function macro\" style=\"color: #78dce8; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #fc9867; \""
"background" = "class=\"background\" style=\"background-color: #2d2a2e; \""
"punctuation" = "class=\"punctuation\" style=\"color: #939293;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ffd866;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #727072; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff6188;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #ff6188; \""
"constructor" = "class=\"constructor\" style=\"color: #78dce8;\""
"variable" = "class=\"variable\" style=\"color: #fcfcfa;\""
"module" = "class=\"module\" style=\"color: #f59762; \""
"constant" = "class=\"constant\" style=\"color: #fc9867;\""
"type" = "class=\"type\" style=\"color: #a9dc76;\""
"attribute" = "class=\"attribute\" style=\"color: #78dce8;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ff6188;\""
"markup.heading" = "class=\"markup heading\" style=\"color: #a9dc76;\""
"namespace" = "class=\"namespace\" style=\"color: #fcfcfa;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #fc9867; \""
"label" = "class=\"label\" style=\"color: #fcfcfa;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
