"attribute" = "style=\"color: #78dce8;\""
"comment" = "style=\"text-decoration: underline; color: #727072; \""
"constant" = "style=\"color: #fc9867;\""
"constant.builtin" = "style=\"color: #ff6188;\""
"constant.character.escape" = "style=\"color: #fcfcfa; \""
"constant.numeric" = "style=\"color: #ab9df2;\""
"constructor" = "style=\"color: #78dce8;\""
"diff.delta" = "style=\"color: #fc9867;\""
"diff.minus" = "style=\"color: #ff6188;\""
"diff.plus" = "style=\"color: #a9dc76;\""
"function" = "style=\"color: #a9dc76;\""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"color: #78dce8; \""
"keyword" = "style=\"color: #ff6188; \""
"keyword.directive" = "style=\"color: #78dce8;\""
"label" = "style=\"color: #fcfcfa;\""
"markup.bold" = "style=\"font-weight: bold; color: #fc9867; \""
"markup.heading" = "style=\"color: #a9dc76;\""
"markup.italic" = "style=\"text-decoration: underline; color: #fc9867; \""
"markup.link.text" = "style=\"color: #ffd866;\""
"markup.link.url" = "style=\"color: #fc9867; \""
"markup.quote" = "style=\"color: #a9dc76;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #f59762;\""
"namespace" = "style=\"color: #fcfcfa;\""
"operator" = "style=\"color: #ff6188;\""
"punctuation" = "style=\"color: #939293;\""
"special" = "style=\"color: #f59762;\""
"string" = "style=\"color: #ffd866;\""
"type" = "style=\"color: #a9dc76;\""
"type.builtin" = "style=\"color: #ff6188; \""
"variable" = "style=\"color: #fcfcfa;\""
"variable.builtin" = "style=\"color: #ff6188;\""
"variable.other.member" = "style=\"color: #fcfcfa;\""
"variable.parameter" = "style=\"color: #f59762;\""
