"background" = "style=\"background-color: #222222; \""
"attribute" = "style=\"color: #5ad4e6;\""
"comment" = "style=\"text-decoration: underline; color: #69676c; \""
"constant" = "style=\"color: #fd9353;\""
"constant.builtin" = "style=\"color: #fc618d;\""
"constant.character.escape" = "style=\"color: #f7f1ff; \""
"constant.numeric" = "style=\"color: #948ae3;\""
"constructor" = "style=\"color: #5ad4e6;\""
"diff.delta" = "style=\"color: #fd9353;\""
"diff.minus" = "style=\"color: #fc618d;\""
"diff.plus" = "style=\"color: #7bd88f;\""
"function" = "style=\"color: #7bd88f;\""
"function.builtin" = "style=\"color: #5ad4e6; \""
"function.macro" = "style=\"color: #5ad4e6; \""
"keyword" = "style=\"color: #fc618d; \""
"keyword.directive" = "style=\"color: #5ad4e6;\""
"label" = "style=\"color: #f7f1ff;\""
"markup.bold" = "style=\"font-weight: bold; color: #fd9353; \""
"markup.heading" = "style=\"color: #7bd88f;\""
"markup.italic" = "style=\"text-decoration: underline; color: #fd9353; \""
"markup.link.text" = "style=\"color: #fce566;\""
"markup.link.url" = "style=\"color: #fd9353; \""
"markup.quote" = "style=\"color: #7bd88f;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #f59762;\""
"namespace" = "style=\"color: #f7f1ff;\""
"operator" = "style=\"color: #fc618d;\""
"punctuation" = "style=\"color: #8b888f;\""
"special" = "style=\"color: #f59762;\""
"string" = "style=\"color: #fce566;\""
"type" = "style=\"color: #7bd88f;\""
"type.builtin" = "style=\"color: #fc618d; \""
"variable" = "style=\"color: #f7f1ff;\""
"variable.builtin" = "style=\"color: #fc618d;\""
"variable.other.member" = "style=\"color: #f7f1ff;\""
"variable.parameter" = "style=\"color: #f59762;\""
