"attribute" = "style=\"color: #9cd1bb;\""
"comment" = "style=\"text-decoration: underline; color: #696d77; \""
"constant" = "style=\"color: #ff9b5e;\""
"constant.builtin" = "style=\"color: #ff657a;\""
"constant.character.escape" = "style=\"color: #eaf2f1; \""
"constant.numeric" = "style=\"color: #c39ac9;\""
"constructor" = "style=\"color: #9cd1bb;\""
"diff.delta" = "style=\"color: #ff9b5e;\""
"diff.minus" = "style=\"color: #ff657a;\""
"diff.plus" = "style=\"color: #bad761;\""
"function" = "style=\"color: #bad761;\""
"function.builtin" = "style=\"color: ; \""
"function.macro" = "style=\"color: #9cd1bb; \""
"keyword" = "style=\"color: #ff657a; \""
"keyword.directive" = "style=\"color: #9cd1bb;\""
"label" = "style=\"color: #eaf2f1;\""
"markup.bold" = "style=\"font-weight: bold; color: #ff9b5e; \""
"markup.heading" = "style=\"color: #bad761;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ff9b5e; \""
"markup.link.text" = "style=\"color: #ffd76d;\""
"markup.link.url" = "style=\"color: #ff9b5e; \""
"markup.quote" = "style=\"color: #bad761;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #f59762;\""
"namespace" = "style=\"color: #eaf2f1;\""
"operator" = "style=\"color: #ff657a;\""
"punctuation" = "style=\"color: #767b81;\""
"special" = "style=\"color: #f59762;\""
"string" = "style=\"color: #ffd76d;\""
"type" = "style=\"color: #bad761;\""
"type.builtin" = "style=\"color: #ff657a; \""
"variable" = "style=\"color: #eaf2f1;\""
"variable.builtin" = "style=\"color: #ff657a;\""
"variable.other.member" = "style=\"color: #eaf2f1;\""
"variable.parameter" = "style=\"color: #f59762;\""
