"background" = "style=\"background-color: #062329; \""
"attribute" = "style=\"color: #d1b897;\""
"comment" = "style=\"color: #44b340;\""
"constant" = "style=\"color: #7ad0c6;\""
"constant.builtin" = "style=\"color: #ffffff;\""
"constant.builtin.boolean" = "style=\"color: #ffffff;\""
"constant.character" = "style=\"color: #d1b897;\""
"constant.numeric" = "style=\"color: #7ad0c6;\""
"constructor" = "style=\"color: #ffffff;\""
"diff.delta" = "style=\"color: #66d9ef; \""
"diff.minus" = "style=\"color: #f92672; \""
"diff.plus" = "style=\"color: #a6e22e; \""
"function" = "style=\"color: #ffffff;\""
"function.builtin" = "style=\"color: #ffffff;\""
"function.macro" = "style=\"color: #8cde94;\""
"function.method" = "style=\"color: #c1d1e3;\""
"function.special" = "style=\"color: #8cde94;\""
"keyword" = "style=\"color: #ffffff;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.strikethrough" = "style=\"\""
"punctuation" = "style=\"color: #8cde94;\""
"string" = "style=\"color: #2ec90c;\""
"tag.builtin" = "style=\"color: #ffffff;\""
"type" = "style=\"color: #d1b897;\""
"type.builtin" = "style=\"color: #ffffff;\""
"variable" = "style=\"color: #c1d1e3;\""
"variable.builtin" = "style=\"color: #ffffff;\""
