"attribute" = "class=\"attribute\" style=\"color: #d1b897;\""
"background" = "class=\"background\" style=\"background-color: #062329; \""
"comment" = "class=\"comment\" style=\"color: #44b340;\""
"constant" = "class=\"constant\" style=\"color: #7ad0c6;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ffffff;\""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #ffffff;\""
"constant.character" = "class=\"constant character\" style=\"color: #d1b897;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #7ad0c6;\""
"constructor" = "class=\"constructor\" style=\"color: #ffffff;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #66d9ef; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #f92672; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a6e22e; \""
"function" = "class=\"function\" style=\"color: #ffffff;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #ffffff;\""
"function.macro" = "class=\"function macro\" style=\"color: #8cde94;\""
"function.method" = "class=\"function method\" style=\"color: #c1d1e3;\""
"function.special" = "class=\"function special\" style=\"color: #8cde94;\""
"keyword" = "class=\"keyword\" style=\"color: #ffffff;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
"module" = "class=\"module\" style=\"color: #ffffff; \""
"operator" = "class=\"operator\" style=\"\""
"punctuation" = "class=\"punctuation\" style=\"color: #8cde94;\""
"string" = "class=\"string\" style=\"color: #2ec90c;\""
"tag.builtin" = "class=\"tag builtin\" style=\"color: #ffffff;\""
"type" = "class=\"type\" style=\"color: #d1b897;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #ffffff;\""
"variable" = "class=\"variable\" style=\"color: #c1d1e3;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ffffff;\""
