"attribute" = "style=\"color: #ffd479; \""
"comment" = "style=\"color: #777c85; \""
"constant" = "style=\"color: #e1a6f2; \""
"constant.builtin" = "style=\"color: #e1a6f2; \""
"constant.character" = "style=\"color: #92d192; \""
"constant.character.escape" = "style=\"color: #76d4d6; \""
"constant.numeric" = "style=\"color: #fca369; \""
"constructor" = "style=\"color: #6ab0f3; \""
"diff.delta" = "style=\"color: #6ab0f3; \""
"diff.minus" = "style=\"color: #f2777a; \""
"diff.plus" = "style=\"color: #92d192; \""
"function" = "style=\"color: #ffffff; \""
"function.builtin" = "style=\"color: #ffffff; \""
"function.macro" = "style=\"color: #6ab0f3; \""
"keyword" = "style=\"color: #ffeea6; \""
"keyword.control" = "style=\"color: #ffeea6; \""
"keyword.directive" = "style=\"color: #ffeea6; \""
"label" = "style=\"color: #6ab0f3; \""
"markup.bold" = "style=\"font-weight: bold; color: #6ab0f3; \""
"markup.heading" = "style=\"font-weight: bold; color: #6ab0f3; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #fca369;\""
"markup.link.url" = "style=\"\""
"markup.list" = "style=\"color: #76d4d6;\""
"markup.quote" = "style=\"color: #92d192;\""
"markup.raw" = "style=\"color: #fca369;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #6ab0f3; \""
"namespace" = "style=\"color: #6ab0f3; \""
"operator" = "style=\"color: #ac8d58; \""
"punctuation" = "style=\"color: #d4d4d4; \""
"punctuation.delimiter" = "style=\"color: #d4d4d4; \""
"special" = "style=\"color: #ffffff; \""
"string" = "style=\"color: #92d192; \""
"string.regexp" = "style=\"color: #fca369; \""
"tag" = "style=\"color: #6ab0f3;\""
"type" = "style=\"color: #6ab0f3; \""
"type.builtin" = "style=\"color: #6ab0f3; \""
"type.enum.variant" = "style=\"color: #6ab0f3; \""
"variable" = "style=\"color: #f2777a; \""
"variable.builtin" = "style=\"color: #6ab0f3; \""
"variable.other.member" = "style=\"color: #f2777a; \""
"variable.parameter" = "style=\"color: #f2777a; \""
