"background" = "style=\"background-color: #011627; \""
"attribute" = "style=\"color: #7fdbca; \""
"comment" = "style=\"text-decoration: underline; color: #637777; \""
"comment.block.documentation" = "style=\"color: #637777; \""
"constant" = "style=\"color: #d6deeb; \""
"constant.builtin" = "style=\"color: #7fdbca; \""
"constant.character.escape" = "style=\"color: #f78c6c; \""
"constructor" = "style=\"color: #82aaff; \""
"diff.delta" = "style=\"color: #82aaff; \""
"diff.delta.moved" = "style=\"text-decoration: underline; color: #82aaff; \""
"diff.minus" = "style=\"color: #ff5874; \""
"diff.plus" = "style=\"color: #addb67; \""
"function" = "style=\"color: #82aaff; \""
"function.macro" = "style=\"color: #f78c6c; \""
"function.special" = "style=\"color: #c792ea; \""
"keyword" = "style=\"color: #c792ea; \""
"keyword.control.exception" = "style=\"color: #ff5874; \""
"keyword.control.import" = "style=\"text-decoration: underline; color: #addb67; \""
"keyword.control.return" = "style=\"text-decoration: underline; color: #c792ea; \""
"label" = "style=\"color: #d6deeb; \""
"markup.bold" = "style=\"font-weight: bold; color: #d6deeb; \""
"markup.heading" = "style=\"font-weight: bold; color: #82aaff; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #82aaff; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #7fdbca; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #addb67; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #c792ea; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #f78c6c; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #637777; \""
"markup.heading.marker" = "style=\"color: #444444; \""
"markup.italic" = "style=\"text-decoration: underline; color: #d6deeb; \""
"markup.link" = "style=\"color: #c792ea; \""
"markup.link.url" = "style=\"color: #637777; \""
"markup.list" = "style=\"color: #c792ea; \""
"markup.quote" = "style=\"text-decoration: underline; color: #addb67; \""
"markup.raw" = "style=\"color: #ecc48d; background-color: #112630; \""
"markup.strikethrough" = "style=\"color: #d6deeb; \""
"module" = "style=\"color: #eeeeee; \""
"namespace" = "style=\"color: #f78c6c; \""
"operator" = "style=\"color: #c792ea; \""
"punctuation" = "style=\"color: #d6deeb; \""
"punctuation.special" = "style=\"color: #c792ea; \""
"special" = "style=\"color: #eeeeee; \""
"string" = "style=\"color: #ecc48d; \""
"string.regexp" = "style=\"color: #addb67; \""
"string.special.url" = "style=\"color: #ecc48d; \""
"tag" = "style=\"color: #82aaff; \""
"type" = "style=\"color: #addb67; \""
"variable" = "style=\"color: #addb67; \""
"variable.builtin" = "style=\"text-decoration: underline; color: #addb67; \""
