"background" = "style=\"background-color: #192330; \""
"attribute" = "style=\"color: #dbc074; \""
"comment" = "style=\"color: #738091; \""
"comment.block.documentation" = "style=\"font-weight: bold; color: #738091; \""
"constant" = "style=\"color: #f6b079; \""
"constant.builtin" = "style=\"color: #f6b079; \""
"constant.builtin.boolean" = "style=\"color: #f4a261; \""
"constant.character" = "style=\"color: #81b29a; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #e0c989; \""
"constant.numeric" = "style=\"color: #f4a261; \""
"constructor" = "style=\"color: #9d79d6; \""
"diff.delta" = "style=\"color: #719cd6;\""
"diff.delta.moved" = "style=\"color: #63cdcf;\""
"diff.minus" = "style=\"color: #c94f6d;\""
"diff.plus" = "style=\"color: #81b29a;\""
"function" = "style=\"color: #86abdc; \""
"function.builtin" = "style=\"color: #c94f6d; \""
"function.macro" = "style=\"color: #c94f6d; \""
"keyword" = "style=\"color: #9d79d6; \""
"keyword.control" = "style=\"color: #d67ad2; \""
"keyword.control.conditional" = "style=\"color: #baa1e2; \""
"keyword.control.exception" = "style=\"color: #9d79d6; \""
"keyword.control.import" = "style=\"color: #dc8ed9; \""
"keyword.control.repeat" = "style=\"color: #baa1e2; \""
"keyword.control.return" = "style=\"color: #9d79d6; \""
"keyword.directive" = "style=\"color: #dc8ed9; \""
"keyword.function" = "style=\"color: #c94f6d; \""
"keyword.operator" = "style=\"font-weight: bold; color: #aeafb0; \""
"keyword.storage" = "style=\"color: #9d79d6; \""
"keyword.storage.modifier" = "style=\"color: #dbc074; \""
"keyword.storage.type" = "style=\"color: #9d79d6; \""
"label" = "style=\"color: #baa1e2; \""
"markup.bold" = "style=\"font-weight: bold; color: #f4a261; \""
"markup.heading" = "style=\"font-weight: bold; color: #dbc074; \""
"markup.italic" = "style=\"color: #d67ad2; \""
"markup.link" = "style=\"font-weight: bold; color: #e0c989; \""
"markup.list" = "style=\"font-weight: bold; color: #9d79d6; \""
"markup.quote" = "style=\"color: #719cd6; \""
"markup.raw" = "style=\"color: #9d79d6; \""
"markup.raw.inline" = "style=\"color: #f4a261; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #7ad4d6; \""
"operator" = "style=\"color: #aeafb0; \""
"punctuation" = "style=\"color: #aeafb0; \""
"special" = "style=\"color: #aeafb0; \""
"string" = "style=\"color: #81b29a; \""
"string.regexp" = "style=\"color: #e0c989; \""
"string.special" = "style=\"font-weight: bold; color: #e0c989; \""
"string.special.url" = "style=\"font-weight: bold; color: #63cdcf; \""
"tag" = "style=\"color: #86abdc; \""
"type" = "style=\"color: #dbc074; \""
"type.builtin" = "style=\"color: #7ad4d6; \""
"type.enum.variant" = "style=\"color: #f6b079; \""
"variable" = "style=\"color: #dfdfe0; \""
"variable.builtin" = "style=\"color: #c94f6d; \""
"variable.other.member" = "style=\"color: #aeafb0; \""
"variable.parameter" = "style=\"color: #7ad4d6; \""
