"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"color: #baa1e2; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #9d79d6; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #f4a261; \""
"function" = "class=\"function\" style=\"color: #86abdc; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #c94f6d; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #aeafb0; \""
"keyword.operator" = "class=\"keyword operator\" style=\"font-weight: bold; color: #aeafb0; \""
"markup.list" = "class=\"markup list\" style=\"font-weight: bold; color: #9d79d6; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #c94f6d; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #719cd6; \""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"color: #9d79d6; \""
"keyword" = "class=\"keyword\" style=\"color: #9d79d6; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #dc8ed9; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #719cd6;\""
"string" = "class=\"string\" style=\"color: #81b29a; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #7ad4d6; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #c94f6d; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #d67ad2; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #e0c989; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #dc8ed9; \""
"operator" = "class=\"operator\" style=\"color: #aeafb0; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #81b29a;\""
"special" = "class=\"special\" style=\"color: #aeafb0; \""
"function.macro" = "class=\"function macro\" style=\"color: #c94f6d; \""
"markup.italic" = "class=\"markup italic\" style=\"color: #d67ad2; \""
"background" = "class=\"background\" style=\"background-color: #192330; \""
"punctuation" = "class=\"punctuation\" style=\"color: #aeafb0; \""
"string.special.url" = "class=\"string special url\" style=\"font-weight: bold; color: #63cdcf; \""
"comment" = "class=\"comment\" style=\"color: #738091; \""
"tag" = "class=\"tag\" style=\"color: #86abdc; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #63cdcf;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #9d79d6; \""
"constant.character" = "class=\"constant character\" style=\"color: #81b29a; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #c94f6d;\""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"color: #dbc074; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #7ad4d6; \""
"constructor" = "class=\"constructor\" style=\"color: #9d79d6; \""
"variable" = "class=\"variable\" style=\"color: #dfdfe0; \""
"text" = "class=\"text\" style=\"color: #cdcecf; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #f6b079; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #9d79d6; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #e0c989; \""
"module" = "class=\"module\" style=\"color: #7ad4d6; \""
"markup.link" = "class=\"markup link\" style=\"font-weight: bold; color: #e0c989; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #f4a261; \""
"constant" = "class=\"constant\" style=\"color: #f6b079; \""
"string.special" = "class=\"string special\" style=\"font-weight: bold; color: #e0c989; \""
"type" = "class=\"type\" style=\"color: #dbc074; \""
"attribute" = "class=\"attribute\" style=\"color: #dbc074; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #f6b079; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #dbc074; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"color: #baa1e2; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #f4a261; \""
"namespace" = "class=\"namespace\" style=\"color: #7ad4d6; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-weight: bold; color: #738091; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #f4a261; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #9d79d6; \""
"label" = "class=\"label\" style=\"color: #baa1e2; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
