"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #ff5874; \""
"function" = "class=\"function\" style=\"color: #82aaff; \""
"markup.list" = "class=\"markup list\" style=\"color: #c792ea; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #addb67; \""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #c792ea; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #f78c6c; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #addb67; \""
"keyword" = "class=\"keyword\" style=\"color: #c792ea; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"font-style: italic; color: #addb67; \""
"function.special" = "class=\"function special\" style=\"color: #c792ea; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #82aaff; \""
"string" = "class=\"string\" style=\"color: #ecc48d; \""
"variable.builtin" = "class=\"variable builtin\" style=\"font-style: italic; color: #addb67; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #637777; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #f78c6c; \""
"operator" = "class=\"operator\" style=\"color: #c792ea; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #addb67; \""
"special" = "class=\"special\" style=\"color: #eeeeee; \""
"function.macro" = "class=\"function macro\" style=\"color: #f78c6c; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #d6deeb; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #011627; \""
"punctuation" = "class=\"punctuation\" style=\"color: #d6deeb; \""
"string.special.url" = "class=\"string special url\" style=\"text-decoration: underline; color: #ecc48d; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #637777; \""
"tag" = "class=\"tag\" style=\"color: #82aaff; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"font-style: italic; color: #82aaff; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #ecc48d; background-color: #112630; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff5874; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #7fdbca; \""
"constructor" = "class=\"constructor\" style=\"color: #82aaff; \""
"variable" = "class=\"variable\" style=\"color: #addb67; \""
"text" = "class=\"text\" style=\"color: #d6deeb; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #addb67; \""
"module" = "class=\"module\" style=\"color: #eeeeee; \""
"markup.link" = "class=\"markup link\" style=\"text-decoration: underline; color: #c792ea; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #c792ea; \""
"constant" = "class=\"constant\" style=\"color: #d6deeb; \""
"type" = "class=\"type\" style=\"color: #addb67; \""
"attribute" = "class=\"attribute\" style=\"color: #7fdbca; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #637777; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #7fdbca; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #82aaff; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #82aaff; \""
"namespace" = "class=\"namespace\" style=\"color: #f78c6c; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"color: #637777; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #d6deeb; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"font-style: italic; color: #c792ea; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #444444; \""
"label" = "class=\"label\" style=\"color: #d6deeb; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"color: #d6deeb; \""
