"background" = "style=\"background-color: #322a2d; \""
"attribute" = "style=\"font-weight: bold; color: #7060eb; \""
"comment" = "style=\"text-decoration: underline; color: #585858; \""
"comment.block.documentation" = "style=\"text-decoration: underline; color: #e8e8e8; \""
"constant" = "style=\"color: #d5971a;\""
"constant.character.escape" = "style=\"color: #16b673;\""
"constant.numeric" = "style=\"color: #7060eb;\""
"constructor" = "style=\"color: #16a3b6;\""
"debug" = "style=\"color: #585858;\""
"diff.delta" = "style=\"color: #d5971a;\""
"diff.minus" = "style=\"color: #e4b781;\""
"diff.plus" = "style=\"color: #49e9a6;\""
"function" = "style=\"color: #16a3b6;\""
"keyword" = "style=\"color: #ba8baf;\""
"keyword.control" = "style=\"font-weight: bold; color: #ba8baf; \""
"keyword.directive" = "style=\"color: ;\""
"keyword.import" = "style=\"color: #df769b; \""
"keyword.operator" = "style=\"text-decoration: underline; color: #ba8baf; \""
"label" = "style=\"color: #ba8baf;\""
"markup.bold" = "style=\"font-weight: bold; color: #df769b; \""
"markup.heading" = "style=\"color: #16a3b6;\""
"markup.italic" = "style=\"text-decoration: underline; color: #ba8baf; \""
"markup.link.text" = "style=\"color: #e4b781;\""
"markup.link.url" = "style=\"color: #d5971a; \""
"markup.list" = "style=\"color: #e4b781;\""
"markup.quote" = "style=\"color: #16b673;\""
"markup.raw" = "style=\"color: #49e9a6;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #ba8baf;\""
"operator" = "style=\"color: #cbbec2;\""
"special" = "style=\"color: #16a3b6;\""
"string" = "style=\"color: #49e9a6;\""
"type" = "style=\"color: #b0b0ff;\""
"variable" = "style=\"color: #e4b781;\""
"variable.other.member" = "style=\"color: #e4b781;\""
