"comment.block" = "style=\"\""
"comment.block.documentation" = "style=\"\""
"comment.line" = "style=\"\""
"constant.builtin.boolean" = "style=\"\""
"keyword.control.repeat" = "style=\"\""
"keyword.control.return" = "style=\"\""
"keyword.function" = "style=\"\""
"keyword.operator" = "style=\"\""
"markup.heading" = "style=\"\""
"markup.heading.1" = "style=\"\""
"markup.heading.2" = "style=\"\""
"markup.heading.3" = "style=\"\""
"markup.heading.4" = "style=\"\""
"markup.heading.5" = "style=\"\""
"markup.heading.6" = "style=\"\""
"markup.heading.completion" = "style=\"\""
"markup.heading.raw" = "style=\"\""
"markup.link.label" = "style=\"\""
"markup.link.url" = "style=\"\""
"markup.list.numbered" = "style=\"\""
"markup.list.unnumbered" = "style=\"\""
"markup.normal" = "style=\"\""
"markup.normal.completion" = "style=\"\""
"markup.normal.raw" = "style=\"\""
"markup.quote" = "style=\"\""
"markup.raw" = "style=\"\""
"markup.raw.block" = "style=\"\""
"markup.raw.inline" = "style=\"\""
"markup.raw.inline.completion" = "style=\"\""
"markup.raw.inline.hover" = "style=\"\""
"property" = "style=\"color: #e34e1b; \""
"string.regexp" = "style=\"\""
"string.special.path" = "style=\"\""
"string.special.symbol" = "style=\"\""
"string.special.url" = "style=\"\""
"variable.builtin" = "style=\"\""
"variable.function" = "style=\"\""
"variable.other.member" = "style=\"\""
"variable.parameter" = "style=\"\""
