"debug" = "class=\"debug\" style=\"color: #585858;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #7060eb;\""
"function" = "class=\"function\" style=\"color: #16a3b6;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #e4b781;\""
"keyword.operator" = "class=\"keyword operator\" style=\"text-decoration: underline; color: #ba8baf; \""
"markup.list" = "class=\"markup list\" style=\"color: #e4b781;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #16b673;\""
"keyword" = "class=\"keyword\" style=\"color: #ba8baf;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #d5971a;\""
"string" = "class=\"string\" style=\"color: #49e9a6;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #d5971a; \""
"keyword.control" = "class=\"keyword control\" style=\"font-weight: bold; color: #ba8baf; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #16b673;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: ;\""
"operator" = "class=\"operator\" style=\"color: #cbbec2; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #49e9a6;\""
"special" = "class=\"special\" style=\"color: #16a3b6;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #ba8baf; \""
"background" = "class=\"background\" style=\"background-color: #322a2d; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #e4b781;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #585858; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #49e9a6;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e4b781;\""
"constructor" = "class=\"constructor\" style=\"color: #16a3b6;\""
"variable" = "class=\"variable\" style=\"color: #e4b781;\""
"module" = "class=\"module\" style=\"color: #ba8baf; \""
"constant" = "class=\"constant\" style=\"color: #d5971a;\""
"type" = "class=\"type\" style=\"color: #b0b0ff;\""
"attribute" = "class=\"attribute\" style=\"font-weight: bold; color: #7060eb; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #16a3b6;\""
"keyword.import" = "class=\"keyword import\" style=\"color: #df769b; \""
"namespace" = "class=\"namespace\" style=\"color: #ba8baf;\""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"text-decoration: underline; color: #e8e8e8; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #df769b; \""
"label" = "class=\"label\" style=\"color: #ba8baf;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
