"markup.raw.inline.hover" = "class=\"markup raw inline hover\" style=\"\""
"string.special.path" = "class=\"string special path\" style=\"\""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"\""
"markup.normal" = "class=\"markup normal\" style=\"\""
"keyword.function" = "class=\"keyword function\" style=\"\""
"variable.other.member" = "class=\"variable other member\" style=\"\""
"keyword.operator" = "class=\"keyword operator\" style=\"\""
"markup.link.label" = "class=\"markup link label\" style=\"\""
"markup.quote" = "class=\"markup quote\" style=\"\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"\""
"markup.normal.completion" = "class=\"markup normal completion\" style=\"\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"\""
"markup.heading.3" = "class=\"markup heading 3\" style=\"\""
"markup.raw.block" = "class=\"markup raw block\" style=\"\""
"variable.parameter" = "class=\"variable parameter\" style=\"\""
"variable.builtin" = "class=\"variable builtin\" style=\"\""
"variable.function" = "class=\"variable function\" style=\"\""
"markup.link.url" = "class=\"markup link url\" style=\"\""
"operator" = "class=\"operator\" style=\"color: ; \""
"background" = "class=\"background\" style=\"background-color: #00262a; \""
"string.special.url" = "class=\"string special url\" style=\"\""
"markup.normal.raw" = "class=\"markup normal raw\" style=\"\""
"markup.raw" = "class=\"markup raw\" style=\"\""
"markup.raw.inline.completion" = "class=\"markup raw inline completion\" style=\"\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"\""
"string.regexp" = "class=\"string regexp\" style=\"\""
"module" = "class=\"module\" style=\"\""
"comment.block" = "class=\"comment block\" style=\"\""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"\""
"property" = "class=\"property\" style=\"color: #e34e1b; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"\""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"\""
"markup.heading" = "class=\"markup heading\" style=\"\""
"string.special.symbol" = "class=\"string special symbol\" style=\"\""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"\""
"markup.heading.completion" = "class=\"markup heading completion\" style=\"\""
"markup.heading.raw" = "class=\"markup heading raw\" style=\"\""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"\""
"comment.line" = "class=\"comment line\" style=\"\""
"keyword.control.return" = "class=\"keyword control return\" style=\"\""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"\""
