"string.escape" = "class=\"string escape\" style=\"color: #EBCB8B;\""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"color: #81A1C1;\""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #81A1C1;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #B48EAD;\""
"function" = "class=\"function\" style=\"color: #88C0D0;\""
"keyword.function" = "class=\"keyword function\" style=\"color: #81A1C1;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #D8DEE9;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #81A1C1;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #8FBCBB;\""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #ECEFF4;\""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"color: #8FBCBB;\""
"constant.macro" = "class=\"constant macro\" style=\"color: #81A1C1;\""
"keyword" = "class=\"keyword\" style=\"color: #81A1C1;\""
"function.special" = "class=\"function special\" style=\"color: #81A1C1;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #EBCB8B;\""
"string" = "class=\"string\" style=\"color: #A3BE8C;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #88C0D0;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #ECEFF4;\""
"keyword.return" = "class=\"keyword return\" style=\"color: #81A1C1;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #EBCB8B;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #81A1C1;\""
"operator" = "class=\"operator\" style=\"color: #81A1C1; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #A3BE8C;\""
"special" = "class=\"special\" style=\"color: #D8DEE9;\""
"function.macro" = "class=\"function macro\" style=\"color: #81A1C1;\""
"background" = "class=\"background\" style=\"background-color: #2e3440; \""
"punctuation" = "class=\"punctuation\" style=\"color: #ECEFF4;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #616e88; \""
"tag" = "class=\"tag\" style=\"color: #D8DEE9;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #BF616A;\""
"git.delta.moved" = "class=\"git delta moved\" style=\"color: #D08770;\""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"color: #81A1C1;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #8FBCBB;\""
"constructor" = "class=\"constructor\" style=\"color: #88C0D0;\""
"variable" = "class=\"variable\" style=\"color: #D8DEE9;\""
"module" = "class=\"module\" style=\"color: #D8DEE9; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #81A1C1;\""
"string.regex" = "class=\"string regex\" style=\"color: #EBCB8B;\""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #81A1C1;\""
"constant" = "class=\"constant\" style=\"color: #D8DEE9;\""
"string.special" = "class=\"string special\" style=\"color: #EBCB8B;\""
"function.method" = "class=\"function method\" style=\"color: #88C0D0;\""
"type" = "class=\"type\" style=\"color: #D8DEE9;\""
"constant.builtin.character" = "class=\"constant builtin character\" style=\"color: #B48EAD;\""
"attribute" = "class=\"attribute\" style=\"color: #D8DEE9;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #81A1C1;\""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"color: #81A1C1;\""
"variable.builint" = "class=\"variable builint\" style=\"color: #81A1C1;\""
"namespace" = "class=\"namespace\" style=\"color: #D8DEE9;\""
"label" = "class=\"label\" style=\"color: #8FBCBB;\""
