"attribute" = "class=\"attribute\" style=\"color: #5E81AC; \""
"background" = "class=\"background\" style=\"background-color: #ECEFF4; \""
"comment" = "class=\"comment\" style=\"color: #8FBCBB;\""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #B48EAD; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #B48EAD; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #EBCB8B; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #BF616A; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #A3BE8C; \""
"function" = "class=\"function\" style=\"color: #4C566A; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #5E81AC; \""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #5E81AC; \""
"function.method" = "class=\"function method\" style=\"color: #2E3440; \""
"keyword" = "class=\"keyword\" style=\"color: #434C5E; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #434C5E; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #434C5E; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #2E3440; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #D08770; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #4C566A; \""
"markup.quote" = "class=\"markup quote\" style=\"text-decoration: underline; color: #4C566A; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #5E81AC; \""
"module" = "class=\"module\" style=\"color: #5E81AC; \""
"namespace" = "class=\"namespace\" style=\"color: #5E81AC; \""
"operator" = "class=\"operator\" style=\"\""
"string" = "class=\"string\" style=\"color: #A3BE8C;\""
"type" = "class=\"type\" style=\"color: #5E81AC; \""
"variable" = "class=\"variable\" style=\"color: #2E3440; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #4C566A; \""
"variable.other" = "class=\"variable other\" style=\"color: #4C566A; \""
