"attribute" = "style=\"color: #5E81AC; \""
"comment" = "style=\"color: #8FBCBB;\""
"constant.builtin" = "style=\"color: #B48EAD; \""
"constant.numeric" = "style=\"color: #B48EAD; \""
"diff.delta" = "style=\"color: #EBCB8B; \""
"diff.minus" = "style=\"color: #BF616A; \""
"diff.plus" = "style=\"color: #A3BE8C; \""
"function" = "style=\"color: #4C566A; \""
"function.builtin" = "style=\"color: #5E81AC; \""
"function.macro" = "style=\"font-weight: bold; color: #5E81AC; \""
"function.method" = "style=\"color: #2E3440; \""
"keyword" = "style=\"color: #434C5E; \""
"keyword.control" = "style=\"color: #434C5E; \""
"keyword.function" = "style=\"color: #434C5E; \""
"markup.heading" = "style=\"font-weight: bold; color: #2E3440; \""
"markup.link.text" = "style=\"color: #D08770; \""
"markup.link.url" = "style=\"color: #4C566A; \""
"markup.quote" = "style=\"text-decoration: underline; color: #4C566A; \""
"markup.raw" = "style=\"color: #5E81AC; \""
"namespace" = "style=\"color: #5E81AC; \""
"string" = "style=\"color: #A3BE8C;\""
"type" = "style=\"color: #5E81AC; \""
"variable" = "style=\"color: #2E3440; \""
"variable.builtin" = "style=\"color: #4C566A; \""
"variable.other" = "style=\"color: #4C566A; \""
