"attribute" = "style=\"color: #D8DEE9;\""
"comment" = "style=\"text-decoration: underline; color: #616e88; \""
"constant" = "style=\"color: #D8DEE9;\""
"constant.builtin" = "style=\"color: #81A1C1;\""
"constant.builtin.boolean" = "style=\"color: #81A1C1;\""
"constant.builtin.character" = "style=\"color: #B48EAD;\""
"constant.character.escape" = "style=\"color: #EBCB8B;\""
"constant.macro" = "style=\"color: #81A1C1;\""
"constant.numeric" = "style=\"color: #B48EAD;\""
"constructor" = "style=\"color: #88C0D0;\""
"diff.delta" = "style=\"color: #EBCB8B;\""
"diff.minus" = "style=\"color: #BF616A;\""
"diff.plus" = "style=\"color: #A3BE8C;\""
"function" = "style=\"color: #88C0D0;\""
"function.builtin" = "style=\"color: #8FBCBB;\""
"function.macro" = "style=\"color: #81A1C1;\""
"function.method" = "style=\"color: #88C0D0;\""
"function.special" = "style=\"color: #81A1C1;\""
"git.delta.moved" = "style=\"color: #D08770;\""
"keyword" = "style=\"color: #81A1C1;\""
"keyword.control.conditional" = "style=\"color: #81A1C1;\""
"keyword.control.exception" = "style=\"color: #81A1C1;\""
"keyword.control.repeat" = "style=\"color: #81A1C1;\""
"keyword.directive" = "style=\"color: #81A1C1;\""
"keyword.function" = "style=\"color: #81A1C1;\""
"keyword.operator" = "style=\"color: #81A1C1;\""
"keyword.return" = "style=\"color: #81A1C1;\""
"keyword.storage.modifier" = "style=\"color: #81A1C1;\""
"keyword.storage.type" = "style=\"color: #8FBCBB;\""
"label" = "style=\"color: #8FBCBB;\""
"namespace" = "style=\"color: #D8DEE9;\""
"operator" = "style=\"color: #81A1C1;\""
"punctuation" = "style=\"color: #ECEFF4;\""
"punctuation.bracket" = "style=\"color: #ECEFF4;\""
"punctuation.delimiter" = "style=\"color: #ECEFF4;\""
"punctuation.special" = "style=\"color: #81A1C1;\""
"special" = "style=\"color: #D8DEE9;\""
"string" = "style=\"color: #A3BE8C;\""
"string.escape" = "style=\"color: #EBCB8B;\""
"string.regex" = "style=\"color: #EBCB8B;\""
"string.special" = "style=\"color: #EBCB8B;\""
"tag" = "style=\"color: #D8DEE9;\""
"type" = "style=\"color: #D8DEE9;\""
"type.builtin" = "style=\"color: #8FBCBB;\""
"variable" = "style=\"color: #D8DEE9;\""
"variable.builint" = "style=\"color: #81A1C1;\""
"variable.other.member" = "style=\"color: #D8DEE9;\""
"variable.parameter" = "style=\"color: #88C0D0;\""
