"constant.numeric" = "class=\"constant numeric\" style=\"color: #D19A66; \""
"function" = "class=\"function\" style=\"color: #61AFEF; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #E06C75; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #C678DD; \""
"markup.list" = "class=\"markup list\" style=\"color: #E06C75; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #61AFEF; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #E5C07B; \""
"keyword" = "class=\"keyword\" style=\"color: #E06C75; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #E06C75; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #D19A66;\""
"string" = "class=\"string\" style=\"color: #98C379; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #E06C75; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #61AFEF; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #56B6C2; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #C678DD; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #D19A66; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #C678DD; \""
"operator" = "class=\"operator\" style=\"color: #C678DD; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #98C379;\""
"special" = "class=\"special\" style=\"color: #61AFEF; \""
"function.macro" = "class=\"function macro\" style=\"color: #C678DD; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #C678DD; \""
"background" = "class=\"background\" style=\"background-color: #282C34; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #C678DD; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #5C6370; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #E06C75;\""
"constructor" = "class=\"constructor\" style=\"color: #61AFEF; \""
"module" = "class=\"module\" style=\"color: #61AFEF; \""
"constant" = "class=\"constant\" style=\"color: #56B6C2; \""
"type" = "class=\"type\" style=\"color: #E5C07B; \""
"attribute" = "class=\"attribute\" style=\"color: #E5C07B; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #D19A66; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #E06C75; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #98C379; \""
"namespace" = "class=\"namespace\" style=\"color: #61AFEF; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #D19A66; \""
"label" = "class=\"label\" style=\"color: #C678DD; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
