"constant.numeric" = "class=\"constant numeric\" style=\"color: #D19A66; \""
"function" = "class=\"function\" style=\"color: #ABB2BF; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #519FDF; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #ABB2BF; \""
"markup.list" = "class=\"markup list\" style=\"color: #D05C65; \""
"markup.link.label" = "class=\"markup link label\" style=\"color: #ABB2BF; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #519FDF; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #D5B06B; \""
"keyword" = "class=\"keyword\" style=\"color: #B668CD; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #B668CD; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #D19A66;\""
"string" = "class=\"string\" style=\"color: #7DA869; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #ABB2BF; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #D05C65; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #D05C65; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #519FDF; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #B668CD; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #D19A66; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #B668CD; \""
"operator" = "class=\"operator\" style=\"color: #ABB2BF; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #7DA869;\""
"special" = "class=\"special\" style=\"color: #519FDF; \""
"function.macro" = "class=\"function macro\" style=\"color: #B668CD; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #B668CD; \""
"background" = "class=\"background\" style=\"background-color: #16181A; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ABB2BF; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #636C6E; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #D05C65;\""
"constructor" = "class=\"constructor\" style=\"color: #519FDF; \""
"variable" = "class=\"variable\" style=\"color: #ABB2BF; \""
"text" = "class=\"text\" style=\"color: #ABB2BF; \""
"module" = "class=\"module\" style=\"color: #B668CD; \""
"constant" = "class=\"constant\" style=\"color: #D19A66; \""
"type" = "class=\"type\" style=\"color: #D5B06B; \""
"attribute" = "class=\"attribute\" style=\"color: #D5B06B; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #D19A66; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #D05C65; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #7DA869; \""
"namespace" = "class=\"namespace\" style=\"color: #B668CD; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #D19A66; \""
"label" = "class=\"label\" style=\"color: #B668CD; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
