"attribute" = "style=\"color: #D5B06B; \""
"comment" = "style=\"text-decoration: underline; color: #636C6E; \""
"constant" = "style=\"color: #D19A66; \""
"constant.builtin" = "style=\"color: #D19A66; \""
"constant.character.escape" = "style=\"color: #D19A66; \""
"constant.numeric" = "style=\"color: #D19A66; \""
"constructor" = "style=\"color: #519FDF; \""
"diff.delta" = "style=\"color: #D19A66;\""
"diff.minus" = "style=\"color: #D05C65;\""
"diff.plus" = "style=\"color: #7DA869;\""
"function" = "style=\"color: #ABB2BF; \""
"function.builtin" = "style=\"color: #519FDF; \""
"function.macro" = "style=\"color: #B668CD; \""
"keyword" = "style=\"color: #B668CD; \""
"keyword.control" = "style=\"color: #B668CD; \""
"keyword.control.import" = "style=\"color: #B668CD; \""
"keyword.directive" = "style=\"color: #B668CD; \""
"keyword.operator" = "style=\"color: #ABB2BF; \""
"label" = "style=\"color: #B668CD; \""
"markup.bold" = "style=\"font-weight: bold; color: #D19A66; \""
"markup.heading" = "style=\"color: #D05C65; \""
"markup.italic" = "style=\"text-decoration: underline; color: #B668CD; \""
"markup.link.label" = "style=\"color: #ABB2BF; \""
"markup.link.text" = "style=\"color: #ABB2BF; \""
"markup.link.url" = "style=\"color: #519FDF; \""
"markup.list" = "style=\"color: #D05C65; \""
"markup.quote" = "style=\"color: #D5B06B; \""
"markup.raw.block" = "style=\"color: #ABB2BF; \""
"markup.raw.inline" = "style=\"color: #7DA869; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #B668CD; \""
"operator" = "style=\"color: #ABB2BF; \""
"special" = "style=\"color: #519FDF; \""
"string" = "style=\"color: #7DA869; \""
"type" = "style=\"color: #D5B06B; \""
"variable" = "style=\"color: #ABB2BF; \""
"variable.builtin" = "style=\"color: #D05C65; \""
"variable.other.member" = "style=\"color: #519FDF; \""
"variable.parameter" = "style=\"color: #D05C65; \""
