"attribute" = "style=\"color: #E5C07B; \""
"comment" = "style=\"text-decoration: underline; color: #5C6370; \""
"constant" = "style=\"color: #56B6C2; \""
"constant.builtin" = "style=\"color: #D19A66; \""
"constant.character.escape" = "style=\"color: #D19A66; \""
"constant.numeric" = "style=\"color: #D19A66; \""
"constructor" = "style=\"color: #61AFEF; \""
"diff.delta" = "style=\"color: #D19A66;\""
"diff.minus" = "style=\"color: #E06C75;\""
"diff.plus" = "style=\"color: #98C379;\""
"function" = "style=\"color: #61AFEF; \""
"function.builtin" = "style=\"color: #61AFEF; \""
"function.macro" = "style=\"color: #C678DD; \""
"keyword" = "style=\"color: #E06C75; \""
"keyword.control" = "style=\"color: #C678DD; \""
"keyword.control.import" = "style=\"color: #E06C75; \""
"keyword.directive" = "style=\"color: #C678DD; \""
"keyword.operator" = "style=\"color: #C678DD; \""
"label" = "style=\"color: #C678DD; \""
"markup.bold" = "style=\"font-weight: bold; color: #D19A66; \""
"markup.heading" = "style=\"color: #E06C75; \""
"markup.italic" = "style=\"text-decoration: underline; color: #C678DD; \""
"markup.link.text" = "style=\"color: #C678DD; \""
"markup.link.url" = "style=\"color: #56B6C2; \""
"markup.list" = "style=\"color: #E06C75; \""
"markup.quote" = "style=\"color: #E5C07B; \""
"markup.raw.inline" = "style=\"color: #98C379; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #61AFEF; \""
"operator" = "style=\"color: #C678DD; \""
"special" = "style=\"color: #61AFEF; \""
"string" = "style=\"color: #98C379; \""
"type" = "style=\"color: #E5C07B; \""
"variable.builtin" = "style=\"color: #61AFEF; \""
"variable.other.member" = "style=\"color: #E06C75; \""
"variable.parameter" = "style=\"color: #E06C75; \""
