"attribute" = "style=\"color: #FF6F00; \""
"comment" = "style=\"text-decoration: underline; color: #5C6370; \""
"comment.block" = "style=\"text-decoration: underline; color: #5C6370; \""
"comment.block.documentation" = "style=\"text-decoration: underline; color: #5C6370; \""
"comment.line" = "style=\"text-decoration: underline; color: #5C6370; \""
"constant" = "style=\"font-weight: bold; color: #0086C1; \""
"constant.builtin" = "style=\"color: #651FFF; \""
"constant.builtin.boolean" = "style=\"color: #B500A9; \""
"constant.character" = "style=\"color: #24A443; \""
"constant.character.escape" = "style=\"color: #795548; \""
"constant.numeric" = "style=\"color: #795548; \""
"constant.numeric.float" = "style=\"color: #795548; \""
"constant.numeric.integer" = "style=\"color: #795548; \""
"constructor" = "style=\"color: #0061FF; \""
"diff" = "style=\"color: #D50000; \""
"diff.delta" = "style=\"color: #0086C1; \""
"diff.delta.moved" = "style=\"color: #0086C1; \""
"diff.minus" = "style=\"color: #D50000; \""
"diff.plus" = "style=\"color: #24A443; \""
"function" = "style=\"color: #0061FF; \""
"function.builtin" = "style=\"color: #0086C1; \""
"function.macro" = "style=\"font-weight: bold; color: #C2185B; \""
"function.method" = "style=\"color: #0091EA; \""
"function.special" = "style=\"color: #0086C1; \""
"keyword" = "style=\"color: #B500A9; \""
"keyword.control" = "style=\"color: #B500A9; \""
"keyword.control.conditional" = "style=\"font-weight: bold; color: #D50000; \""
"keyword.control.exception" = "style=\"color: #B500A9; \""
"keyword.control.import" = "style=\"color: #D50000; \""
"keyword.control.repeat" = "style=\"font-weight: bold; color: #C2185B; \""
"keyword.control.return" = "style=\"font-weight: bold; color: #651FFF; \""
"keyword.directive" = "style=\"color: #651FFF; \""
"keyword.function" = "style=\"color: #B500A9; \""
"keyword.operator" = "style=\"color: #D50000; \""
"keyword.storage" = "style=\"color: #B500A9; \""
"keyword.storage.modifier" = "style=\"font-weight: bold; color: #B500A9; \""
"keyword.storage.type" = "style=\"color: #B500A9; \""
"label" = "style=\"color: #0086C1; \""
"markup.bold" = "style=\"font-weight: bold; color: #FF6F00; \""
"markup.heading" = "style=\"color: #D50000; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #D50000; \""
"markup.heading.2" = "style=\"text-decoration: underline; font-weight: bold; color: #D35400; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #FF6F00; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #24A443; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #0061FF; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #B500A9; \""
"markup.heading.marker" = "style=\"color: #D50000; \""
"markup.italic" = "style=\"text-decoration: underline; color: #B500A9; \""
"markup.link" = "style=\"color: #0091EA; \""
"markup.link.text" = "style=\"color: #0091EA; \""
"markup.link.url" = "style=\"color: #0086C1; \""
"markup.list" = "style=\"color: #0091EA; \""
"markup.list.checked" = "style=\"color: #24A443; \""
"markup.list.numbered" = "style=\"color: #0091EA; \""
"markup.list.unchecked" = "style=\"color: #0061FF; \""
"markup.list.unnumbered" = "style=\"color: #0091EA; \""
"markup.quote" = "style=\"color: #5C6370; \""
"markup.raw" = "style=\"color: #795548; \""
"markup.raw.block" = "style=\"color: #5C6370; \""
"markup.raw.inline" = "style=\"color: #24A443; \""
"markup.strikethrough" = "style=\"color: #D50000; \""
"module" = "style=\"color: #0061FF; \""
"namespace" = "style=\"color: #0061FF; \""
"operator" = "style=\"color: #D50000; \""
"property" = "style=\"color: #B500A9; \""
"punctuation" = "style=\"color: #282C34; \""
"punctuation.bracket" = "style=\"color: #795548; \""
"punctuation.delimiter" = "style=\"color: #B500A9; \""
"punctuation.special" = "style=\"color: #795548; \""
"special" = "style=\"color: #651FFF; \""
"string" = "style=\"color: #24A443; \""
"string.regexp" = "style=\"color: #B500A9; \""
"string.special" = "style=\"color: #24A443; \""
"string.special.path" = "style=\"color: #0061FF; \""
"string.special.symbol" = "style=\"color: #C2185B; \""
"string.special.url" = "style=\"color: #0091EA; \""
"tag" = "style=\"color: #0086C1; \""
"type" = "style=\"color: #D35400; \""
"type.builtin" = "style=\"color: #FF6F00; \""
"type.enum" = "style=\"color: #0086C1; \""
"type.enum.variant" = "style=\"color: #0086C1; \""
"variable.builtin" = "style=\"color: #0091EA; \""
"variable.other" = "style=\"color: #C2185B; \""
"variable.other.member" = "style=\"color: #C2185B; \""
"variable.parameter" = "style=\"color: #D50000; \""
