"constant.numeric.float" = "class=\"constant numeric float\" style=\"color: #795548; \""
"string.special.path" = "class=\"string special path\" style=\"color: #0061FF; \""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"font-weight: bold; color: #C2185B; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #B500A9; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #795548; \""
"function" = "class=\"function\" style=\"color: #0061FF; \""
"type.enum" = "class=\"type enum\" style=\"color: #0086C1; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #B500A9; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #C2185B; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #D50000; \""
"markup.list" = "class=\"markup list\" style=\"color: #0091EA; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #0086C1; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #5C6370; \""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #24A443; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #795548; \""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"color: #B500A9; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #0061FF; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #FF6F00; \""
"keyword" = "class=\"keyword\" style=\"color: #B500A9; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #D50000; \""
"function.special" = "class=\"function special\" style=\"color: #0086C1; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #0086C1; \""
"string" = "class=\"string\" style=\"color: #24A443; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #5C6370; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #D50000; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #B500A9; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #0091EA; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #0086C1; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #B500A9; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #795548; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #651FFF; \""
"operator" = "class=\"operator\" style=\"color: #D50000; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #24A443; \""
"special" = "class=\"special\" style=\"color: #651FFF; \""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #C2185B; \""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; color: #B500A9; \""
"background" = "class=\"background\" style=\"background-color: #FAFAFA; \""
"punctuation" = "class=\"punctuation\" style=\"color: #282C34; \""
"string.special.url" = "class=\"string special url\" style=\"color: #0091EA; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #0091EA; \""
"constant.numeric.integer" = "class=\"constant numeric integer\" style=\"color: #795548; \""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #5C6370; \""
"tag" = "class=\"tag\" style=\"color: #0086C1; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #0086C1; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #795548; \""
"constant.character" = "class=\"constant character\" style=\"color: #24A443; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #D50000; \""
"markup.list.unchecked" = "class=\"markup list unchecked\" style=\"color: #0061FF; \""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"font-weight: bold; color: #B500A9; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"text-decoration: underline; font-weight: bold; color: #D35400; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #FF6F00; \""
"constructor" = "class=\"constructor\" style=\"color: #0061FF; \""
"markup.list.checked" = "class=\"markup list checked\" style=\"color: #24A443; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #0086C1; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #B500A9; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #B500A9; \""
"module" = "class=\"module\" style=\"color: #0061FF; \""
"markup.link" = "class=\"markup link\" style=\"color: #0091EA; \""
"comment.block" = "class=\"comment block\" style=\"text-decoration: underline; color: #5C6370; \""
"punctuation.special" = "class=\"punctuation special\" style=\"color: #795548; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #B500A9; \""
"constant" = "class=\"constant\" style=\"font-weight: bold; color: #0086C1; \""
"string.special" = "class=\"string special\" style=\"color: #24A443; \""
"property" = "class=\"property\" style=\"color: #B500A9; \""
"function.method" = "class=\"function method\" style=\"color: #0091EA; \""
"type" = "class=\"type\" style=\"color: #D35400; \""
"variable.other" = "class=\"variable other\" style=\"color: #C2185B; \""
"attribute" = "class=\"attribute\" style=\"color: #FF6F00; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #B500A9; \""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #0091EA; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #651FFF; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #D50000; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #D50000; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-weight: bold; color: #D50000; \""
"string.special.symbol" = "class=\"string special symbol\" style=\"color: #C2185B; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #24A443; \""
"namespace" = "class=\"namespace\" style=\"color: #0061FF; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"text-decoration: underline; color: #5C6370; \""
"comment.line" = "class=\"comment line\" style=\"text-decoration: underline; color: #5C6370; \""
"diff" = "class=\"diff\" style=\"color: #D50000; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #FF6F00; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"font-weight: bold; color: #651FFF; \""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #0091EA; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #D50000; \""
"label" = "class=\"label\" style=\"color: #0086C1; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"color: #D50000; \""
