"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"font-weight: bold; color: #8700af; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #d70000; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #d75f00;\""
"function" = "class=\"function\" style=\"color: #444444; \""
"type.enum" = "class=\"type enum\" style=\"color: #444444; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #d70087;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #444444;\""
"keyword.operator" = "class=\"keyword operator\" style=\"font-weight: bold; color: #0087af; \""
"markup.list" = "class=\"markup list\" style=\"color: #0087af;\""
"markup.link.label" = "class=\"markup link label\" style=\"font-weight: bold; color: #008700; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #005faf; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #0087af;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #d75f00; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #444444; \""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"font-weight: bold; color: #0087af; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #8700af; \""
"keyword" = "class=\"keyword\" style=\"color: #d70087; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #d70087; \""
"function.special" = "class=\"function special\" style=\"color: #d75f00; \""
"diff.delta" = "class=\"diff delta\" style=\"background-color: #ffd787; \""
"string" = "class=\"string\" style=\"color: #5f8700;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #444444;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"font-weight: bold; color: #0087af; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #d75f00;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #005faf; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #d70000;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #8700af; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #0087af;\""
"operator" = "class=\"operator\" style=\"color: #0087af; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #008700; background-color: #afffaf; \""
"special" = "class=\"special\" style=\"color: #3e999f;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #5f8700; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #eeeeee; \""
"punctuation" = "class=\"punctuation\" style=\"color: #444444; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d70087;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #878787; \""
"tag" = "class=\"tag\" style=\"color: #0087af; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"font-style: italic; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #5f8700;\""
"constant.character" = "class=\"constant character\" style=\"color: #5f8700; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #af0000; background-color: #ffd7ff; \""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"font-weight: bold; color: #0087af; \""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"font-weight: bold; color: #005f87; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #d75f00; \""
"type.builtin" = "class=\"type builtin\" style=\"font-weight: bold; color: #d70087; \""
"constructor" = "class=\"constructor\" style=\"color: #444444;\""
"variable" = "class=\"variable\" style=\"color: #444444;\""
"keyword.special" = "class=\"keyword special\" style=\"color: #d70000;\""
"text" = "class=\"text\" style=\"color: #444444; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #444444; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #d70087;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #8700af;\""
"module" = "class=\"module\" style=\"color: #005faf; \""
"comment.block" = "class=\"comment block\" style=\"font-style: italic; color: #878787; \""
"punctuation.special" = "class=\"punctuation special\" style=\"font-weight: bold; color: #d70000; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"font-weight: bold; color: #008700; \""
"constant" = "class=\"constant\" style=\"color: #d75f00;\""
"function.method" = "class=\"function method\" style=\"color: #444444; \""
"type" = "class=\"type\" style=\"font-weight: bold; color: #d70087; \""
"attribute" = "class=\"attribute\" style=\"color: #d75f00;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #d75f00; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #5f8700;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #d70087; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #d75f00; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-weight: bold; color: #8700af; \""
"namespace" = "class=\"namespace\" style=\"color: #005faf;\""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-weight: bold; color: #878787; \""
"comment.line" = "class=\"comment line\" style=\"font-style: italic; color: #878787; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #444444; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #d70087; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #d70087; \""
"label" = "class=\"label\" style=\"font-style: italic; font-weight: bold; color: #0087af; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
