"background" = "style=\"background-color: #1c1c1c; \""
"attribute" = "style=\"color: #ffaf00;\""
"comment" = "style=\"text-decoration: underline; color: #808080; \""
"comment.block" = "style=\"text-decoration: underline; color: #808080; \""
"comment.block.documentation" = "style=\"font-weight: bold; color: #808080; \""
"comment.line" = "style=\"text-decoration: underline; color: #808080; \""
"constant" = "style=\"color: #ff5faf;\""
"constant.builtin" = "style=\"color: #d7af5f;\""
"constant.builtin.boolean" = "style=\"font-weight: bold; color: #5faf00; \""
"constant.character" = "style=\"color: #d7af5f; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #af87d7; \""
"constant.numeric" = "style=\"color: #ff5faf;\""
"constructor" = "style=\"color: #d0d0d0;\""
"diff.delta" = "style=\"background-color: #005f5f; \""
"diff.delta.moved" = "style=\"text-decoration: underline; \""
"diff.minus" = "style=\"color: #af005f; background-color: #5f0000; \""
"diff.plus" = "style=\"color: #87d700; background-color: #005f00; \""
"function" = "style=\"color: #d0d0d0; \""
"function.builtin" = "style=\"color: #00afaf; \""
"function.macro" = "style=\"font-weight: bold; color: #d7af5f; \""
"function.method" = "style=\"color: #d0d0d0; \""
"function.special" = "style=\"color: #ffaf00; \""
"keyword" = "style=\"color: #afd700; \""
"keyword.control" = "style=\"color: #5faf5f;\""
"keyword.control.conditional" = "style=\"font-weight: bold; color: #af87d7; \""
"keyword.control.exception" = "style=\"color: #5faf5f; \""
"keyword.control.import" = "style=\"color: #afd700; \""
"keyword.control.repeat" = "style=\"font-weight: bold; color: #af87d7; \""
"keyword.control.return" = "style=\"color: #afd700; \""
"keyword.directive" = "style=\"color: #5fafd7;\""
"keyword.function" = "style=\"color: #afd700;\""
"keyword.operator" = "style=\"font-weight: bold; color: #5fafd7; \""
"keyword.special" = "style=\"color: #5faf5f;\""
"keyword.storage" = "style=\"color: #afd700;\""
"keyword.storage.modifier" = "style=\"font-weight: bold; color: #d7875f; \""
"keyword.storage.modifier.ref" = "style=\"font-weight: bold; color: #5fafd7; \""
"keyword.storage.type" = "style=\"font-weight: bold; color: #5fafd7; \""
"label" = "style=\"text-decoration: underline; font-weight: bold; color: #8787af; \""
"markup.bold" = "style=\"font-weight: bold; color: #d0d0d0; \""
"markup.heading" = "style=\"font-weight: bold; color: #ffaf00; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #afd700; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #ff5faf; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #af87d7; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #ffaf00; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #ffaf00; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #ffaf00; \""
"markup.heading.marker" = "style=\"font-weight: bold; color: #afd700; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"font-weight: bold; color: #5faf00; \""
"markup.link.text" = "style=\"color: #afd700;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #00afaf; \""
"markup.list" = "style=\"color: #5fafd7;\""
"markup.quote" = "style=\"color: #5fafd7;\""
"markup.raw" = "style=\"color: #d7af5f;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #00afaf;\""
"operator" = "style=\"font-weight: bold; color: #5fafd7; \""
"punctuation" = "style=\"color: #d0d0d0; \""
"punctuation.bracket" = "style=\"color: #d0d0d0; \""
"punctuation.delimiter" = "style=\"font-weight: bold; color: #5fafd7; \""
"punctuation.special" = "style=\"font-weight: bold; color: #5faf5f; \""
"special" = "style=\"color: #3e999f;\""
"string" = "style=\"color: #d7af5f;\""
"string.regexp" = "style=\"color: #af87d7;\""
"tag" = "style=\"color: #5fafd7; \""
"type" = "style=\"font-weight: bold; color: #afd700; \""
"type.builtin" = "style=\"font-weight: bold; color: #afd700; \""
"type.enum" = "style=\"color: #d0d0d0; \""
"type.enum.variant" = "style=\"color: #d0d0d0; \""
"variable" = "style=\"color: #d0d0d0;\""
"variable.builtin" = "style=\"color: #ff5faf;\""
"variable.other.member" = "style=\"color: #d0d0d0;\""
"variable.parameter" = "style=\"color: #d0d0d0;\""
