"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"font-weight: bold; color: #af87d7; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #5faf5f; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #ff5faf;\""
"function" = "class=\"function\" style=\"color: #d0d0d0; \""
"type.enum" = "class=\"type enum\" style=\"color: #d0d0d0; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #afd700;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #d0d0d0;\""
"keyword.operator" = "class=\"keyword operator\" style=\"font-weight: bold; color: #5fafd7; \""
"markup.list" = "class=\"markup list\" style=\"color: #5fafd7;\""
"markup.link.label" = "class=\"markup link label\" style=\"font-weight: bold; color: #5faf00; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #00afaf; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #5fafd7;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #ffaf00; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #d0d0d0; \""
"keyword.storage.type" = "class=\"keyword storage type\" style=\"font-weight: bold; color: #5fafd7; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #ffaf00; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #af87d7; \""
"keyword" = "class=\"keyword\" style=\"color: #afd700; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #afd700; \""
"function.special" = "class=\"function special\" style=\"color: #ffaf00; \""
"diff.delta" = "class=\"diff delta\" style=\"background-color: #005f5f; \""
"string" = "class=\"string\" style=\"color: #d7af5f;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #d0d0d0;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"font-weight: bold; color: #5fafd7; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ff5faf;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #00afaf; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #5faf5f;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #af87d7; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #5fafd7;\""
"operator" = "class=\"operator\" style=\"color: #5fafd7; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #87d700; background-color: #005f00; \""
"special" = "class=\"special\" style=\"color: #3e999f;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #d7af5f; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #1c1c1c; \""
"punctuation" = "class=\"punctuation\" style=\"color: #d0d0d0; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #afd700;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #808080; \""
"tag" = "class=\"tag\" style=\"color: #5fafd7; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"font-style: italic; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #d7af5f;\""
"constant.character" = "class=\"constant character\" style=\"color: #d7af5f; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #af005f; background-color: #5f0000; \""
"keyword.storage.modifier.ref" = "class=\"keyword storage modifier ref\" style=\"font-weight: bold; color: #5fafd7; \""
"keyword.storage.modifier" = "class=\"keyword storage modifier\" style=\"font-weight: bold; color: #d7875f; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #ff5faf; \""
"type.builtin" = "class=\"type builtin\" style=\"font-weight: bold; color: #afd700; \""
"constructor" = "class=\"constructor\" style=\"color: #d0d0d0;\""
"variable" = "class=\"variable\" style=\"color: #d0d0d0;\""
"keyword.special" = "class=\"keyword special\" style=\"color: #5faf5f;\""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #d0d0d0; \""
"keyword.storage" = "class=\"keyword storage\" style=\"color: #afd700;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #af87d7;\""
"module" = "class=\"module\" style=\"color: #00afaf; \""
"comment.block" = "class=\"comment block\" style=\"font-style: italic; color: #808080; \""
"punctuation.special" = "class=\"punctuation special\" style=\"font-weight: bold; color: #5faf5f; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"font-weight: bold; color: #5faf00; \""
"constant" = "class=\"constant\" style=\"color: #ff5faf;\""
"function.method" = "class=\"function method\" style=\"color: #d0d0d0; \""
"type" = "class=\"type\" style=\"font-weight: bold; color: #afd700; \""
"attribute" = "class=\"attribute\" style=\"color: #ffaf00;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #ffaf00; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #d7af5f;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #afd700; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #ffaf00; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"font-weight: bold; color: #af87d7; \""
"namespace" = "class=\"namespace\" style=\"color: #00afaf;\""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-weight: bold; color: #808080; \""
"comment.line" = "class=\"comment line\" style=\"font-style: italic; color: #808080; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #d0d0d0; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #afd700; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #afd700; \""
"label" = "class=\"label\" style=\"font-style: italic; font-weight: bold; color: #8787af; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
