"attribute" = "style=\"color: #d75f00;\""
"comment" = "style=\"text-decoration: underline; color: #878787; \""
"comment.block" = "style=\"text-decoration: underline; color: #878787; \""
"comment.block.documentation" = "style=\"font-weight: bold; color: #878787; \""
"comment.line" = "style=\"text-decoration: underline; color: #878787; \""
"constant" = "style=\"color: #d75f00;\""
"constant.builtin" = "style=\"color: #5f8700;\""
"constant.builtin.boolean" = "style=\"font-weight: bold; color: #008700; \""
"constant.character" = "style=\"color: #5f8700; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #8700af; \""
"constant.numeric" = "style=\"color: #d75f00;\""
"constructor" = "style=\"color: #444444;\""
"diff.delta" = "style=\"background-color: #ffd787; \""
"diff.delta.moved" = "style=\"text-decoration: underline; \""
"diff.minus" = "style=\"color: #af0000; background-color: #ffd7ff; \""
"diff.plus" = "style=\"color: #008700; background-color: #afffaf; \""
"function" = "style=\"color: #444444; \""
"function.builtin" = "style=\"color: #005faf; \""
"function.macro" = "style=\"font-weight: bold; color: #5f8700; \""
"function.method" = "style=\"color: #444444; \""
"function.special" = "style=\"color: #d75f00; \""
"keyword" = "style=\"color: #d70087; \""
"keyword.control" = "style=\"color: #d70000;\""
"keyword.control.conditional" = "style=\"font-weight: bold; color: #8700af; \""
"keyword.control.exception" = "style=\"color: #d70000; \""
"keyword.control.import" = "style=\"color: #d70087; \""
"keyword.control.repeat" = "style=\"font-weight: bold; color: #8700af; \""
"keyword.control.return" = "style=\"color: #d70087; \""
"keyword.directive" = "style=\"color: #0087af;\""
"keyword.function" = "style=\"color: #d70087;\""
"keyword.operator" = "style=\"font-weight: bold; color: #0087af; \""
"keyword.special" = "style=\"color: #d70000;\""
"keyword.storage" = "style=\"color: #d70087;\""
"keyword.storage.modifier" = "style=\"font-weight: bold; color: #005f87; \""
"keyword.storage.modifier.ref" = "style=\"font-weight: bold; color: #0087af; \""
"keyword.storage.type" = "style=\"font-weight: bold; color: #0087af; \""
"label" = "style=\"text-decoration: underline; font-weight: bold; color: #0087af; \""
"markup.bold" = "style=\"font-weight: bold; color: #444444; \""
"markup.heading" = "style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #d70087; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #8700af; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #d75f00; \""
"markup.heading.marker" = "style=\"font-weight: bold; color: #d70087; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.label" = "style=\"font-weight: bold; color: #008700; \""
"markup.link.text" = "style=\"color: #d70087;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #005faf; \""
"markup.list" = "style=\"color: #0087af;\""
"markup.quote" = "style=\"color: #0087af;\""
"markup.raw" = "style=\"color: #5f8700;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #005faf;\""
"operator" = "style=\"font-weight: bold; color: #0087af; \""
"punctuation" = "style=\"color: #444444; \""
"punctuation.bracket" = "style=\"color: #444444; \""
"punctuation.delimiter" = "style=\"font-weight: bold; color: #0087af; \""
"punctuation.special" = "style=\"font-weight: bold; color: #d70000; \""
"special" = "style=\"color: #3e999f;\""
"string" = "style=\"color: #5f8700;\""
"string.regexp" = "style=\"color: #8700af;\""
"tag" = "style=\"color: #0087af; \""
"type" = "style=\"font-weight: bold; color: #d70087; \""
"type.builtin" = "style=\"font-weight: bold; color: #d70087; \""
"type.enum" = "style=\"color: #444444; \""
"type.enum.variant" = "style=\"color: #444444; \""
"variable" = "style=\"color: #444444;\""
"variable.builtin" = "style=\"color: #d75f00;\""
"variable.other.member" = "style=\"color: #444444;\""
"variable.parameter" = "style=\"color: #444444;\""
