"string.special.path" = "class=\"string special path\" style=\"color: #00B3C2;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #00B3C2;\""
"function" = "class=\"function\" style=\"color: #61A3E6;\""
"markup.list" = "class=\"markup list\" style=\"color: #9E9E9E;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #50B584;\""
"keyword" = "class=\"keyword\" style=\"color: #D080B6;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #00B3C2;\""
"string" = "class=\"string\" style=\"color: #9CA748;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #DF7F78;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; \""
"operator" = "class=\"operator\" style=\"color: #D080B6; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #50B584;\""
"function.macro" = "class=\"function macro\" style=\"color: #A48FE1;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #24272B; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9E9E9E;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #D080B6;\""
"comment" = "class=\"comment\" style=\"color: #636363;\""
"tag" = "class=\"tag\" style=\"color: #61A3E6;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #CE9042;\""
"constant.character" = "class=\"constant character\" style=\"color: #A48FE1;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #DF7F78;\""
"variable" = "class=\"variable\" style=\"color: #9E9E9E;\""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #50B584;\""
"module" = "class=\"module\" style=\"color: #9E9E9E; \""
"constant" = "class=\"constant\" style=\"color: #A48FE1;\""
"type" = "class=\"type\" style=\"color: #50B584;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #CECECE; \""
"string.special.symbol" = "class=\"string special symbol\" style=\"color: #00B3C2;\""
"namespace" = "class=\"namespace\" style=\"color: #9E9E9E;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"label" = "class=\"label\" style=\"color: #61A3E6;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
