"comment" = "style=\"color: #636363;\""
"constant" = "style=\"color: #A48FE1;\""
"constant.character" = "style=\"color: #A48FE1;\""
"constant.numeric" = "style=\"color: #00B3C2;\""
"diff.delta" = "style=\"color: #00B3C2;\""
"diff.minus" = "style=\"color: #DF7F78;\""
"diff.plus" = "style=\"color: #50B584;\""
"function" = "style=\"color: #61A3E6;\""
"function.macro" = "style=\"color: #A48FE1;\""
"keyword" = "style=\"color: #D080B6;\""
"label" = "style=\"color: #61A3E6;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #CECECE; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #D080B6;\""
"markup.link.url" = "style=\"\""
"markup.list" = "style=\"color: #9E9E9E;\""
"markup.quote" = "style=\"color: #50B584;\""
"markup.raw" = "style=\"color: #CE9042;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #9E9E9E;\""
"operator" = "style=\"color: #D080B6;\""
"punctuation" = "style=\"color: #9E9E9E;\""
"string" = "style=\"color: #9CA748;\""
"string.special.path" = "style=\"color: #00B3C2;\""
"string.special.symbol" = "style=\"color: #00B3C2;\""
"tag" = "style=\"color: #61A3E6;\""
"type" = "style=\"color: #50B584;\""
"type.enum.variant" = "style=\"color: #50B584;\""
"variable" = "style=\"color: #9E9E9E;\""
"variable.builtin" = "style=\"color: #DF7F78;\""
