"markup.raw.inline.hover" = "class=\"markup raw inline hover\" style=\"color: #6FC475; \""
"string.special.path" = "class=\"string special path\" style=\"color: #FF9500; \""
"keyword.control.repeat" = "class=\"keyword control repeat\" style=\"color: #6dd2fa; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"color: #F78C6C; \""
"markup.normal" = "class=\"markup normal\" style=\"color: #6dd2fa; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #F78C6C; \""
"function" = "class=\"function\" style=\"color: #8DEEF9; \""
"keyword.function" = "class=\"keyword function\" style=\"color: #F78C6C; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #FFD68A; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #6dd2fa; \""
"markup.list" = "class=\"markup list\" style=\"color: #73C48F; \""
"markup.link.label" = "class=\"markup link label\" style=\"color: #8DEEF9; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #8DEEF9; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #6dd2fa; \""
"markup.heading.4" = "class=\"markup heading 4\" style=\"color: #FFB950; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #FDAF1F; \""
"markup.normal.completion" = "class=\"markup normal completion\" style=\"background-color: #3E3B39; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"color: #FFB340; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"color: #FFC166; \""
"keyword" = "class=\"keyword\" style=\"color: #8DEEF9; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #F78C6C; \""
"function.special" = "class=\"function special\" style=\"color: #4AAAD6; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #4d4ddd; \""
"string" = "class=\"string\" style=\"color: #73C48F; \""
"markup.raw.block" = "class=\"markup raw block\" style=\"color: #FFD68A; background-color: #4b4845; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #FFFFFF; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #8DEEF9; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #6dd2fa; \""
"variable.function" = "class=\"variable function\" style=\"color: #6dd2fa; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #6dd2fa; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #6dd2fa; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #6dd2fa; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #6dd2fa; \""
"operator" = "class=\"operator\" style=\"color: #FDC33B; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #4dd44d; \""
"special" = "class=\"special\" style=\"color: #FF9500; \""
"function.macro" = "class=\"function macro\" style=\"color: #CFCFCF; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #3E3B39; \""
"punctuation" = "class=\"punctuation\" style=\"color: #6dd2fa; \""
"string.special.url" = "class=\"string special url\" style=\"color: #FF9500; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #39B7C7; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #A0B4A7; \""
"markup.normal.raw" = "class=\"markup normal raw\" style=\"background-color: #3E3B39; \""
"tag" = "class=\"tag\" style=\"color: #8DEEF9; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #dd4ddd; \""
"markup.raw" = "class=\"markup raw\" style=\"background-color: #3E3B39; \""
"constant.character" = "class=\"constant character\" style=\"color: #6FC475; \""
"markup.raw.inline.completion" = "class=\"markup raw inline completion\" style=\"color: #73C48F; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #dd4d4d; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"color: #FFC26C; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #FFCB6B; \""
"constructor" = "class=\"constructor\" style=\"color: #4AAAD6; \""
"variable" = "class=\"variable\" style=\"color: #DEDEDE; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #FFCB6B; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #6dd2fa; \""
"module" = "class=\"module\" style=\"color: ; \""
"markup.link" = "class=\"markup link\" style=\"color: #4AAAD6; \""
"comment.block" = "class=\"comment block\" style=\"font-style: italic; color: #A0B4A7; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #F96964; \""
"constant" = "class=\"constant\" style=\"color: #DDFFDD; \""
"string.special" = "class=\"string special\" style=\"color: #FF9500; \""
"function.method" = "class=\"function method\" style=\"color: #8DEEF9; \""
"type" = "class=\"type\" style=\"color: #F78C6C; \""
"attribute" = "class=\"attribute\" style=\"color: #FFCB6B; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"color: #FFAD34; \""
"markup.list.unnumbered" = "class=\"markup list unnumbered\" style=\"color: #73C48F; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #F96964; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"color: #FFC977; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #73C48F; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"color: #6dd2fa; \""
"string.special.symbol" = "class=\"string special symbol\" style=\"color: #FF9500; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #6dd2fa; \""
"markup.heading.completion" = "class=\"markup heading completion\" style=\"color: #73C48F; \""
"namespace" = "class=\"namespace\" style=\"color: #FFCB6B; \""
"markup.heading.raw" = "class=\"markup heading raw\" style=\"background-color: #3E3B39; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-style: italic; color: #A0B4A7; \""
"comment.line" = "class=\"comment line\" style=\"font-style: italic; color: #A0B4A7; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"color: #6dd2fa; \""
"markup.list.numbered" = "class=\"markup list numbered\" style=\"color: #73C48F; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #FDAF1F; \""
"label" = "class=\"label\" style=\"color: #6FC475; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
