"background" = "style=\"background-color: #3E3B39; \""
"attribute" = "style=\"color: #FFCB6B; \""
"comment" = "style=\"text-decoration: underline; color: #A0B4A7; \""
"comment.block" = "style=\"text-decoration: underline; color: #A0B4A7; \""
"comment.block.documentation" = "style=\"text-decoration: underline; color: #A0B4A7; \""
"comment.line" = "style=\"text-decoration: underline; color: #A0B4A7; \""
"constant" = "style=\"color: #DDFFDD; \""
"constant.builtin" = "style=\"color: #F96964; \""
"constant.builtin.boolean" = "style=\"color: #F96964; \""
"constant.character" = "style=\"color: #6FC475; \""
"constant.character.escape" = "style=\"color: #6dd2fa; \""
"constant.numeric" = "style=\"color: #F78C6C; \""
"constructor" = "style=\"color: #4AAAD6; \""
"diff.delta" = "style=\"color: #4d4ddd; \""
"diff.delta.moved" = "style=\"color: #dd4ddd; \""
"diff.minus" = "style=\"color: #dd4d4d; \""
"diff.plus" = "style=\"color: #4dd44d; \""
"function" = "style=\"color: #8DEEF9; \""
"function.builtin" = "style=\"color: #8DEEF9; \""
"function.macro" = "style=\"color: #CFCFCF; \""
"function.method" = "style=\"color: #8DEEF9; \""
"function.special" = "style=\"color: #4AAAD6; \""
"keyword" = "style=\"color: #8DEEF9; \""
"keyword.control" = "style=\"color: #6dd2fa; \""
"keyword.control.conditional" = "style=\"color: #6dd2fa; \""
"keyword.control.exception" = "style=\"color: #F78C6C; \""
"keyword.control.import" = "style=\"color: #F78C6C; \""
"keyword.control.repeat" = "style=\"color: #6dd2fa; \""
"keyword.control.return" = "style=\"color: #6dd2fa; \""
"keyword.directive" = "style=\"color: #6dd2fa; \""
"keyword.function" = "style=\"color: #F78C6C; \""
"keyword.operator" = "style=\"color: #6dd2fa; \""
"label" = "style=\"color: #6FC475; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"color: #73C48F; \""
"markup.heading.1" = "style=\"color: #FFC977; \""
"markup.heading.2" = "style=\"color: #FFC26C; \""
"markup.heading.3" = "style=\"color: #FFC166; \""
"markup.heading.4" = "style=\"color: #FFB950; \""
"markup.heading.5" = "style=\"color: #FFB340; \""
"markup.heading.6" = "style=\"color: #FFAD34; \""
"markup.heading.completion" = "style=\"color: #73C48F; \""
"markup.heading.marker" = "style=\"color: #FDAF1F; \""
"markup.heading.raw" = "style=\"background-color: #3E3B39; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link" = "style=\"color: #4AAAD6; \""
"markup.link.label" = "style=\"color: #8DEEF9; \""
"markup.link.text" = "style=\"color: #39B7C7; \""
"markup.link.url" = "style=\"color: #6dd2fa; \""
"markup.list" = "style=\"color: #73C48F; \""
"markup.list.numbered" = "style=\"color: #73C48F; \""
"markup.list.unnumbered" = "style=\"color: #73C48F; \""
"markup.normal" = "style=\"color: #6dd2fa; \""
"markup.normal.completion" = "style=\"background-color: #3E3B39; \""
"markup.normal.raw" = "style=\"background-color: #3E3B39; \""
"markup.quote" = "style=\"color: #6dd2fa; \""
"markup.raw" = "style=\"background-color: #3E3B39; \""
"markup.raw.block" = "style=\"color: #FFD68A; background-color: #4b4845; \""
"markup.raw.inline" = "style=\"color: #6dd2fa; \""
"markup.raw.inline.completion" = "style=\"color: #73C48F; \""
"markup.raw.inline.hover" = "style=\"color: #6FC475; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"background-color: #FFCB6B; \""
"namespace" = "style=\"color: #FFCB6B; \""
"operator" = "style=\"color: #FDC33B; \""
"punctuation" = "style=\"color: #6dd2fa; \""
"punctuation.bracket" = "style=\"color: #FDAF1F; \""
"punctuation.delimiter" = "style=\"color: #8DEEF9; \""
"special" = "style=\"color: #FF9500; \""
"string" = "style=\"color: #73C48F; \""
"string.regexp" = "style=\"color: #6dd2fa; \""
"string.special" = "style=\"color: #FF9500; \""
"string.special.path" = "style=\"color: #FF9500; \""
"string.special.symbol" = "style=\"color: #FF9500; \""
"string.special.url" = "style=\"color: #FF9500; \""
"tag" = "style=\"color: #8DEEF9; \""
"type" = "style=\"color: #F78C6C; \""
"type.builtin" = "style=\"color: #FFCB6B; \""
"type.enum.variant" = "style=\"color: #FFCB6B; \""
"variable" = "style=\"color: #DEDEDE; \""
"variable.builtin" = "style=\"color: #6dd2fa; \""
"variable.function" = "style=\"color: #6dd2fa; \""
"variable.other.member" = "style=\"color: #FFD68A; \""
"variable.parameter" = "style=\"color: #FFFFFF; \""
