"constant.numeric" = "class=\"constant numeric\" style=\"color: #de9bc8;\""
"function" = "class=\"function\" style=\"color: #d1d1d1;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #d1d1d1;\""
"markup.list" = "class=\"markup list\" style=\"color: #b6b6b5;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #8db4d4;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #b6b6b5; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #767675; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #b6b6b5; \""
"keyword" = "class=\"keyword\" style=\"color: #8db4d4;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #94c9b2;\""
"string" = "class=\"string\" style=\"color: #7bb099;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #eaeaea;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #767675;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #a6cded;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: #7bb099; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #de9bc8;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #de9bc8;\""
"operator" = "class=\"operator\" style=\"color: #ffc591; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #7aae98;\""
"special" = "class=\"special\" style=\"color: #ffc591;\""
"function.macro" = "class=\"function macro\" style=\"color: #8db4d4;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #1a1a19; \""
"punctuation" = "class=\"punctuation\" style=\"color: #767675;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #8db4d4;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #6a6a69; \""
"tag" = "class=\"tag\" style=\"color: #ffc591;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #ffc591;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ffafa5;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #b6b6b5; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #de9bc8;\""
"constructor" = "class=\"constructor\" style=\"color: #ffc591;\""
"variable" = "class=\"variable\" style=\"color: #d1d1d1;\""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #de9bc8;\""
"string.regexp" = "class=\"string regexp\" style=\"color: #61957f;\""
"module" = "class=\"module\" style=\"color: #8db4d4; \""
"constant" = "class=\"constant\" style=\"color: #d1d1d1;\""
"string.special" = "class=\"string special\" style=\"color: #8db4d4;\""
"type" = "class=\"type\" style=\"color: #eaeaea;\""
"attribute" = "class=\"attribute\" style=\"color: #7bb099;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #767675; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #d1d1d1;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #d1d1d1; \""
"keyword.control.conditional" = "class=\"keyword control conditional\" style=\"text-decoration: underline; color: #8db4d4; \""
"namespace" = "class=\"namespace\" style=\"text-decoration: underline; color: #8db4d4; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #b6b6b5; \""
"label" = "class=\"label\" style=\"color: #ffc591;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
