"background" = "style=\"background-color: #1a1a19; \""
"attribute" = "style=\"color: #7bb099;\""
"comment" = "style=\"text-decoration: underline; color: #6a6a69; \""
"constant" = "style=\"color: #d1d1d1;\""
"constant.builtin" = "style=\"color: #d1d1d1;\""
"constant.character.escape" = "style=\"color: #de9bc8;\""
"constant.numeric" = "style=\"color: #de9bc8;\""
"constructor" = "style=\"color: #ffc591;\""
"diff.delta" = "style=\"color: #94c9b2;\""
"diff.minus" = "style=\"color: #ffafa5;\""
"diff.plus" = "style=\"color: #7aae98;\""
"function" = "style=\"color: #d1d1d1;\""
"function.builtin" = "style=\"color: #8db4d4;\""
"function.macro" = "style=\"color: #8db4d4;\""
"keyword" = "style=\"color: #8db4d4;\""
"keyword.control.conditional" = "style=\"text-decoration: underline; color: #8db4d4; \""
"keyword.directive" = "style=\"color: #de9bc8;\""
"label" = "style=\"color: #ffc591;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #d1d1d1; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #b6b6b5; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #b6b6b5; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #b6b6b5; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #767675; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #767675; \""
"markup.heading.marker" = "style=\"color: #b6b6b5; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #8db4d4;\""
"markup.link.url" = "style=\"color: #7bb099; \""
"markup.list" = "style=\"color: #b6b6b5;\""
"markup.raw" = "style=\"color: #ffc591;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"text-decoration: underline; color: #8db4d4; \""
"operator" = "style=\"color: #ffc591;\""
"punctuation" = "style=\"color: #767675;\""
"punctuation.delimiter" = "style=\"color: #767675;\""
"special" = "style=\"color: #ffc591;\""
"string" = "style=\"color: #7bb099;\""
"string.regexp" = "style=\"color: #61957f;\""
"string.special" = "style=\"color: #8db4d4;\""
"tag" = "style=\"color: #ffc591;\""
"type" = "style=\"color: #eaeaea;\""
"type.builtin" = "style=\"color: #de9bc8;\""
"type.enum.variant" = "style=\"color: #de9bc8;\""
"variable" = "style=\"color: #d1d1d1;\""
"variable.builtin" = "style=\"color: #a6cded;\""
"variable.other.member" = "style=\"color: #d1d1d1;\""
"variable.parameter" = "style=\"color: #eaeaea;\""
