"debug" = "class=\"debug\" style=\"color: #ebbcba;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #f6c177;\""
"function" = "class=\"function\" style=\"color: #ebbcba;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #908caa;\""
"markup.list" = "class=\"markup list\" style=\"color: #6e6a86;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #908caa;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #eb6f92;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #908caa;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #f6c177; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #31748f; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #ebbcba; \""
"keyword" = "class=\"keyword\" style=\"color: #31748f;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #524f67;\""
"string" = "class=\"string\" style=\"color: #f6c177;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #c4a7e7;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #eb6f92;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #c4a7e7; color: #c4a7e7; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #31748f;\""
"operator" = "class=\"operator\" style=\"color: #908caa; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #9ccfd8;\""
"special" = "class=\"special\" style=\"color: #ebbcba;\""
"markup.italic" = "class=\"markup italic\" style=\"text-decoration: underline; \""
"background" = "class=\"background\" style=\"background-color: #191724; \""
"punctuation" = "class=\"punctuation\" style=\"color: #908caa;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #e0def4;\""
"comment" = "class=\"comment\" style=\"text-decoration: underline; color: #6e6a86; \""
"tag" = "class=\"tag\" style=\"color: #9ccfd8;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #908caa;\""
"constant.character" = "class=\"constant character\" style=\"color: #f6c177;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #eb6f92;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #9ccfd8; \""
"constructor" = "class=\"constructor\" style=\"color: #9ccfd8;\""
"variable" = "class=\"variable\" style=\"color: #e0def4;\""
"module" = "class=\"module\" style=\"color: #c4a7e7; \""
"markup.link" = "class=\"markup link\" style=\"color: #c4a7e7;\""
"constant" = "class=\"constant\" style=\"color: #9ccfd8;\""
"type" = "class=\"type\" style=\"color: #9ccfd8;\""
"attribute" = "class=\"attribute\" style=\"color: #c4a7e7;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #9ccfd8; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #ebbcba;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #c4a7e7; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #c4a7e7; \""
"namespace" = "class=\"namespace\" style=\"color: #c4a7e7;\""
"diff" = "class=\"diff\" style=\"color: #26233a;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #6e6a86;\""
"label" = "class=\"label\" style=\"color: #9ccfd8;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
