"background" = "style=\"background-color: #faf4ed; \""
"attribute" = "style=\"color: #907aa9;\""
"comment" = "style=\"text-decoration: underline; color: #9893a5; \""
"constant" = "style=\"color: #56949f;\""
"constant.builtin" = "style=\"color: #d7827e;\""
"constant.character" = "style=\"color: #ea9d34;\""
"constant.character.escape" = "style=\"color: #286983;\""
"constant.numeric" = "style=\"color: #ea9d34;\""
"constructor" = "style=\"color: #56949f;\""
"debug" = "style=\"color: #d7827e;\""
"diff" = "style=\"color: #f2e9e1;\""
"diff.delta" = "style=\"color: #cecacd;\""
"diff.minus" = "style=\"color: #b4637a;\""
"diff.plus" = "style=\"color: #56949f;\""
"function" = "style=\"color: #d7827e;\""
"function.builtin" = "style=\"color: #b4637a;\""
"keyword" = "style=\"color: #286983;\""
"keyword.operator" = "style=\"color: #797593;\""
"label" = "style=\"color: #56949f;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #907aa9; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #907aa9; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #56949f; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #d7827e; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #ea9d34; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #286983; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #56949f; \""
"markup.heading.marker" = "style=\"color: #9893a5;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link" = "style=\"color: #907aa9;\""
"markup.link.label" = "style=\"color: #797593;\""
"markup.link.text" = "style=\"color: #575279;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #907aa9; color: #907aa9; \""
"markup.list" = "style=\"color: #9893a5;\""
"markup.quote" = "style=\"color: #797593;\""
"markup.raw" = "style=\"color: #797593;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #907aa9;\""
"operator" = "style=\"color: #797593;\""
"punctuation" = "style=\"color: #797593;\""
"special" = "style=\"color: #d7827e;\""
"string" = "style=\"color: #ea9d34;\""
"tag" = "style=\"color: #56949f;\""
"type" = "style=\"color: #56949f;\""
"variable" = "style=\"color: #575279;\""
"variable.builtin" = "style=\"color: #b4637a;\""
"variable.parameter" = "style=\"color: #907aa9;\""
