"attribute" = "style=\"color: #c4a7e7;\""
"comment" = "style=\"text-decoration: underline; color: #6e6a86; \""
"constant" = "style=\"color: #9ccfd8;\""
"constant.builtin" = "style=\"color: #ebbcba;\""
"constant.character" = "style=\"color: #f6c177;\""
"constant.character.escape" = "style=\"color: #31748f;\""
"constant.numeric" = "style=\"color: #f6c177;\""
"constructor" = "style=\"color: #9ccfd8;\""
"debug" = "style=\"color: #ebbcba;\""
"diff" = "style=\"color: #26233a;\""
"diff.delta" = "style=\"color: #524f67;\""
"diff.minus" = "style=\"color: #eb6f92;\""
"diff.plus" = "style=\"color: #9ccfd8;\""
"function" = "style=\"color: #ebbcba;\""
"function.builtin" = "style=\"color: #eb6f92;\""
"keyword" = "style=\"color: #31748f;\""
"keyword.operator" = "style=\"color: #908caa;\""
"label" = "style=\"color: #9ccfd8;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading" = "style=\"font-weight: bold; color: #c4a7e7; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #c4a7e7; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #9ccfd8; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #ebbcba; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #f6c177; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #31748f; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #9ccfd8; \""
"markup.heading.marker" = "style=\"color: #6e6a86;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link" = "style=\"color: #c4a7e7;\""
"markup.link.label" = "style=\"color: #908caa;\""
"markup.link.text" = "style=\"color: #e0def4;\""
"markup.link.url" = "style=\"text-decoration: underline; color: #c4a7e7; color: #c4a7e7; \""
"markup.list" = "style=\"color: #6e6a86;\""
"markup.quote" = "style=\"color: #908caa;\""
"markup.raw" = "style=\"color: #908caa;\""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #c4a7e7;\""
"operator" = "style=\"color: #908caa;\""
"punctuation" = "style=\"color: #908caa;\""
"special" = "style=\"color: #ebbcba;\""
"string" = "style=\"color: #f6c177;\""
"tag" = "style=\"color: #9ccfd8;\""
"type" = "style=\"color: #9ccfd8;\""
"variable" = "style=\"color: #e0def4;\""
"variable.builtin" = "style=\"color: #eb6f92;\""
"variable.parameter" = "style=\"color: #c4a7e7;\""
