"debug" = "class=\"debug\" style=\"color: #d7827e;\""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #ea9d34;\""
"function" = "class=\"function\" style=\"color: #d7827e;\""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #797593;\""
"markup.list" = "class=\"markup list\" style=\"color: #9893a5;\""
"markup.link.label" = "class=\"markup link label\" style=\"color: #797593;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #b4637a;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #797593;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #ea9d34; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #286983; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #d7827e; \""
"keyword" = "class=\"keyword\" style=\"color: #286983;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #cecacd;\""
"string" = "class=\"string\" style=\"color: #ea9d34;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #907aa9;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #b4637a;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #907aa9; color: #907aa9; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #286983;\""
"operator" = "class=\"operator\" style=\"color: #797593; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #56949f;\""
"special" = "class=\"special\" style=\"color: #d7827e;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"background\" style=\"background-color: #faf4ed; \""
"punctuation" = "class=\"punctuation\" style=\"color: #797593;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #575279;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #9893a5; \""
"tag" = "class=\"tag\" style=\"color: #56949f;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #797593;\""
"constant.character" = "class=\"constant character\" style=\"color: #ea9d34;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #b4637a;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #56949f; \""
"constructor" = "class=\"constructor\" style=\"color: #56949f;\""
"variable" = "class=\"variable\" style=\"color: #575279;\""
"module" = "class=\"module\" style=\"color: #907aa9; \""
"markup.link" = "class=\"markup link\" style=\"color: #907aa9;\""
"constant" = "class=\"constant\" style=\"color: #56949f;\""
"type" = "class=\"type\" style=\"color: #56949f;\""
"attribute" = "class=\"attribute\" style=\"color: #907aa9;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #56949f; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #d7827e;\""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #907aa9; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #907aa9; \""
"namespace" = "class=\"namespace\" style=\"color: #907aa9;\""
"diff" = "class=\"diff\" style=\"color: #f2e9e1;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #9893a5;\""
"label" = "class=\"label\" style=\"color: #56949f;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
