"function" = "class=\"function\" style=\"color: #3f4b34;\""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #3f5673;\""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #9a7d0e; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #323437;\""
"keyword" = "class=\"keyword\" style=\"color: #621d28;\""
"variable.property" = "class=\"variable property\" style=\"color: #9a7d0e;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #6a89af; \""
"string" = "class=\"string\" style=\"color: #323437;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #9a7d0e;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #646669;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #3f5673;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: ;\""
"operator" = "class=\"operator\" style=\"color: #aaaeb3; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #86b365; \""
"special" = "class=\"special\" style=\"color: #57320f;\""
"function.macro" = "class=\"function macro\" style=\"color: #455054;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #9a7d0e; \""
"background" = "class=\"background\" style=\"background-color: #e1e1e3; \""
"punctuation" = "class=\"punctuation\" style=\"color: #aaaeb3;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #e06c75;\""
"comment" = "class=\"comment\" style=\"color: #646669;\""
"tag" = "class=\"tag\" style=\"color: #9a7d0e;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #323437; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #da3333; \""
"constructor" = "class=\"constructor\" style=\"color: #9a7d0e;\""
"variable" = "class=\"variable\" style=\"color: #9a7d0e;\""
"module" = "class=\"module\" style=\"color: #3f5673; \""
"constant" = "class=\"constant\" style=\"color: #534059;\""
"type" = "class=\"type\" style=\"color: #9a7d0e;\""
"attribute" = "class=\"attribute\" style=\"color: #455054;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #534059; \""
"escape" = "class=\"escape\" style=\"color: #57320f;\""
"number" = "class=\"number\" style=\"color: #534059;\""
"namespace" = "class=\"namespace\" style=\"color: #323437;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #57320f; \""
"label" = "class=\"label\" style=\"color: #455054;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
