"background" = "style=\"background-color: #e1e1e3; \""
"attribute" = "style=\"color: #455054;\""
"comment" = "style=\"color: #646669;\""
"constant" = "style=\"color: #534059;\""
"constructor" = "style=\"color: #9a7d0e;\""
"diff.delta" = "style=\"color: #6a89af; \""
"diff.minus" = "style=\"color: #da3333; \""
"diff.plus" = "style=\"color: #86b365; \""
"escape" = "style=\"color: #57320f;\""
"function" = "style=\"color: #3f4b34;\""
"function.builtin" = "style=\"color: #3f5673;\""
"function.macro" = "style=\"color: #455054;\""
"keyword" = "style=\"color: #621d28;\""
"label" = "style=\"color: #455054;\""
"markup.bold" = "style=\"font-weight: bold; color: #57320f; \""
"markup.heading" = "style=\"font-weight: bold; color: #534059; \""
"markup.italic" = "style=\"text-decoration: underline; color: #9a7d0e; \""
"markup.link.text" = "style=\"color: #e06c75;\""
"markup.link.url" = "style=\"color: ;\""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"text-decoration: underline; color: #9a7d0e; \""
"markup.raw" = "style=\"color: #323437; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #3f5673;\""
"namespace" = "style=\"color: #323437;\""
"number" = "style=\"color: #534059;\""
"operator" = "style=\"color: #aaaeb3;\""
"punctuation" = "style=\"color: #aaaeb3;\""
"punctuation.bracket" = "style=\"color: #323437;\""
"punctuation.delimiter" = "style=\"color: #646669;\""
"special" = "style=\"color: #57320f;\""
"string" = "style=\"color: #323437;\""
"tag" = "style=\"color: #9a7d0e;\""
"type" = "style=\"color: #9a7d0e;\""
"variable" = "style=\"color: #9a7d0e;\""
"variable.builtin" = "style=\"color: #3f5673;\""
"variable.parameter" = "style=\"color: #9a7d0e;\""
"variable.property" = "style=\"color: #9a7d0e;\""
