"background" = "style=\"background-color: #323437; \""
"attribute" = "style=\"color: #b9c2c6;\""
"comment" = "style=\"color: #646669;\""
"constant" = "style=\"color: #d0c4d4;\""
"constructor" = "style=\"color: #e2b714;\""
"diff.delta" = "style=\"color: #dd8a3c; \""
"diff.minus" = "style=\"color: #ca4754; \""
"diff.plus" = "style=\"color: #e5eae1; \""
"escape" = "style=\"color: #dd8a3c;\""
"function" = "style=\"color: #e5eae1;\""
"function.builtin" = "style=\"color: #bdcadb;\""
"function.macro" = "style=\"color: #b9c2c6;\""
"keyword" = "style=\"color: #f9ebed;\""
"label" = "style=\"color: #b9c2c6;\""
"markup.bold" = "style=\"font-weight: bold; color: #dd8a3c; \""
"markup.heading" = "style=\"font-weight: bold; color: #d0c4d4; \""
"markup.italic" = "style=\"text-decoration: underline; color: #e2b714; \""
"markup.link.text" = "style=\"color: #e06c75;\""
"markup.link.url" = "style=\"color: ;\""
"markup.list" = "style=\"color: ;\""
"markup.quote" = "style=\"text-decoration: underline; color: #e2b714; \""
"markup.raw" = "style=\"color: #d1d0c5; \""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #bdcadb;\""
"namespace" = "style=\"color: #d1d0c5;\""
"number" = "style=\"color: #d0c4d4;\""
"operator" = "style=\"color: #aaaeb3;\""
"punctuation" = "style=\"color: #aaaeb3;\""
"punctuation.bracket" = "style=\"color: #d1d0c5;\""
"punctuation.delimiter" = "style=\"color: #6d7278;\""
"special" = "style=\"color: #dd8a3c;\""
"string" = "style=\"color: #d1d0c5;\""
"tag" = "style=\"color: #e2b714;\""
"type" = "style=\"color: #e2b714;\""
"variable" = "style=\"color: #e2b714;\""
"variable.builtin" = "style=\"color: #bdcadb;\""
"variable.parameter" = "style=\"color: #e2b714;\""
"variable.property" = "style=\"color: #e2b714;\""
