"function" = "class=\"function\" style=\"color: #e5eae1;\""
"markup.list" = "class=\"markup list\" style=\"color: ;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #bdcadb;\""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #e2b714; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #d1d0c5;\""
"keyword" = "class=\"keyword\" style=\"color: #f9ebed;\""
"variable.property" = "class=\"variable property\" style=\"color: #e2b714;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #dd8a3c; \""
"string" = "class=\"string\" style=\"color: #d1d0c5;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #e2b714;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #6d7278;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #bdcadb;\""
"markup.link.url" = "class=\"markup link url\" style=\"color: ;\""
"operator" = "class=\"operator\" style=\"color: #aaaeb3; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #e5eae1; \""
"special" = "class=\"special\" style=\"color: #dd8a3c;\""
"function.macro" = "class=\"function macro\" style=\"color: #b9c2c6;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #e2b714; \""
"background" = "class=\"background\" style=\"background-color: #323437; \""
"punctuation" = "class=\"punctuation\" style=\"color: #aaaeb3;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #e06c75;\""
"comment" = "class=\"comment\" style=\"color: #646669;\""
"tag" = "class=\"tag\" style=\"color: #e2b714;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #d1d0c5; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ca4754; \""
"constructor" = "class=\"constructor\" style=\"color: #e2b714;\""
"variable" = "class=\"variable\" style=\"color: #e2b714;\""
"text" = "class=\"text\" style=\"color: #d1d0c5; \""
"module" = "class=\"module\" style=\"color: #bdcadb; \""
"constant" = "class=\"constant\" style=\"color: #d0c4d4;\""
"type" = "class=\"type\" style=\"color: #e2b714;\""
"attribute" = "class=\"attribute\" style=\"color: #b9c2c6;\""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #d0c4d4; \""
"escape" = "class=\"escape\" style=\"color: #dd8a3c;\""
"number" = "class=\"number\" style=\"color: #d0c4d4;\""
"namespace" = "class=\"namespace\" style=\"color: #d1d0c5;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #dd8a3c; \""
"label" = "class=\"label\" style=\"color: #b9c2c6;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
