"constant.numeric.float" = "class=\"constant numeric float\" style=\"color: #ff5c57; \""
"keyword.control.exception" = "class=\"keyword control exception\" style=\"font-weight: bold; color: #ff5c57; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #9aedfe; \""
"function" = "class=\"function\" style=\"color: #5af78e; \""
"keyword.function" = "class=\"keyword function\" style=\"font-weight: bold; color: #c9c5fb; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #c9c5fb; \""
"keyword.operator" = "class=\"keyword operator\" style=\"font-weight: bold; color: #f97c7c; \""
"markup.list" = "class=\"markup list\" style=\"color: #9aedfe;\""
"markup.link.label" = "class=\"markup link label\" style=\"font-style: italic; color: #57c7ff; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #ffab6f; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #f3f99d; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #eff0eb; \""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #ff6ac1; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #57c7ff; \""
"string" = "class=\"string\" style=\"color: #f3f99d; \""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #57c7ff; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #f97c7c; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #b6d37c; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #9aedfe;\""
"keyword.control" = "class=\"keyword control\" style=\"font-weight: bold; color: #f99fc6; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #ff6ac1; \""
"operator" = "class=\"operator\" style=\"color: #f97c7c; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #5af78e; \""
"special" = "class=\"special\" style=\"color: #ff6ac1; \""
"function.macro" = "class=\"function macro\" style=\"color: #57c7ff; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #f3f99d; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #282a36; \""
"punctuation" = "class=\"punctuation\" style=\"color: #ff6ac1; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #ff6ac1;\""
"comment" = "class=\"comment\" style=\"color: #a39e9b; \""
"tag" = "class=\"tag\" style=\"color: #f99fc6; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #eff0eb; \""
"constant.character" = "class=\"constant character\" style=\"color: #f99fc6; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #ff5c57; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #f3f99d; \""
"constructor" = "class=\"constructor\" style=\"color: #ffab6f; \""
"variable" = "class=\"variable\" style=\"color: #9aedfe; \""
"text" = "class=\"text\" style=\"color: #eff0eb; \""
"type.enum.variant" = "class=\"type enum variant\" style=\"color: #ffab6f; \""
"type.variant" = "class=\"type variant\" style=\"color: #ffab6f; \""
"keyword.storage" = "class=\"keyword storage\" style=\"font-weight: bold; color: #f97c7c; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff5c57; \""
"module" = "class=\"module\" style=\"color: #b6d37c; \""
"constant" = "class=\"constant\" style=\"color: #bd93f9; \""
"string.special" = "class=\"string special\" style=\"color: #57c7ff; \""
"function.method" = "class=\"function method\" style=\"color: #b1d7c7; \""
"type" = "class=\"type\" style=\"color: #b1d7c7; \""
"attribute" = "class=\"attribute\" style=\"color: #b1d7c7; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #b6d37c; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #bd93f9; \""
"namespace" = "class=\"namespace\" style=\"color: #b6d37c; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #57c7ff; \""
"label" = "class=\"label\" style=\"color: #ff6ac1; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
