"background" = "style=\"background-color: #282a36; \""
"attribute" = "style=\"color: #b1d7c7; \""
"comment" = "style=\"color: #a39e9b; \""
"constant" = "style=\"color: #bd93f9; \""
"constant.builtin" = "style=\"color: #b6d37c; \""
"constant.character" = "style=\"color: #f99fc6; \""
"constant.character.escape" = "style=\"color: #ff6ac1; \""
"constant.numeric" = "style=\"color: #9aedfe; \""
"constant.numeric.float" = "style=\"color: #ff5c57; \""
"constructor" = "style=\"color: #ffab6f; \""
"diff.delta" = "style=\"color: #57c7ff; \""
"diff.minus" = "style=\"color: #ff5c57; \""
"diff.plus" = "style=\"color: #5af78e; \""
"function" = "style=\"color: #5af78e; \""
"function.builtin" = "style=\"color: #ffab6f; \""
"function.macro" = "style=\"color: #57c7ff; \""
"function.method" = "style=\"color: #b1d7c7; \""
"keyword" = "style=\"font-weight: bold; color: #ff6ac1; \""
"keyword.control" = "style=\"font-weight: bold; color: #f99fc6; \""
"keyword.control.exception" = "style=\"font-weight: bold; color: #ff5c57; \""
"keyword.function" = "style=\"font-weight: bold; color: #c9c5fb; \""
"keyword.operator" = "style=\"font-weight: bold; color: #f97c7c; \""
"keyword.storage" = "style=\"font-weight: bold; color: #f97c7c; \""
"label" = "style=\"color: #ff6ac1; \""
"markup.bold" = "style=\"font-weight: bold; color: #57c7ff; \""
"markup.heading" = "style=\"font-weight: bold; color: #bd93f9; \""
"markup.italic" = "style=\"text-decoration: underline; color: #f3f99d; \""
"markup.link.label" = "style=\"text-decoration: underline; color: #57c7ff; \""
"markup.link.text" = "style=\"color: #ff6ac1;\""
"markup.link.url" = "style=\"color: #9aedfe;\""
"markup.list" = "style=\"color: #9aedfe;\""
"markup.quote" = "style=\"text-decoration: underline; color: #f3f99d; \""
"markup.raw" = "style=\"color: #eff0eb; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #b6d37c; \""
"operator" = "style=\"color: #f97c7c; \""
"punctuation" = "style=\"color: #ff6ac1; \""
"punctuation.bracket" = "style=\"color: #eff0eb; \""
"punctuation.delimiter" = "style=\"color: #f97c7c; \""
"special" = "style=\"color: #ff6ac1; \""
"string" = "style=\"color: #f3f99d; \""
"string.regexp" = "style=\"color: #ff5c57; \""
"string.special" = "style=\"color: #57c7ff; \""
"tag" = "style=\"color: #f99fc6; \""
"type" = "style=\"color: #b1d7c7; \""
"type.builtin" = "style=\"color: #f3f99d; \""
"type.enum.variant" = "style=\"color: #ffab6f; \""
"type.variant" = "style=\"color: #ffab6f; \""
"variable" = "style=\"color: #9aedfe; \""
"variable.builtin" = "style=\"color: #b6d37c; \""
"variable.other.member" = "style=\"color: #c9c5fb; \""
"variable.parameter" = "style=\"text-decoration: underline; color: #57c7ff; \""
