"function" = "class=\"function\" style=\"color: #268bd2; \""
"markup.list" = "class=\"markup list\" style=\"color: #dc322f;\""
"function.builtin" = "class=\"function builtin\" style=\"font-weight: bold; color: #268bd2; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #2aa198;\""
"keyword" = "class=\"keyword\" style=\"color: #859900; \""
"function.special" = "class=\"function special\" style=\"color: #d33682; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #cb4b16; \""
"string" = "class=\"string\" style=\"color: #2aa198; \""
"variable.builtin" = "class=\"variable builtin\" style=\"font-weight: bold; color: #2aa198; \""
"variable.function" = "class=\"variable function\" style=\"color: #268bd2; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #b58900; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #dc322f; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #cb4b16; \""
"operator" = "class=\"operator\" style=\"color: #859900; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #859900; \""
"special" = "class=\"special\" style=\"color: #cb4b16; \""
"function.macro" = "class=\"function macro\" style=\"color: #d33682; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #d33682; \""
"background" = "class=\"background\" style=\"background-color: #fdf6e3; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #dc322f;\""
"comment" = "class=\"comment\" style=\"color: #93a1a1; \""
"tag" = "class=\"tag\" style=\"color: #d33682; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #859900;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #dc322f; \""
"type.builtin" = "class=\"type builtin\" style=\"font-weight: bold; color: #b58900; \""
"constructor" = "class=\"constructor\" style=\"color: #268bd2; \""
"module" = "class=\"module\" style=\"color: #6c71c4; \""
"constant" = "class=\"constant\" style=\"color: #2aa198; \""
"type" = "class=\"type\" style=\"color: #b58900; \""
"attribute" = "class=\"attribute\" style=\"color: #6c71c4; \""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #2aa198; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #268bd2;\""
"namespace" = "class=\"namespace\" style=\"color: #6c71c4; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #b58900; \""
"label" = "class=\"label\" style=\"color: #859900; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
