"attribute" = "style=\"color: #6c71c4; \""
"comment" = "style=\"color: #93a1a1; \""
"constant" = "style=\"color: #2aa198; \""
"constant.builtin" = "style=\"font-weight: bold; color: #2aa198; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #dc322f; \""
"constructor" = "style=\"color: #268bd2; \""
"diff.delta" = "style=\"color: #cb4b16; \""
"diff.minus" = "style=\"color: #dc322f; \""
"diff.plus" = "style=\"color: #859900; \""
"function" = "style=\"color: #268bd2; \""
"function.builtin" = "style=\"font-weight: bold; color: #268bd2; \""
"function.macro" = "style=\"color: #d33682; \""
"function.special" = "style=\"color: #d33682; \""
"keyword" = "style=\"color: #859900; \""
"keyword.directive" = "style=\"color: #cb4b16; \""
"label" = "style=\"color: #859900; \""
"markup.bold" = "style=\"font-weight: bold; color: #b58900; \""
"markup.heading" = "style=\"color: #268bd2;\""
"markup.italic" = "style=\"text-decoration: underline; color: #d33682; \""
"markup.link.text" = "style=\"color: #dc322f;\""
"markup.link.url" = "style=\"color: #b58900; \""
"markup.list" = "style=\"color: #dc322f;\""
"markup.quote" = "style=\"color: #2aa198;\""
"markup.raw" = "style=\"color: #859900;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #6c71c4; \""
"namespace" = "style=\"color: #6c71c4; \""
"operator" = "style=\"color: #859900; \""
"special" = "style=\"color: #cb4b16; \""
"string" = "style=\"color: #2aa198; \""
"tag" = "style=\"color: #d33682; \""
"type" = "style=\"color: #b58900; \""
"type.builtin" = "style=\"font-weight: bold; color: #b58900; \""
"variable.builtin" = "style=\"font-weight: bold; color: #2aa198; \""
"variable.function" = "style=\"color: #268bd2; \""
