"attribute" = "style=\"color: #b39df3;\""
"comment" = "style=\"color: #7f8490;\""
"constant" = "style=\"color: #b39df3;\""
"constant.character.escape" = "style=\"color: #f39660;\""
"constant.numeric" = "style=\"color: #b39df3;\""
"constructor" = "style=\"color: #76cce0;\""
"diff.delta" = "style=\"color: #f39660;\""
"diff.minus" = "style=\"color: #fc5d7c;\""
"diff.plus" = "style=\"color: #9ed072;\""
"function" = "style=\"color: #9ed072;\""
"function.builtin" = "style=\"color: #76cce0;\""
"function.macro" = "style=\"color: #b39df3;\""
"keyword" = "style=\"color: #fc5d7c;\""
"label" = "style=\"color: #f39660;\""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #fc5d7c; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #f39660; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #e7c664; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #9ed072; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #76cce0; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #e2e2e3; \""
"markup.heading.marker" = "style=\"color: #7f8490;\""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #b39df3;\""
"markup.link.url" = "style=\"color: #76cce0; \""
"markup.list" = "style=\"color: #fc5d7c;\""
"markup.quote" = "style=\"color: #7f8490;\""
"markup.raw" = "style=\"color: #9ed072;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #76cce0;\""
"namespace" = "style=\"color: #76cce0;\""
"operator" = "style=\"color: #f39660;\""
"punctuation" = "style=\"color: #7f8490;\""
"punctuation.bracket" = "style=\"color: #e2e2e3;\""
"punctuation.delimiter" = "style=\"color: #7f8490;\""
"special" = "style=\"color: #f39660;\""
"string" = "style=\"color: #e7c664;\""
"tag" = "style=\"color: #e7c664;\""
"type" = "style=\"color: #76cce0;\""
"variable" = "style=\"color: #e2e2e3;\""
"variable.builtin" = "style=\"color: #f39660;\""
"variable.other.member" = "style=\"color: #e2e2e3;\""
"variable.parameter" = "style=\"color: #e2e2e3;\""
