"attribute" = "style=\"color: #b1951d;\""
"comment" = "style=\"text-decoration: underline; color: #a49da5; \""
"constant" = "style=\"color: #6c3163; \""
"constant.builtin" = "style=\"font-weight: bold; color: #6c3163; \""
"constructor" = "style=\"font-weight: bold; color: #4e3163; \""
"diff.delta" = "style=\"color: #715ab1;\""
"diff.minus" = "style=\"color: #ba2f59;\""
"diff.plus" = "style=\"color: #2d9574;\""
"escape" = "style=\"font-weight: bold; color: #5f3bc4; \""
"function" = "style=\"font-weight: bold; color: #715ab1; \""
"function.builtin" = "style=\"color: #b1951d;\""
"function.macro" = "style=\"color: #b1951d;\""
"keyword" = "style=\"color: #3a81c3; \""
"keyword.directive" = "style=\"color: #3a81c3;\""
"label" = "style=\"color: #b1951d;\""
"markup.bold" = "style=\"font-weight: bold; color: #b1951d; \""
"markup.heading" = "style=\"color: #3a81c3;\""
"markup.italic" = "style=\"text-decoration: underline; color: #a31db1; \""
"markup.link.text" = "style=\"color: #c10e0b;\""
"markup.link.url" = "style=\"color: #b1951d; \""
"markup.list" = "style=\"color: #c10e0b;\""
"markup.quote" = "style=\"color: #21b8c7;\""
"markup.raw" = "style=\"color: #67b11d;\""
"markup.strikethrough" = "style=\"\""
"module" = "style=\"color: #b1951d;\""
"namespace" = "style=\"color: #b1951d;\""
"number" = "style=\"color: #6c3163;\""
"operator" = "style=\"color: #ba2f59;\""
"punctuation" = "style=\"color: #6c3163;\""
"punctuation.delimiter" = "style=\"color: #6c3163;\""
"special" = "style=\"color: #ba2f59;\""
"string" = "style=\"color: #2d9574;\""
"type" = "style=\"color: #6c3163;\""
"type.builtin" = "style=\"color: #6c3163;\""
"variable" = "style=\"color: #715ab1;\""
"variable.builtin" = "style=\"color: #715ab1;\""
"variable.other.member" = "style=\"color: #002db3;\""
"variable.parameter" = "style=\"color: #7590db;\""
"variable.property" = "style=\"color: #7590db;\""
