"function" = "class=\"function\" style=\"font-weight: bold; color: #715ab1; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #002db3;\""
"markup.list" = "class=\"markup list\" style=\"color: #c10e0b;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #b1951d;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #21b8c7;\""
"keyword" = "class=\"keyword\" style=\"color: #3a81c3; \""
"variable.property" = "class=\"variable property\" style=\"color: #7590db;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #715ab1;\""
"string" = "class=\"string\" style=\"color: #2d9574;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #7590db;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #6c3163;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #715ab1;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #b1951d; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #3a81c3;\""
"operator" = "class=\"operator\" style=\"color: #ba2f59; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #2d9574;\""
"special" = "class=\"special\" style=\"color: #ba2f59;\""
"function.macro" = "class=\"function macro\" style=\"color: #b1951d;\""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #a31db1; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #fbf8ef; \""
"punctuation" = "class=\"punctuation\" style=\"color: #6c3163;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #c10e0b;\""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #a49da5; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #67b11d;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ba2f59;\""
"type.builtin" = "class=\"type builtin\" style=\"color: #6c3163;\""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #4e3163; \""
"variable" = "class=\"variable\" style=\"color: #715ab1;\""
"text" = "class=\"text\" style=\"color: #655370; \""
"module" = "class=\"module\" style=\"color: #b1951d; \""
"constant" = "class=\"constant\" style=\"color: #6c3163; \""
"type" = "class=\"type\" style=\"color: #6c3163;\""
"attribute" = "class=\"attribute\" style=\"color: #b1951d;\""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #6c3163; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #3a81c3;\""
"escape" = "class=\"escape\" style=\"font-weight: bold; color: #5f3bc4; \""
"number" = "class=\"number\" style=\"color: #6c3163;\""
"namespace" = "class=\"namespace\" style=\"color: #b1951d;\""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #b1951d; \""
"label" = "class=\"label\" style=\"color: #b1951d;\""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
