"comment" = "style=\"text-decoration: underline; color: #565f89; \""
"constant" = "style=\"color: #ff9e64; \""
"constant.character.escape" = "style=\"color: #bb9af7; \""
"diff.delta" = "style=\"color: #ff9e64; \""
"diff.minus" = "style=\"color: #f7768e; \""
"diff.plus" = "style=\"color: #73daca; \""
"function" = "style=\"text-decoration: underline; color: #7aa2f7; \""
"function.macro" = "style=\"color: #7dcfff; \""
"keyword" = "style=\"text-decoration: underline; color: #7dcfff; \""
"keyword.control" = "style=\"color: #bb9af7; \""
"keyword.control.import" = "style=\"color: #7dcfff; \""
"keyword.function" = "style=\"text-decoration: underline; color: #bb9af7; \""
"keyword.operator" = "style=\"color: #89ddff; \""
"markup.bold" = "style=\"font-weight: bold; color: #ff9e64; \""
"markup.heading" = "style=\"font-weight: bold; color: #7dcfff; \""
"markup.italic" = "style=\"text-decoration: underline; color: #e0af68; \""
"markup.link.text" = "style=\"color: #9aa5ce; \""
"markup.link.url" = "style=\"color: #73daca; \""
"markup.list" = "style=\"color: #7dcfff; \""
"markup.quote" = "style=\"text-decoration: underline; color: #e0af68; \""
"markup.raw" = "style=\"color: #7dcfff; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #7aa2f7; \""
"operator" = "style=\"color: #89ddff; \""
"punctuation" = "style=\"color: #89ddff; \""
"special" = "style=\"color: #ff9e64; \""
"string" = "style=\"color: #9ece6a; \""
"string.regexp" = "style=\"color: ; \""
"tag" = "style=\"color: #f7768e; \""
"type" = "style=\"color: #2ac3de; \""
"variable" = "style=\"color: #c0caf5; \""
"variable.builtin" = "style=\"color: #f7768e; \""
"variable.other.member" = "style=\"color: #73daca; \""
"variable.parameter" = "style=\"text-decoration: underline; color: #e0af68; \""
