"comment" = "style=\"text-decoration: underline; color: ; \""
"constant" = "style=\"color: ; \""
"constant.character.escape" = "style=\"color: ; \""
"diff.delta" = "style=\"color: ; \""
"diff.minus" = "style=\"color: ; \""
"diff.plus" = "style=\"color: ; \""
"function" = "style=\"text-decoration: underline; color: ; \""
"function.macro" = "style=\"color: ; \""
"keyword" = "style=\"text-decoration: underline; color: ; \""
"keyword.control" = "style=\"color: ; \""
"keyword.control.import" = "style=\"color: ; \""
"keyword.function" = "style=\"text-decoration: underline; color: ; \""
"keyword.operator" = "style=\"color: ; \""
"markup.bold" = "style=\"font-weight: bold; color: ; \""
"markup.heading" = "style=\"font-weight: bold; color: ; \""
"markup.italic" = "style=\"text-decoration: underline; color: ; \""
"markup.link.text" = "style=\"color: ; \""
"markup.link.url" = "style=\"color: ; \""
"markup.list" = "style=\"color: ; \""
"markup.quote" = "style=\"text-decoration: underline; color: ; \""
"markup.raw" = "style=\"color: ; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: ; \""
"operator" = "style=\"color: ; \""
"punctuation" = "style=\"color: ; \""
"special" = "style=\"color: ; \""
"string" = "style=\"color: ; \""
"string.regexp" = "style=\"color: ; \""
"tag" = "style=\"color: ; \""
"type" = "style=\"color: ; \""
"variable" = "style=\"color: ; \""
"variable.builtin" = "style=\"color: ; \""
"variable.other.member" = "style=\"color: ; \""
"variable.parameter" = "style=\"text-decoration: underline; color: ; \""
