"function" = "class=\"function\" style=\"font-style: italic; color: #7aa2f7; \""
"keyword.function" = "class=\"keyword function\" style=\"font-style: italic; color: #bb9af7; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #73daca; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #89ddff; \""
"markup.list" = "class=\"markup list\" style=\"color: #7dcfff; \""
"markup.quote" = "class=\"markup quote\" style=\"font-style: italic; color: #e0af68; \""
"keyword" = "class=\"keyword\" style=\"font-style: italic; color: #7dcfff; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #7dcfff; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #ff9e64; \""
"string" = "class=\"string\" style=\"color: #9ece6a; \""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #e0af68; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #f7768e; \""
"markup.link.url" = "class=\"markup link url\" style=\"color: #73daca; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #bb9af7; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #bb9af7; \""
"operator" = "class=\"operator\" style=\"color: #89ddff; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #73daca; \""
"special" = "class=\"special\" style=\"color: #ff9e64; \""
"function.macro" = "class=\"function macro\" style=\"color: #7dcfff; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #e0af68; \""
"background" = "class=\"background\" style=\"background-color: #1a1b26; \""
"punctuation" = "class=\"punctuation\" style=\"color: #89ddff; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #9aa5ce; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #565f89; \""
"tag" = "class=\"tag\" style=\"color: #f7768e; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #7dcfff; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #f7768e; \""
"variable" = "class=\"variable\" style=\"color: #c0caf5; \""
"text" = "class=\"text\" style=\"color: #a9b1d6; \""
"string.regexp" = "class=\"string regexp\" style=\"color: ; \""
"module" = "class=\"module\" style=\"color: #7aa2f7; \""
"constant" = "class=\"constant\" style=\"color: #ff9e64; \""
"type" = "class=\"type\" style=\"color: #2ac3de; \""
"markup.heading" = "class=\"markup heading\" style=\"font-weight: bold; color: #7dcfff; \""
"namespace" = "class=\"namespace\" style=\"color: #7aa2f7; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #ff9e64; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
