"attribute" = "style=\"color: #83c092;\""
"comment" = "style=\"color: #928374;\""
"constant" = "style=\"color: #d699b6;\""
"constant.character.escape" = "style=\"color: #e69875;\""
"constant.numeric" = "style=\"color: #d699b6;\""
"constructor" = "style=\"color: #83c092;\""
"diff.delta" = "style=\"color: #e69875;\""
"diff.minus" = "style=\"color: #e67e80;\""
"diff.plus" = "style=\"color: #a7c080;\""
"function" = "style=\"color: #a7c080;\""
"function.builtin" = "style=\"color: #7fbbb3;\""
"function.macro" = "style=\"color: #83c092;\""
"keyword" = "style=\"color: #d699b6;\""
"label" = "style=\"color: #83c092;\""
"markup.heading.1" = "style=\"font-weight: bold; color: #e67e80; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #e69875; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #dbbc7f; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #a7c080; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #7fbbb3; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #dfbf8e; \""
"markup.heading.marker" = "style=\"color: #9da9a0;\""
"markup.link.text" = "style=\"color: #d699b6;\""
"markup.link.url" = "style=\"color: #7fbbb3; \""
"markup.list" = "style=\"color: #e67e80;\""
"markup.quote" = "style=\"color: #9da9a0;\""
"markup.raw" = "style=\"color: #a7c080;\""
"module" = "style=\"color: #7fbbb3;\""
"namespace" = "style=\"color: #83c092;\""
"operator" = "style=\"color: #e69875;\""
"punctuation" = "style=\"color: #9da9a0;\""
"punctuation.bracket" = "style=\"color: #dfbf8e;\""
"punctuation.delimiter" = "style=\"color: #9da9a0;\""
"special" = "style=\"color: #e69875;\""
"string" = "style=\"color: #a7c080;\""
"tag" = "style=\"color: #dbbc7f;\""
"type" = "style=\"color: #7fbbb3;\""
"variable" = "style=\"color: #dfbf8e;\""
"variable.builtin" = "style=\"color: #7fbbb3;\""
"variable.other.member" = "style=\"color: #dfbf8e;\""
"variable.parameter" = "style=\"color: #dfbf8e;\""
