"constant.numeric" = "class=\"constant numeric\" style=\"color: #d699b6;\""
"function" = "class=\"function\" style=\"color: #a7c080;\""
"variable.other.member" = "class=\"variable other member\" style=\"color: #dfbf8e;\""
"markup.list" = "class=\"markup list\" style=\"color: #e67e80;\""
"function.builtin" = "class=\"function builtin\" style=\"color: #7fbbb3;\""
"markup.quote" = "class=\"markup quote\" style=\"color: #9da9a0;\""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #a7c080; \""
"punctuation.bracket" = "class=\"punctuation bracket\" style=\"color: #dfbf8e;\""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #7fbbb3; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #dbbc7f; \""
"keyword" = "class=\"keyword\" style=\"color: #d699b6;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #e69875;\""
"string" = "class=\"string\" style=\"color: #a7c080;\""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #dfbf8e;\""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #9da9a0;\""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #7fbbb3;\""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #7fbbb3; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #e69875;\""
"operator" = "class=\"operator\" style=\"color: #e69875; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a7c080;\""
"special" = "class=\"special\" style=\"color: #e69875;\""
"function.macro" = "class=\"function macro\" style=\"color: #83c092;\""
"background" = "class=\"background\" style=\"background-color: #282828; \""
"punctuation" = "class=\"punctuation\" style=\"color: #9da9a0;\""
"markup.link.text" = "class=\"markup link text\" style=\"color: #d699b6;\""
"comment" = "class=\"comment\" style=\"color: #928374;\""
"tag" = "class=\"tag\" style=\"color: #dbbc7f;\""
"markup.raw" = "class=\"markup raw\" style=\"color: #a7c080;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #e67e80;\""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #e69875; \""
"constructor" = "class=\"constructor\" style=\"color: #83c092;\""
"variable" = "class=\"variable\" style=\"color: #dfbf8e;\""
"text" = "class=\"text\" style=\"color: #dfbf8e; \""
"module" = "class=\"module\" style=\"color: #7fbbb3; \""
"constant" = "class=\"constant\" style=\"color: #d699b6;\""
"type" = "class=\"type\" style=\"color: #7fbbb3;\""
"attribute" = "class=\"attribute\" style=\"color: #83c092;\""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #dfbf8e; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #e67e80; \""
"namespace" = "class=\"namespace\" style=\"color: #83c092;\""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"color: #9da9a0;\""
"label" = "class=\"label\" style=\"color: #83c092;\""
