"background" = "class=\"background\" style=\"background-color: #000000; \""
"comment" = "class=\"comment\" style=\"color: #697386;\""
"comment.documentation" = "class=\"comment documentation\" style=\"color: #c96ed0;\""
"constant" = "class=\"constant\" style=\"color: #ed5f74;\""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #c96ed0;\""
"constructor" = "class=\"constructor\" style=\"color: #7fd3ed;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #d97917;\""
"diff.minus" = "class=\"diff minus\" style=\"color: #ed5f74;\""
"diff.plus" = "class=\"diff plus\" style=\"color: #1ea672;\""
"function" = "class=\"function\" style=\"color: #7fd3ed;\""
"function.macro" = "class=\"function macro\" style=\"color: #c96ed0;\""
"keyword" = "class=\"keyword\" style=\"color: #d97917;\""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #c96ed0;\""
"label" = "class=\"label\" style=\"color: #1ea672;\""
"module" = "class=\"module\" style=\"color: #d97917; \""
"operator" = "class=\"operator\" style=\"\""
"special" = "class=\"special\" style=\"color: #3a97d4;\""
"string" = "class=\"string\" style=\"color: #ed5f74;\""
"type" = "class=\"type\" style=\"color: #1ea672;\""
