"comment" = "style=\"color: #697386;\""
"comment.documentation" = "style=\"color: #c96ed0;\""
"constant" = "style=\"color: #ed5f74;\""
"constant.character.escape" = "style=\"color: #c96ed0;\""
"constructor" = "style=\"color: #7fd3ed;\""
"diff.delta" = "style=\"color: #d97917;\""
"diff.minus" = "style=\"color: #ed5f74;\""
"diff.plus" = "style=\"color: #1ea672;\""
"function" = "style=\"color: #7fd3ed;\""
"function.macro" = "style=\"color: #c96ed0;\""
"keyword" = "style=\"color: #d97917;\""
"keyword.directive" = "style=\"color: #c96ed0;\""
"label" = "style=\"color: #1ea672;\""
"special" = "style=\"color: #3a97d4;\""
"string" = "style=\"color: #ed5f74;\""
"type" = "style=\"color: #1ea672;\""
