"constant.numeric" = "class=\"constant numeric\" style=\"color: #ffd900; \""
"function" = "class=\"function\" style=\"font-weight: bold; color: #FFFFFF; \""
"type.enum" = "class=\"type enum\" style=\"color: #ffd900; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #ffd900; \""
"markup.list" = "class=\"markup list\" style=\"font-weight: bold; color: #ffd900; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #FFFFFF; \""
"markup.heading.4" = "class=\"markup heading 4\" style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.5" = "class=\"markup heading 5\" style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.3" = "class=\"markup heading 3\" style=\"font-weight: bold; color: #FFFFFF; \""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #ffd900; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #008DFF; \""
"string" = "class=\"string\" style=\"color: #378b1d; \""
"variable.parameter" = "class=\"variable parameter\" style=\"font-style: italic; color: #FFFFFF; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #ffd900; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #FFFFFF; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #ffd900; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #ff80f4; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #ffd900; \""
"operator" = "class=\"operator\" style=\"color: #ffd900; \""
"diff.plus" = "class=\"diff plus\" style=\"color: ; \""
"special" = "class=\"special\" style=\"color: #ffd900; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #242424; \""
"punctuation" = "class=\"punctuation\" style=\"color: #FFFFFF; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #378b1d; \""
"comment" = "class=\"comment\" style=\"color: #6b6b6b; \""
"tag" = "class=\"tag\" style=\"font-weight: bold; color: #ffd900; \""
"diff.delta.moved" = "class=\"diff delta moved\" style=\"color: #2a2a2a; \""
"markup.raw" = "class=\"markup raw\" style=\"color: #378b1d; \""
"constant.character" = "class=\"constant character\" style=\"color: #378b1d; \""
"diff.minus" = "class=\"diff minus\" style=\"color: ; \""
"markup.heading.2" = "class=\"markup heading 2\" style=\"font-weight: bold; color: #FFFFFF; \""
"type.builtin" = "class=\"type builtin\" style=\"color: #ffd900; \""
"constructor" = "class=\"constructor\" style=\"font-weight: bold; color: #FFFFFF; \""
"variable" = "class=\"variable\" style=\"color: #FFFFFF; \""
"text" = "class=\"text\" style=\"color: #FFFFFF; \""
"string.regexp" = "class=\"string regexp\" style=\"color: #ff80f4; \""
"module" = "class=\"module\" style=\"color: #FFFFFF; \""
"punctuation.special" = "class=\"punctuation special\" style=\"font-weight: bold; color: #ff80f4; \""
"constant" = "class=\"constant\" style=\"font-weight: bold; color: #FFFFFF; \""
"type" = "class=\"type\" style=\"color: #FFFFFF; \""
"attribute" = "class=\"attribute\" style=\"color: #FFFFFF; \""
"markup.heading.6" = "class=\"markup heading 6\" style=\"font-weight: bold; color: #FFFFFF; \""
"constant.builtin" = "class=\"constant builtin\" style=\"font-weight: bold; color: #ff80f4; \""
"markup.heading.1" = "class=\"markup heading 1\" style=\"font-weight: bold; color: #FFFFFF; \""
"namespace" = "class=\"namespace\" style=\"color: #FFFFFF; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; \""
"keyword.control.return" = "class=\"keyword control return\" style=\"font-weight: bold; color: #ffd900; \""
"markup.heading.marker" = "class=\"markup heading marker\" style=\"font-weight: bold; color: #ffd900; \""
"label" = "class=\"label\" style=\"color: #FFFFFF; \""
