"attribute" = "style=\"color: #FFFFFF; \""
"comment" = "style=\"color: #6b6b6b; \""
"constant" = "style=\"font-weight: bold; color: #FFFFFF; \""
"constant.builtin" = "style=\"font-weight: bold; color: #ff80f4; \""
"constant.character" = "style=\"color: #378b1d; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #ff80f4; \""
"constant.numeric" = "style=\"color: #ffd900; \""
"constructor" = "style=\"font-weight: bold; color: #FFFFFF; \""
"diff.delta" = "style=\"color: #008DFF; \""
"diff.delta.moved" = "style=\"color: #2a2a2a; \""
"diff.minus" = "style=\"color: ; \""
"diff.plus" = "style=\"color: ; \""
"function" = "style=\"font-weight: bold; color: #FFFFFF; \""
"keyword" = "style=\"font-weight: bold; color: #ffd900; \""
"keyword.control" = "style=\"color: #ffd900; \""
"keyword.control.return" = "style=\"font-weight: bold; color: #ffd900; \""
"keyword.directive" = "style=\"color: #ffd900; \""
"keyword.operator" = "style=\"color: #ffd900; \""
"label" = "style=\"color: #FFFFFF; \""
"markup.bold" = "style=\"font-weight: bold; \""
"markup.heading.1" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.2" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.3" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.4" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.5" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.6" = "style=\"font-weight: bold; color: #FFFFFF; \""
"markup.heading.marker" = "style=\"font-weight: bold; color: #ffd900; \""
"markup.italic" = "style=\"text-decoration: underline; \""
"markup.link.text" = "style=\"color: #378b1d; \""
"markup.link.url" = "style=\"color: #FFFFFF; \""
"markup.list" = "style=\"font-weight: bold; color: #ffd900; \""
"markup.quote" = "style=\"color: #FFFFFF; \""
"markup.raw" = "style=\"color: #378b1d; \""
"namespace" = "style=\"color: #FFFFFF; \""
"operator" = "style=\"color: #ffd900; \""
"punctuation" = "style=\"color: #FFFFFF; \""
"punctuation.special" = "style=\"font-weight: bold; color: #ff80f4; \""
"special" = "style=\"color: #ffd900; \""
"string" = "style=\"color: #378b1d; \""
"string.regexp" = "style=\"color: #ff80f4; \""
"tag" = "style=\"font-weight: bold; color: #ffd900; \""
"type" = "style=\"color: #FFFFFF; \""
"type.builtin" = "style=\"color: #ffd900; \""
"type.enum" = "style=\"color: #ffd900; \""
"variable" = "style=\"color: #FFFFFF; \""
"variable.builtin" = "style=\"color: #ffd900; \""
"variable.parameter" = "style=\"text-decoration: underline; color: #FFFFFF; \""
