"background" = "style=\"background-color: #292c33; \""
"attribute" = "style=\"color: #dac18c; \""
"comment" = "style=\"text-decoration: underline; color: #5c606b; \""
"constant" = "style=\"color: #dac18c; \""
"constant.builtin" = "style=\"color: #b4926e; \""
"constant.builtin.boolean" = "style=\"color: #dac18c; \""
"constant.character.escape" = "style=\"color: #b4926e; \""
"constant.numeric" = "style=\"color: #b4926e; \""
"constructor" = "style=\"color: #7ca8dd; \""
"diff.delta" = "style=\"color: #b4926e;\""
"diff.minus" = "style=\"color: #bd7476;\""
"diff.plus" = "style=\"color: #a0b783;\""
"function" = "style=\"color: #7ca8dd; \""
"function.builtin" = "style=\"color: #7ca8dd; \""
"function.macro" = "style=\"color: #9d74b9; \""
"keyword" = "style=\"color: #9d74b9; \""
"keyword.control" = "style=\"color: #9d74b9; \""
"keyword.control.import" = "style=\"color: #9d74b9; \""
"keyword.directive" = "style=\"color: #9d74b9; \""
"keyword.operator" = "style=\"color: #9d74b9; \""
"label" = "style=\"color: #a8adb7; \""
"markup.bold" = "style=\"font-weight: bold; color: #b4926e; \""
"markup.heading" = "style=\"color: #bd7476; \""
"markup.italic" = "style=\"text-decoration: underline; color: #9d74b9; \""
"markup.link.text" = "style=\"color: #9d74b9; \""
"markup.link.url" = "style=\"color: #7eb2be; \""
"markup.list" = "style=\"color: #bd7476; \""
"markup.quote" = "style=\"color: #dac18c; \""
"markup.raw.inline" = "style=\"color: #a0b783; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #a8adb7; \""
"operator" = "style=\"color: #a8adb7; \""
"special" = "style=\"color: #7ca8dd; \""
"string" = "style=\"color: #a0b783; \""
"type" = "style=\"color: #7eb2be; \""
"variable.builtin" = "style=\"color: #b4926e; \""
"variable.other.member" = "style=\"color: #bd7476; \""
"variable.parameter" = "style=\"color: #a8adb7; \""
