"background" = "style=\"background-color: #fafafa; \""
"attribute" = "style=\"color: #739d60; \""
"comment" = "style=\"text-decoration: underline; color: #a6a6aa; \""
"constant" = "style=\"color: #739d60; \""
"constant.builtin" = "style=\"color: #a8763c; \""
"constant.builtin.boolean" = "style=\"color: #739d60; \""
"constant.character.escape" = "style=\"color: #ca7667; \""
"constant.numeric" = "style=\"color: #a8763c; \""
"constructor" = "style=\"color: #5185b5; \""
"diff.delta" = "style=\"color: #ca7667;\""
"diff.minus" = "style=\"color: #bd7476;\""
"diff.plus" = "style=\"color: #739d60;\""
"function" = "style=\"color: #5185b5; \""
"function.builtin" = "style=\"color: #5185b5; \""
"function.macro" = "style=\"color: #a160ac; \""
"keyword" = "style=\"color: #a160ac; \""
"keyword.control" = "style=\"color: #a160ac; \""
"keyword.control.import" = "style=\"color: #a160ac; \""
"keyword.directive" = "style=\"color: #a160ac; \""
"keyword.operator" = "style=\"color: #a160ac; \""
"label" = "style=\"color: #404248; \""
"markup.bold" = "style=\"font-weight: bold; color: #ca7667; \""
"markup.heading" = "style=\"color: #ca7667; \""
"markup.italic" = "style=\"text-decoration: underline; color: #a160ac; \""
"markup.link.text" = "style=\"color: #a160ac; \""
"markup.link.url" = "style=\"color: #4b80b2; \""
"markup.list" = "style=\"color: #ca7667; \""
"markup.quote" = "style=\"color: #739d60; \""
"markup.raw.inline" = "style=\"color: #739d60; \""
"markup.strikethrough" = "style=\"\""
"namespace" = "style=\"color: #404248; \""
"operator" = "style=\"color: #404248; \""
"special" = "style=\"color: #5185b5; \""
"string" = "style=\"color: #739d60; \""
"type" = "style=\"color: #4b80b2; \""
"variable.builtin" = "style=\"color: #a8763c; \""
"variable.other.member" = "style=\"color: #ca7667; \""
"variable.parameter" = "style=\"color: #404248; \""
