"constant.numeric" = "class=\"constant numeric\" style=\"color: #b4926e; \""
"function" = "class=\"function\" style=\"color: #7ca8dd; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #bd7476; \""
"keyword.operator" = "class=\"keyword operator\" style=\"color: #9d74b9; \""
"markup.list" = "class=\"markup list\" style=\"color: #bd7476; \""
"function.builtin" = "class=\"function builtin\" style=\"color: #7ca8dd; \""
"markup.quote" = "class=\"markup quote\" style=\"color: #dac18c; \""
"keyword" = "class=\"keyword\" style=\"color: #9d74b9; \""
"keyword.control.import" = "class=\"keyword control import\" style=\"color: #9d74b9; \""
"diff.delta" = "class=\"diff delta\" style=\"color: #b4926e;\""
"string" = "class=\"string\" style=\"color: #a0b783; \""
"variable.parameter" = "class=\"variable parameter\" style=\"color: #a8adb7; \""
"variable.builtin" = "class=\"variable builtin\" style=\"color: #b4926e; \""
"markup.link.url" = "class=\"markup link url\" style=\"text-decoration: underline; color: #7eb2be; \""
"keyword.control" = "class=\"keyword control\" style=\"color: #9d74b9; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"color: #b4926e; \""
"keyword.directive" = "class=\"keyword directive\" style=\"color: #9d74b9; \""
"operator" = "class=\"operator\" style=\"color: #a8adb7; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #a0b783;\""
"special" = "class=\"special\" style=\"color: #7ca8dd; \""
"function.macro" = "class=\"function macro\" style=\"color: #9d74b9; \""
"markup.italic" = "class=\"markup italic\" style=\"font-style: italic; color: #9d74b9; \""
"background" = "class=\"autumn highlight background\" style=\"background-color: #292c33; \""
"markup.link.text" = "class=\"markup link text\" style=\"color: #9d74b9; \""
"comment" = "class=\"comment\" style=\"font-style: italic; color: #5c606b; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #bd7476;\""
"constructor" = "class=\"constructor\" style=\"color: #7ca8dd; \""
"text" = "class=\"text\" style=\"color: #a8adb7; \""
"module" = "class=\"module\" style=\"color: #a8adb7; \""
"constant.builtin.boolean" = "class=\"constant builtin boolean\" style=\"color: #dac18c; \""
"constant" = "class=\"constant\" style=\"color: #dac18c; \""
"type" = "class=\"type\" style=\"color: #7eb2be; \""
"attribute" = "class=\"attribute\" style=\"color: #dac18c; \""
"constant.builtin" = "class=\"constant builtin\" style=\"color: #b4926e; \""
"markup.heading" = "class=\"markup heading\" style=\"color: #bd7476; \""
"markup.raw.inline" = "class=\"markup raw inline\" style=\"color: #a0b783; \""
"namespace" = "class=\"namespace\" style=\"color: #a8adb7; \""
"markup.bold" = "class=\"markup bold\" style=\"font-weight: bold; color: #b4926e; \""
"label" = "class=\"label\" style=\"color: #a8adb7; \""
"markup.strikethrough" = "class=\"markup strikethrough\" style=\"\""
