"background" = "class=\"background\" style=\"background-color: #3f3f3f; \""
"comment" = "class=\"comment\" style=\"color: #7f9f7f; \""
"comment.block.documentation" = "class=\"comment block documentation\" style=\"font-weight: bold; color: ; \""
"constant" = "class=\"constant\" style=\"font-weight: bold; color: #dca3a3; \""
"constant.character.escape" = "class=\"constant character escape\" style=\"font-weight: bold; color: #dca3a3; \""
"constant.numeric" = "class=\"constant numeric\" style=\"color: #8cd0d3;\""
"diff.delta" = "class=\"diff delta\" style=\"color: #464646; \""
"diff.minus" = "class=\"diff minus\" style=\"color: #cc9393; \""
"diff.plus" = "class=\"diff plus\" style=\"color: #709080; \""
"function" = "class=\"function\" style=\"color: #efef8f;\""
"function.macro" = "class=\"function macro\" style=\"font-weight: bold; color: #ffcfaf; \""
"keyword" = "class=\"keyword\" style=\"font-weight: bold; color: #f0dfaf; \""
"keyword.storage-class" = "class=\"keyword storage-class\" style=\"font-weight: bold; color: #c3bf9f; \""
"label" = "class=\"label\" style=\"color: #dfcfaf; \""
"module" = "class=\"module\" style=\"color: #f0dfaf; \""
"operator" = "class=\"operator\" style=\"color: #f0efd0; \""
"punctuation.delimiter" = "class=\"punctuation delimiter\" style=\"color: #8f8f8f;\""
"special" = "class=\"special\" style=\"color: #cfbfaf;\""
"string" = "class=\"string\" style=\"color: #cc9393;\""
"type" = "class=\"type\" style=\"font-weight: bold; color: #dfdfbf; \""
"variable" = "class=\"variable\" style=\"color: #dcdccc;\""
"variable.builtin" = "class=\"variable builtin\" style=\"font-weight: bold; color: #dca3a3; \""
"variable.other.member" = "class=\"variable other member\" style=\"color: #efef8f;\""
