"comment" = "style=\"color: #7f9f7f; \""
"comment.block.documentation" = "style=\"font-weight: bold; color: ; \""
"constant" = "style=\"font-weight: bold; color: #dca3a3; \""
"constant.character.escape" = "style=\"font-weight: bold; color: #dca3a3; \""
"constant.numeric" = "style=\"color: #8cd0d3;\""
"diff.delta" = "style=\"color: #464646; \""
"diff.minus" = "style=\"color: #cc9393; \""
"diff.plus" = "style=\"color: #709080; \""
"function" = "style=\"color: #efef8f;\""
"function.macro" = "style=\"font-weight: bold; color: #ffcfaf; \""
"keyword" = "style=\"font-weight: bold; color: #f0dfaf; \""
"keyword.storage-class" = "style=\"font-weight: bold; color: #c3bf9f; \""
"label" = "style=\"color: #dfcfaf; \""
"operator" = "style=\"color: #f0efd0; \""
"punctuation.delimiter" = "style=\"color: #8f8f8f;\""
"special" = "style=\"color: #cfbfaf;\""
"string" = "style=\"color: #cc9393;\""
"type" = "style=\"font-weight: bold; color: #dfdfbf; \""
"variable" = "style=\"color: #dcdccc;\""
"variable.builtin" = "style=\"font-weight: bold; color: #dca3a3; \""
"variable.other.member" = "style=\"color: #efef8f;\""
