name: Elixir

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env:
  MIX_ENV: test
  AUTUMN_BUILD: true
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "test: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }} | Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "24"
            elixir: "1.14.0"
            rust: "1.86.0"

          - otp: "27"
            elixir: "1.18"
            rust: "1.86.0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            native/autumnus_nif/target
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-cargo-${{ hashFiles('native/autumnus_nif/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-cargo-
            ${{ runner.os }}-mix-

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - run: mix deps.get

      - run: mix test

  quality:
    name: "quality: OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: "27"
            elixir: "1.18"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - run: mix deps.get

      - run: mix compile --warnings-as-errors

      - run: mix deps.unlock --unused

      - run: mix format

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: --force
