name: NIF Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: leandrocp/github-actions/.github/workflows/nif-release.yml@main
    with:
      project-name: autumnus_nif
      project-dir: native/autumnus_nif
