name: Rust CI
on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - native/autumnus_nif/Cargo.toml

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort

      - name: Install cargo-sort-derives
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort-derives

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            native/autumnus_nif

      - run: cargo sort

      - run: cargo sort-derives

      - run: cargo fmt

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: --force

      - run: cargo test --all-features

      - run: cargo clippy --all-targets --all-features -- -D warnings
