name: Rust Quality Check

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    name: "quality: Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: "1.86.0"

    defaults:
      run:
        working-directory: native/autumnus_nif

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: clippy

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort

      - name: Install cargo-sort-derives
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort-derives

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            native/autumnus_nif

      - run: cargo sort

      - run: cargo sort-derives

      - run: cargo fmt

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: --force

      - run: cargo test --all-features

      - run: cargo clippy -- -Dwarnings
