name: Rust

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        manifest:
          - native/autumnus_nif/Cargo.toml

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: clippy

      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort

      - name: Install cargo-sort-derives
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort-derives

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            native/autumnus_nif

      - name: cargo sort
      - run: |
          (cd native/autumnus_nif && cargo sort)

      - name: cargo sort-derives
        run: |
          (cd native/autumnus_nif && cargo sort-derives)

      - name: cargo fmt
        run: |
          (cd native/autumnus_nif && cargo fmt)

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: --force

      - name: cargo test
        run: |
          (cd native/autumnus_nif && cargo test --all-features)

      - name: cargo clipppy
        run: |
          (cd native/autumnus_nif && cargo clippy -- -Dwarnings)
