name: Rust CI
on:
  push:
    branches:
      - main
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_dispatch:

jobs:
  lint-rust:
    name: Lint Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest:
          - native/autumnus_nif/Cargo.toml

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            native/autumnus_nif

      - name: fmt
        run: cargo fmt --manifest-path=${{ matrix.manifest }} --all -- --check

      - name: clippy
        run: cargo clippy --manifest-path=${{ matrix.manifest }} -- -Dwarnings
